# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_manager.ui'
#
# Created: Thu Apr 16 16:15:23 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapbioManager(object):
    def setupUi(self, mapbioManager):
        mapbioManager.setObjectName(_fromUtf8("mapbioManager"))
        mapbioManager.resize(796, 664)
        self.gridLayout2 = QtGui.QGridLayout(mapbioManager)
        self.gridLayout2.setObjectName(_fromUtf8("gridLayout2"))
        self.twMapBioSettings = QtGui.QTabWidget(mapbioManager)
        self.twMapBioSettings.setObjectName(_fromUtf8("twMapBioSettings"))
        self.tbSettings = QtGui.QWidget()
        self.tbSettings.setObjectName(_fromUtf8("tbSettings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tbSettings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.glMapBioSettings = QtGui.QGridLayout()
        self.glMapBioSettings.setObjectName(_fromUtf8("glMapBioSettings"))
        self.lblMaxScale = QtGui.QLabel(self.tbSettings)
        self.lblMaxScale.setObjectName(_fromUtf8("lblMaxScale"))
        self.glMapBioSettings.addWidget(self.lblMaxScale, 2, 0, 1, 1)
        self.cbMinScale = QtGui.QComboBox(self.tbSettings)
        self.cbMinScale.setObjectName(_fromUtf8("cbMinScale"))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.glMapBioSettings.addWidget(self.cbMinScale, 3, 1, 1, 1)
        self.cbMaxScale = QtGui.QComboBox(self.tbSettings)
        self.cbMaxScale.setObjectName(_fromUtf8("cbMaxScale"))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.glMapBioSettings.addWidget(self.cbMaxScale, 2, 1, 1, 1)
        self.cbZoomRangeNotices = QtGui.QComboBox(self.tbSettings)
        self.cbZoomRangeNotices.setObjectName(_fromUtf8("cbZoomRangeNotices"))
        self.cbZoomRangeNotices.addItem(_fromUtf8(""))
        self.cbZoomRangeNotices.addItem(_fromUtf8(""))
        self.glMapBioSettings.addWidget(self.cbZoomRangeNotices, 4, 1, 1, 1)
        self.lblZoomNotices = QtGui.QLabel(self.tbSettings)
        self.lblZoomNotices.setObjectName(_fromUtf8("lblZoomNotices"))
        self.glMapBioSettings.addWidget(self.lblZoomNotices, 4, 0, 1, 1)
        self.lblProjectsDir = QtGui.QLabel(self.tbSettings)
        self.lblProjectsDir.setObjectName(_fromUtf8("lblProjectsDir"))
        self.glMapBioSettings.addWidget(self.lblProjectsDir, 0, 0, 1, 1)
        self.cbProjectDatabase = QtGui.QComboBox(self.tbSettings)
        self.cbProjectDatabase.setObjectName(_fromUtf8("cbProjectDatabase"))
        self.glMapBioSettings.addWidget(self.cbProjectDatabase, 1, 1, 1, 1)
        self.lblProjectDatabase = QtGui.QLabel(self.tbSettings)
        self.lblProjectDatabase.setObjectName(_fromUtf8("lblProjectDatabase"))
        self.glMapBioSettings.addWidget(self.lblProjectDatabase, 1, 0, 1, 1)
        self.hlProjectDir = QtGui.QHBoxLayout()
        self.hlProjectDir.setObjectName(_fromUtf8("hlProjectDir"))
        self.leProjectDir = QtGui.QLineEdit(self.tbSettings)
        self.leProjectDir.setEnabled(True)
        self.leProjectDir.setReadOnly(True)
        self.leProjectDir.setObjectName(_fromUtf8("leProjectDir"))
        self.hlProjectDir.addWidget(self.leProjectDir)
        self.tbSelectProjectDir = QtGui.QToolButton(self.tbSettings)
        self.tbSelectProjectDir.setObjectName(_fromUtf8("tbSelectProjectDir"))
        self.hlProjectDir.addWidget(self.tbSelectProjectDir)
        self.glMapBioSettings.addLayout(self.hlProjectDir, 0, 1, 1, 1)
        self.lblMinScale = QtGui.QLabel(self.tbSettings)
        self.lblMinScale.setObjectName(_fromUtf8("lblMinScale"))
        self.glMapBioSettings.addWidget(self.lblMinScale, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.glMapBioSettings, 0, 0, 1, 1)
        self.flQGISSettings = QtGui.QFormLayout()
        self.flQGISSettings.setObjectName(_fromUtf8("flQGISSettings"))
        self.lblQgsProject = QtGui.QLabel(self.tbSettings)
        self.lblQgsProject.setObjectName(_fromUtf8("lblQgsProject"))
        self.flQGISSettings.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblQgsProject)
        self.hlQgsProject = QtGui.QHBoxLayout()
        self.hlQgsProject.setObjectName(_fromUtf8("hlQgsProject"))
        self.leQgsProject = QtGui.QLineEdit(self.tbSettings)
        self.leQgsProject.setEnabled(True)
        self.leQgsProject.setReadOnly(True)
        self.leQgsProject.setObjectName(_fromUtf8("leQgsProject"))
        self.hlQgsProject.addWidget(self.leQgsProject)
        self.tbSelectQgsProject = QtGui.QToolButton(self.tbSettings)
        self.tbSelectQgsProject.setObjectName(_fromUtf8("tbSelectQgsProject"))
        self.hlQgsProject.addWidget(self.tbSelectQgsProject)
        self.flQGISSettings.setLayout(0, QtGui.QFormLayout.FieldRole, self.hlQgsProject)
        self.hlBaseLayers = QtGui.QHBoxLayout()
        self.hlBaseLayers.setObjectName(_fromUtf8("hlBaseLayers"))
        self.tblBaseGroups = QtGui.QTableWidget(self.tbSettings)
        self.tblBaseGroups.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblBaseGroups.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblBaseGroups.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblBaseGroups.setObjectName(_fromUtf8("tblBaseGroups"))
        self.tblBaseGroups.setColumnCount(0)
        self.tblBaseGroups.setRowCount(0)
        self.hlBaseLayers.addWidget(self.tblBaseGroups)
        self.vlBaseGroupActions = QtGui.QVBoxLayout()
        self.vlBaseGroupActions.setObjectName(_fromUtf8("vlBaseGroupActions"))
        self.lblBaseGroupOptions = QtGui.QLabel(self.tbSettings)
        self.lblBaseGroupOptions.setMinimumSize(QtCore.QSize(200, 0))
        self.lblBaseGroupOptions.setObjectName(_fromUtf8("lblBaseGroupOptions"))
        self.vlBaseGroupActions.addWidget(self.lblBaseGroupOptions)
        self.cbProjectGroups = QtGui.QComboBox(self.tbSettings)
        self.cbProjectGroups.setObjectName(_fromUtf8("cbProjectGroups"))
        self.vlBaseGroupActions.addWidget(self.cbProjectGroups)
        self.hlBaseGroups = QtGui.QHBoxLayout()
        self.hlBaseGroups.setObjectName(_fromUtf8("hlBaseGroups"))
        self.pbAddBaseGroup = QtGui.QPushButton(self.tbSettings)
        self.pbAddBaseGroup.setObjectName(_fromUtf8("pbAddBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbAddBaseGroup)
        self.pbRemoveBaseGroup = QtGui.QPushButton(self.tbSettings)
        self.pbRemoveBaseGroup.setEnabled(False)
        self.pbRemoveBaseGroup.setObjectName(_fromUtf8("pbRemoveBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbRemoveBaseGroup)
        self.vlBaseGroupActions.addLayout(self.hlBaseGroups)
        self.hlBaseLayers.addLayout(self.vlBaseGroupActions)
        self.flQGISSettings.setLayout(1, QtGui.QFormLayout.FieldRole, self.hlBaseLayers)
        self.lblBaseLayerGroups = QtGui.QLabel(self.tbSettings)
        self.lblBaseLayerGroups.setMinimumSize(QtCore.QSize(176, 0))
        self.lblBaseLayerGroups.setObjectName(_fromUtf8("lblBaseLayerGroups"))
        self.flQGISSettings.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblBaseLayerGroups)
        self.cbBoundaryLayer = QtGui.QComboBox(self.tbSettings)
        self.cbBoundaryLayer.setObjectName(_fromUtf8("cbBoundaryLayer"))
        self.flQGISSettings.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbBoundaryLayer)
        self.lblProjectBoundary = QtGui.QLabel(self.tbSettings)
        self.lblProjectBoundary.setObjectName(_fromUtf8("lblProjectBoundary"))
        self.flQGISSettings.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblProjectBoundary)
        self.lblEnableReference = QtGui.QLabel(self.tbSettings)
        self.lblEnableReference.setObjectName(_fromUtf8("lblEnableReference"))
        self.flQGISSettings.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblEnableReference)
        self.cbEnableReference = QtGui.QComboBox(self.tbSettings)
        self.cbEnableReference.setObjectName(_fromUtf8("cbEnableReference"))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.flQGISSettings.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbEnableReference)
        self.lblReferenceLayer = QtGui.QLabel(self.tbSettings)
        self.lblReferenceLayer.setObjectName(_fromUtf8("lblReferenceLayer"))
        self.flQGISSettings.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblReferenceLayer)
        self.cbReferenceLayer = QtGui.QComboBox(self.tbSettings)
        self.cbReferenceLayer.setObjectName(_fromUtf8("cbReferenceLayer"))
        self.flQGISSettings.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbReferenceLayer)
        self.gridLayout_2.addLayout(self.flQGISSettings, 1, 0, 1, 1)
        self.hlnSettingsAboveButtons = QtGui.QFrame(self.tbSettings)
        self.hlnSettingsAboveButtons.setFrameShape(QtGui.QFrame.HLine)
        self.hlnSettingsAboveButtons.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnSettingsAboveButtons.setObjectName(_fromUtf8("hlnSettingsAboveButtons"))
        self.gridLayout_2.addWidget(self.hlnSettingsAboveButtons, 2, 0, 1, 1)
        self.hlSettingsButtons = QtGui.QHBoxLayout()
        self.hlSettingsButtons.setObjectName(_fromUtf8("hlSettingsButtons"))
        self.pbSaveSettings = QtGui.QPushButton(self.tbSettings)
        self.pbSaveSettings.setObjectName(_fromUtf8("pbSaveSettings"))
        self.hlSettingsButtons.addWidget(self.pbSaveSettings)
        self.pbCancelSettings = QtGui.QPushButton(self.tbSettings)
        self.pbCancelSettings.setObjectName(_fromUtf8("pbCancelSettings"))
        self.hlSettingsButtons.addWidget(self.pbCancelSettings)
        self.pbTransfer = QtGui.QPushButton(self.tbSettings)
        self.pbTransfer.setObjectName(_fromUtf8("pbTransfer"))
        self.hlSettingsButtons.addWidget(self.pbTransfer)
        self.gridLayout_2.addLayout(self.hlSettingsButtons, 3, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbSettings, _fromUtf8(""))
        self.tbProjectDetails = QtGui.QWidget()
        self.tbProjectDetails.setObjectName(_fromUtf8("tbProjectDetails"))
        self.gridLayout3 = QtGui.QGridLayout(self.tbProjectDetails)
        self.gridLayout3.setObjectName(_fromUtf8("gridLayout3"))
        self.frContentCode = QtGui.QFrame(self.tbProjectDetails)
        self.frContentCode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frContentCode.setFrameShadow(QtGui.QFrame.Plain)
        self.frContentCode.setObjectName(_fromUtf8("frContentCode"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frContentCode)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vlProjectDetails = QtGui.QVBoxLayout()
        self.vlProjectDetails.setObjectName(_fromUtf8("vlProjectDetails"))
        self.lblProjCode = QtGui.QLabel(self.frContentCode)
        self.lblProjCode.setObjectName(_fromUtf8("lblProjCode"))
        self.vlProjectDetails.addWidget(self.lblProjCode)
        self.leProjectCode = QtGui.QLineEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectCode.sizePolicy().hasHeightForWidth())
        self.leProjectCode.setSizePolicy(sizePolicy)
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.vlProjectDetails.addWidget(self.leProjectCode)
        self.lblProjTags = QtGui.QLabel(self.frContentCode)
        self.lblProjTags.setObjectName(_fromUtf8("lblProjTags"))
        self.vlProjectDetails.addWidget(self.lblProjTags)
        self.leProjectTags = QtGui.QLineEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectTags.sizePolicy().hasHeightForWidth())
        self.leProjectTags.setSizePolicy(sizePolicy)
        self.leProjectTags.setObjectName(_fromUtf8("leProjectTags"))
        self.vlProjectDetails.addWidget(self.leProjectTags)
        self.lblProjDescription = QtGui.QLabel(self.frContentCode)
        self.lblProjDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjDescription.setObjectName(_fromUtf8("lblProjDescription"))
        self.vlProjectDetails.addWidget(self.lblProjDescription)
        self.pteProjectDescription = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteProjectDescription.sizePolicy().hasHeightForWidth())
        self.pteProjectDescription.setSizePolicy(sizePolicy)
        self.pteProjectDescription.setMinimumSize(QtCore.QSize(0, 50))
        self.pteProjectDescription.setObjectName(_fromUtf8("pteProjectDescription"))
        self.vlProjectDetails.addWidget(self.pteProjectDescription)
        self.lblTimeOfYear = QtGui.QLabel(self.frContentCode)
        self.lblTimeOfYear.setObjectName(_fromUtf8("lblTimeOfYear"))
        self.vlProjectDetails.addWidget(self.lblTimeOfYear)
        self.pteTimeOfYear = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteTimeOfYear.sizePolicy().hasHeightForWidth())
        self.pteTimeOfYear.setSizePolicy(sizePolicy)
        self.pteTimeOfYear.setMinimumSize(QtCore.QSize(0, 50))
        self.pteTimeOfYear.setObjectName(_fromUtf8("pteTimeOfYear"))
        self.vlProjectDetails.addWidget(self.pteTimeOfYear)
        self.lblDateAndTime = QtGui.QLabel(self.frContentCode)
        self.lblDateAndTime.setObjectName(_fromUtf8("lblDateAndTime"))
        self.vlProjectDetails.addWidget(self.lblDateAndTime)
        self.pteDateAndTime = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteDateAndTime.sizePolicy().hasHeightForWidth())
        self.pteDateAndTime.setSizePolicy(sizePolicy)
        self.pteDateAndTime.setMinimumSize(QtCore.QSize(0, 50))
        self.pteDateAndTime.setObjectName(_fromUtf8("pteDateAndTime"))
        self.vlProjectDetails.addWidget(self.pteDateAndTime)
        self.gridLayout_3.addLayout(self.vlProjectDetails, 0, 0, 1, 1)
        self.vlContentCoding = QtGui.QVBoxLayout()
        self.vlContentCoding.setObjectName(_fromUtf8("vlContentCoding"))
        self.lblContentCodes = QtGui.QLabel(self.frContentCode)
        self.lblContentCodes.setObjectName(_fromUtf8("lblContentCodes"))
        self.vlContentCoding.addWidget(self.lblContentCodes)
        self.pteContentCodes = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteContentCodes.sizePolicy().hasHeightForWidth())
        self.pteContentCodes.setSizePolicy(sizePolicy)
        self.pteContentCodes.setMinimumSize(QtCore.QSize(0, 50))
        self.pteContentCodes.setObjectName(_fromUtf8("pteContentCodes"))
        self.vlContentCoding.addWidget(self.pteContentCodes)
        self.glContentCodes = QtGui.QGridLayout()
        self.glContentCodes.setObjectName(_fromUtf8("glContentCodes"))
        self.cbDefaultCode = QtGui.QComboBox(self.frContentCode)
        self.cbDefaultCode.setObjectName(_fromUtf8("cbDefaultCode"))
        self.glContentCodes.addWidget(self.cbDefaultCode, 0, 1, 1, 1)
        self.lblDefaultPointCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultPointCode.setObjectName(_fromUtf8("lblDefaultPointCode"))
        self.glContentCodes.addWidget(self.lblDefaultPointCode, 1, 0, 1, 1)
        self.lblDefaultCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultCode.setObjectName(_fromUtf8("lblDefaultCode"))
        self.glContentCodes.addWidget(self.lblDefaultCode, 0, 0, 1, 1)
        self.cbPointCode = QtGui.QComboBox(self.frContentCode)
        self.cbPointCode.setObjectName(_fromUtf8("cbPointCode"))
        self.glContentCodes.addWidget(self.cbPointCode, 1, 1, 1, 1)
        self.lblDefaultPolygonCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultPolygonCode.setObjectName(_fromUtf8("lblDefaultPolygonCode"))
        self.glContentCodes.addWidget(self.lblDefaultPolygonCode, 3, 0, 1, 1)
        self.lblDefaultLineCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultLineCode.setObjectName(_fromUtf8("lblDefaultLineCode"))
        self.glContentCodes.addWidget(self.lblDefaultLineCode, 2, 0, 1, 1)
        self.cbLineCode = QtGui.QComboBox(self.frContentCode)
        self.cbLineCode.setObjectName(_fromUtf8("cbLineCode"))
        self.glContentCodes.addWidget(self.cbLineCode, 2, 1, 1, 1)
        self.cbPolygonCode = QtGui.QComboBox(self.frContentCode)
        self.cbPolygonCode.setObjectName(_fromUtf8("cbPolygonCode"))
        self.glContentCodes.addWidget(self.cbPolygonCode, 3, 1, 1, 1)
        self.vlContentCoding.addLayout(self.glContentCodes)
        self.gridLayout_3.addLayout(self.vlContentCoding, 0, 1, 1, 1)
        self.gridLayout3.addWidget(self.frContentCode, 0, 0, 1, 1)
        self.lblProjNote = QtGui.QLabel(self.tbProjectDetails)
        self.lblProjNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjNote.setObjectName(_fromUtf8("lblProjNote"))
        self.gridLayout3.addWidget(self.lblProjNote, 1, 0, 1, 1)
        self.pteProjectNote = QtGui.QPlainTextEdit(self.tbProjectDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteProjectNote.sizePolicy().hasHeightForWidth())
        self.pteProjectNote.setSizePolicy(sizePolicy)
        self.pteProjectNote.setMinimumSize(QtCore.QSize(0, 75))
        self.pteProjectNote.setObjectName(_fromUtf8("pteProjectNote"))
        self.gridLayout3.addWidget(self.pteProjectNote, 2, 0, 1, 1)
        self.hlProjectButtons = QtGui.QHBoxLayout()
        self.hlProjectButtons.setObjectName(_fromUtf8("hlProjectButtons"))
        self.pbProjectSave = QtGui.QPushButton(self.tbProjectDetails)
        self.pbProjectSave.setObjectName(_fromUtf8("pbProjectSave"))
        self.hlProjectButtons.addWidget(self.pbProjectSave)
        self.pbProjectCancel = QtGui.QPushButton(self.tbProjectDetails)
        self.pbProjectCancel.setEnabled(True)
        self.pbProjectCancel.setObjectName(_fromUtf8("pbProjectCancel"))
        self.hlProjectButtons.addWidget(self.pbProjectCancel)
        self.gridLayout3.addLayout(self.hlProjectButtons, 3, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbProjectDetails, _fromUtf8(""))
        self.tbPeople = QtGui.QWidget()
        self.tbPeople.setObjectName(_fromUtf8("tbPeople"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tbPeople)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.lblParticipants = QtGui.QLabel(self.tbPeople)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.gridLayout_18.addWidget(self.lblParticipants, 0, 0, 1, 1)
        self.tblParticipants = QtGui.QTableWidget(self.tbPeople)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblParticipants.sizePolicy().hasHeightForWidth())
        self.tblParticipants.setSizePolicy(sizePolicy)
        self.tblParticipants.setMinimumSize(QtCore.QSize(0, 100))
        self.tblParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblParticipants.setTabKeyNavigation(False)
        self.tblParticipants.setProperty("showDropIndicator", False)
        self.tblParticipants.setDragDropOverwriteMode(False)
        self.tblParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblParticipants.setObjectName(_fromUtf8("tblParticipants"))
        self.tblParticipants.setColumnCount(0)
        self.tblParticipants.setRowCount(0)
        self.gridLayout_18.addWidget(self.tblParticipants, 1, 0, 1, 1)
        self.tbxParticipants = QtGui.QToolBox(self.tbPeople)
        self.tbxParticipants.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbxParticipants.sizePolicy().hasHeightForWidth())
        self.tbxParticipants.setSizePolicy(sizePolicy)
        self.tbxParticipants.setMinimumSize(QtCore.QSize(0, 365))
        self.tbxParticipants.setObjectName(_fromUtf8("tbxParticipants"))
        self.pgBasicInfo = QtGui.QWidget()
        self.pgBasicInfo.setGeometry(QtCore.QRect(0, 0, 756, 260))
        self.pgBasicInfo.setObjectName(_fromUtf8("pgBasicInfo"))
        self.gridLayout_15 = QtGui.QGridLayout(self.pgBasicInfo)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.glParticipants = QtGui.QGridLayout()
        self.glParticipants.setObjectName(_fromUtf8("glParticipants"))
        self.lblFamilyGroup = QtGui.QLabel(self.pgBasicInfo)
        self.lblFamilyGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFamilyGroup.setObjectName(_fromUtf8("lblFamilyGroup"))
        self.glParticipants.addWidget(self.lblFamilyGroup, 5, 0, 1, 1)
        self.lblEmail = QtGui.QLabel(self.pgBasicInfo)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.glParticipants.addWidget(self.lblEmail, 3, 0, 1, 1)
        self.lblCommunityName = QtGui.QLabel(self.pgBasicInfo)
        self.lblCommunityName.setObjectName(_fromUtf8("lblCommunityName"))
        self.glParticipants.addWidget(self.lblCommunityName, 4, 0, 1, 1)
        self.leFirstName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leFirstName.setObjectName(_fromUtf8("leFirstName"))
        self.glParticipants.addWidget(self.leFirstName, 1, 2, 1, 1)
        self.leCommunity = QtGui.QLineEdit(self.pgBasicInfo)
        self.leCommunity.setObjectName(_fromUtf8("leCommunity"))
        self.glParticipants.addWidget(self.leCommunity, 4, 2, 1, 1)
        self.leEmail = QtGui.QLineEdit(self.pgBasicInfo)
        self.leEmail.setObjectName(_fromUtf8("leEmail"))
        self.glParticipants.addWidget(self.leEmail, 3, 2, 1, 1)
        self.lblParticipantCode = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantCode.setObjectName(_fromUtf8("lblParticipantCode"))
        self.glParticipants.addWidget(self.lblParticipantCode, 0, 0, 1, 1)
        self.lblFirstName = QtGui.QLabel(self.pgBasicInfo)
        self.lblFirstName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.glParticipants.addWidget(self.lblFirstName, 1, 0, 1, 1)
        self.lblLastName = QtGui.QLabel(self.pgBasicInfo)
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.glParticipants.addWidget(self.lblLastName, 2, 0, 1, 1)
        self.leFamily = QtGui.QLineEdit(self.pgBasicInfo)
        self.leFamily.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leFamily.setObjectName(_fromUtf8("leFamily"))
        self.glParticipants.addWidget(self.leFamily, 5, 2, 1, 1)
        self.leParticipantCode = QtGui.QLineEdit(self.pgBasicInfo)
        self.leParticipantCode.setObjectName(_fromUtf8("leParticipantCode"))
        self.glParticipants.addWidget(self.leParticipantCode, 0, 2, 1, 1)
        self.leLastName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leLastName.setObjectName(_fromUtf8("leLastName"))
        self.glParticipants.addWidget(self.leLastName, 2, 2, 1, 1)
        self.lblParticipantTags = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantTags.setObjectName(_fromUtf8("lblParticipantTags"))
        self.glParticipants.addWidget(self.lblParticipantTags, 4, 4, 1, 1)
        self.leParticipantTags = QtGui.QLineEdit(self.pgBasicInfo)
        self.leParticipantTags.setObjectName(_fromUtf8("leParticipantTags"))
        self.glParticipants.addWidget(self.leParticipantTags, 4, 6, 1, 1)
        self.lblBirthDate = QtGui.QLabel(self.pgBasicInfo)
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.glParticipants.addWidget(self.lblBirthDate, 3, 4, 1, 1)
        self.lblMaritalStatus = QtGui.QLabel(self.pgBasicInfo)
        self.lblMaritalStatus.setObjectName(_fromUtf8("lblMaritalStatus"))
        self.glParticipants.addWidget(self.lblMaritalStatus, 2, 4, 1, 1)
        self.cbMaritalStatus = QtGui.QComboBox(self.pgBasicInfo)
        self.cbMaritalStatus.setObjectName(_fromUtf8("cbMaritalStatus"))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.glParticipants.addWidget(self.cbMaritalStatus, 2, 6, 1, 1)
        self.lblGender = QtGui.QLabel(self.pgBasicInfo)
        self.lblGender.setObjectName(_fromUtf8("lblGender"))
        self.glParticipants.addWidget(self.lblGender, 1, 4, 1, 1)
        self.cbGender = QtGui.QComboBox(self.pgBasicInfo)
        self.cbGender.setObjectName(_fromUtf8("cbGender"))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.glParticipants.addWidget(self.cbGender, 1, 6, 1, 1)
        self.lblMaidenName = QtGui.QLabel(self.pgBasicInfo)
        self.lblMaidenName.setObjectName(_fromUtf8("lblMaidenName"))
        self.glParticipants.addWidget(self.lblMaidenName, 0, 4, 1, 1)
        self.leMaidenName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leMaidenName.setObjectName(_fromUtf8("leMaidenName"))
        self.glParticipants.addWidget(self.leMaidenName, 0, 6, 1, 1)
        self.lblParticipantNotes = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblParticipantNotes.setObjectName(_fromUtf8("lblParticipantNotes"))
        self.glParticipants.addWidget(self.lblParticipantNotes, 5, 4, 1, 1)
        self.pteParticipantNote = QtGui.QPlainTextEdit(self.pgBasicInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteParticipantNote.sizePolicy().hasHeightForWidth())
        self.pteParticipantNote.setSizePolicy(sizePolicy)
        self.pteParticipantNote.setMinimumSize(QtCore.QSize(0, 50))
        self.pteParticipantNote.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteParticipantNote.setObjectName(_fromUtf8("pteParticipantNote"))
        self.glParticipants.addWidget(self.pteParticipantNote, 5, 6, 1, 1)
        self.leBirthDate = QtGui.QLineEdit(self.pgBasicInfo)
        self.leBirthDate.setObjectName(_fromUtf8("leBirthDate"))
        self.glParticipants.addWidget(self.leBirthDate, 3, 6, 1, 1)
        self.gridLayout_15.addLayout(self.glParticipants, 0, 0, 1, 1)
        self.tbxParticipants.addItem(self.pgBasicInfo, _fromUtf8(""))
        self.pgAddresses = QtGui.QWidget()
        self.pgAddresses.setGeometry(QtCore.QRect(0, 0, 531, 267))
        self.pgAddresses.setObjectName(_fromUtf8("pgAddresses"))
        self.gridLayout_16 = QtGui.QGridLayout(self.pgAddresses)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.vlAddressList = QtGui.QVBoxLayout()
        self.vlAddressList.setObjectName(_fromUtf8("vlAddressList"))
        self.lblAddresses = QtGui.QLabel(self.pgAddresses)
        self.lblAddresses.setObjectName(_fromUtf8("lblAddresses"))
        self.vlAddressList.addWidget(self.lblAddresses)
        self.tblAddresses = QtGui.QTableWidget(self.pgAddresses)
        self.tblAddresses.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblAddresses.setTabKeyNavigation(False)
        self.tblAddresses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblAddresses.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAddresses.setObjectName(_fromUtf8("tblAddresses"))
        self.tblAddresses.setColumnCount(0)
        self.tblAddresses.setRowCount(0)
        self.vlAddressList.addWidget(self.tblAddresses)
        self.hlAddressList = QtGui.QHBoxLayout()
        self.hlAddressList.setObjectName(_fromUtf8("hlAddressList"))
        self.pbAddNew = QtGui.QPushButton(self.pgAddresses)
        self.pbAddNew.setObjectName(_fromUtf8("pbAddNew"))
        self.hlAddressList.addWidget(self.pbAddNew)
        self.pbAddSave = QtGui.QPushButton(self.pgAddresses)
        self.pbAddSave.setEnabled(False)
        self.pbAddSave.setObjectName(_fromUtf8("pbAddSave"))
        self.hlAddressList.addWidget(self.pbAddSave)
        self.pbAddCancel = QtGui.QPushButton(self.pgAddresses)
        self.pbAddCancel.setEnabled(False)
        self.pbAddCancel.setObjectName(_fromUtf8("pbAddCancel"))
        self.hlAddressList.addWidget(self.pbAddCancel)
        self.pbAddDelete = QtGui.QPushButton(self.pgAddresses)
        self.pbAddDelete.setEnabled(False)
        self.pbAddDelete.setObjectName(_fromUtf8("pbAddDelete"))
        self.hlAddressList.addWidget(self.pbAddDelete)
        self.vlAddressList.addLayout(self.hlAddressList)
        self.gridLayout_16.addLayout(self.vlAddressList, 0, 0, 1, 1)
        self.grAddresses = QtGui.QGridLayout()
        self.grAddresses.setObjectName(_fromUtf8("grAddresses"))
        self.leLineTwo = QtGui.QLineEdit(self.pgAddresses)
        self.leLineTwo.setObjectName(_fromUtf8("leLineTwo"))
        self.grAddresses.addWidget(self.leLineTwo, 2, 2, 1, 1)
        self.leCity = QtGui.QLineEdit(self.pgAddresses)
        self.leCity.setObjectName(_fromUtf8("leCity"))
        self.grAddresses.addWidget(self.leCity, 3, 2, 1, 1)
        self.lblCountry = QtGui.QLabel(self.pgAddresses)
        self.lblCountry.setObjectName(_fromUtf8("lblCountry"))
        self.grAddresses.addWidget(self.lblCountry, 5, 0, 1, 1)
        self.lblAddType = QtGui.QLabel(self.pgAddresses)
        self.lblAddType.setObjectName(_fromUtf8("lblAddType"))
        self.grAddresses.addWidget(self.lblAddType, 0, 0, 1, 1)
        self.lblLineTwo = QtGui.QLabel(self.pgAddresses)
        self.lblLineTwo.setObjectName(_fromUtf8("lblLineTwo"))
        self.grAddresses.addWidget(self.lblLineTwo, 2, 0, 1, 1)
        self.lblProvince = QtGui.QLabel(self.pgAddresses)
        self.lblProvince.setObjectName(_fromUtf8("lblProvince"))
        self.grAddresses.addWidget(self.lblProvince, 4, 0, 1, 1)
        self.cbAddType = QtGui.QComboBox(self.pgAddresses)
        self.cbAddType.setObjectName(_fromUtf8("cbAddType"))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.grAddresses.addWidget(self.cbAddType, 0, 2, 1, 1)
        self.lblCity = QtGui.QLabel(self.pgAddresses)
        self.lblCity.setObjectName(_fromUtf8("lblCity"))
        self.grAddresses.addWidget(self.lblCity, 3, 0, 1, 1)
        self.leProvince = QtGui.QLineEdit(self.pgAddresses)
        self.leProvince.setObjectName(_fromUtf8("leProvince"))
        self.grAddresses.addWidget(self.leProvince, 4, 2, 1, 1)
        self.leCountry = QtGui.QLineEdit(self.pgAddresses)
        self.leCountry.setObjectName(_fromUtf8("leCountry"))
        self.grAddresses.addWidget(self.leCountry, 5, 2, 1, 1)
        self.lblPostalCode = QtGui.QLabel(self.pgAddresses)
        self.lblPostalCode.setObjectName(_fromUtf8("lblPostalCode"))
        self.grAddresses.addWidget(self.lblPostalCode, 6, 0, 1, 1)
        self.lePostalCode = QtGui.QLineEdit(self.pgAddresses)
        self.lePostalCode.setObjectName(_fromUtf8("lePostalCode"))
        self.grAddresses.addWidget(self.lePostalCode, 6, 2, 1, 1)
        self.lblLineOne = QtGui.QLabel(self.pgAddresses)
        self.lblLineOne.setObjectName(_fromUtf8("lblLineOne"))
        self.grAddresses.addWidget(self.lblLineOne, 1, 0, 1, 1)
        self.leLineOne = QtGui.QLineEdit(self.pgAddresses)
        self.leLineOne.setObjectName(_fromUtf8("leLineOne"))
        self.grAddresses.addWidget(self.leLineOne, 1, 2, 1, 1)
        self.gridLayout_16.addLayout(self.grAddresses, 0, 1, 1, 1)
        self.tbxParticipants.addItem(self.pgAddresses, _fromUtf8(""))
        self.pgTelecoms = QtGui.QWidget()
        self.pgTelecoms.setGeometry(QtCore.QRect(0, 0, 498, 143))
        self.pgTelecoms.setObjectName(_fromUtf8("pgTelecoms"))
        self.gridLayout_17 = QtGui.QGridLayout(self.pgTelecoms)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.vlTelecomList = QtGui.QVBoxLayout()
        self.vlTelecomList.setObjectName(_fromUtf8("vlTelecomList"))
        self.lblTelecoms = QtGui.QLabel(self.pgTelecoms)
        self.lblTelecoms.setObjectName(_fromUtf8("lblTelecoms"))
        self.vlTelecomList.addWidget(self.lblTelecoms)
        self.tblTelecoms = QtGui.QTableWidget(self.pgTelecoms)
        self.tblTelecoms.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblTelecoms.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblTelecoms.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblTelecoms.setObjectName(_fromUtf8("tblTelecoms"))
        self.tblTelecoms.setColumnCount(0)
        self.tblTelecoms.setRowCount(0)
        self.vlTelecomList.addWidget(self.tblTelecoms)
        self.hlTelecomList = QtGui.QHBoxLayout()
        self.hlTelecomList.setObjectName(_fromUtf8("hlTelecomList"))
        self.pbTelNew = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelNew.setObjectName(_fromUtf8("pbTelNew"))
        self.hlTelecomList.addWidget(self.pbTelNew)
        self.pbTelSave = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelSave.setEnabled(False)
        self.pbTelSave.setObjectName(_fromUtf8("pbTelSave"))
        self.hlTelecomList.addWidget(self.pbTelSave)
        self.pbTelCancel = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelCancel.setEnabled(False)
        self.pbTelCancel.setObjectName(_fromUtf8("pbTelCancel"))
        self.hlTelecomList.addWidget(self.pbTelCancel)
        self.pbTelDelete = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelDelete.setEnabled(False)
        self.pbTelDelete.setObjectName(_fromUtf8("pbTelDelete"))
        self.hlTelecomList.addWidget(self.pbTelDelete)
        self.vlTelecomList.addLayout(self.hlTelecomList)
        self.gridLayout_17.addLayout(self.vlTelecomList, 0, 0, 1, 1)
        self.glTelecoms = QtGui.QGridLayout()
        self.glTelecoms.setObjectName(_fromUtf8("glTelecoms"))
        self.lblTelType = QtGui.QLabel(self.pgTelecoms)
        self.lblTelType.setObjectName(_fromUtf8("lblTelType"))
        self.glTelecoms.addWidget(self.lblTelType, 0, 0, 1, 1)
        self.cbTelType = QtGui.QComboBox(self.pgTelecoms)
        self.cbTelType.setObjectName(_fromUtf8("cbTelType"))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.glTelecoms.addWidget(self.cbTelType, 0, 1, 1, 1)
        self.lblTelecom = QtGui.QLabel(self.pgTelecoms)
        self.lblTelecom.setObjectName(_fromUtf8("lblTelecom"))
        self.glTelecoms.addWidget(self.lblTelecom, 1, 0, 1, 1)
        self.leTelNumber = QtGui.QLineEdit(self.pgTelecoms)
        self.leTelNumber.setObjectName(_fromUtf8("leTelNumber"))
        self.glTelecoms.addWidget(self.leTelNumber, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.glTelecoms.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout_17.addLayout(self.glTelecoms, 0, 1, 1, 1)
        self.tbxParticipants.addItem(self.pgTelecoms, _fromUtf8(""))
        self.gridLayout_18.addWidget(self.tbxParticipants, 3, 0, 1, 1)
        self.frPeopleControls = QtGui.QFrame(self.tbPeople)
        self.frPeopleControls.setObjectName(_fromUtf8("frPeopleControls"))
        self.hzParticipantList = QtGui.QHBoxLayout(self.frPeopleControls)
        self.hzParticipantList.setObjectName(_fromUtf8("hzParticipantList"))
        self.pbParticipantNew = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantNew.setObjectName(_fromUtf8("pbParticipantNew"))
        self.hzParticipantList.addWidget(self.pbParticipantNew)
        self.pbParticipantSave = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantSave.setEnabled(False)
        self.pbParticipantSave.setObjectName(_fromUtf8("pbParticipantSave"))
        self.hzParticipantList.addWidget(self.pbParticipantSave)
        self.pbParticipantCancel = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantCancel.setEnabled(False)
        self.pbParticipantCancel.setObjectName(_fromUtf8("pbParticipantCancel"))
        self.hzParticipantList.addWidget(self.pbParticipantCancel)
        self.pbParticipantDelete = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantDelete.setEnabled(False)
        self.pbParticipantDelete.setObjectName(_fromUtf8("pbParticipantDelete"))
        self.hzParticipantList.addWidget(self.pbParticipantDelete)
        self.gridLayout_18.addWidget(self.frPeopleControls, 2, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbPeople, _fromUtf8(""))
        self.tbInterviews = QtGui.QWidget()
        self.tbInterviews.setObjectName(_fromUtf8("tbInterviews"))
        self.gridLayout1 = QtGui.QGridLayout(self.tbInterviews)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.lblInterviews = QtGui.QLabel(self.tbInterviews)
        self.lblInterviews.setObjectName(_fromUtf8("lblInterviews"))
        self.gridLayout1.addWidget(self.lblInterviews, 0, 0, 1, 1)
        self.tblInterviews = QtGui.QTableWidget(self.tbInterviews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblInterviews.sizePolicy().hasHeightForWidth())
        self.tblInterviews.setSizePolicy(sizePolicy)
        self.tblInterviews.setMinimumSize(QtCore.QSize(0, 100))
        self.tblInterviews.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviews.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviews.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviews.setObjectName(_fromUtf8("tblInterviews"))
        self.tblInterviews.setColumnCount(0)
        self.tblInterviews.setRowCount(0)
        self.gridLayout1.addWidget(self.tblInterviews, 1, 0, 1, 1)
        self.tbxInterview = QtGui.QToolBox(self.tbInterviews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbxInterview.sizePolicy().hasHeightForWidth())
        self.tbxInterview.setSizePolicy(sizePolicy)
        self.tbxInterview.setMinimumSize(QtCore.QSize(0, 315))
        self.tbxInterview.setObjectName(_fromUtf8("tbxInterview"))
        self.pgIntBasic = QtGui.QWidget()
        self.pgIntBasic.setGeometry(QtCore.QRect(0, 0, 756, 245))
        self.pgIntBasic.setObjectName(_fromUtf8("pgIntBasic"))
        self.gridLayout_19 = QtGui.QGridLayout(self.pgIntBasic)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.glInterview = QtGui.QGridLayout()
        self.glInterview.setHorizontalSpacing(6)
        self.glInterview.setVerticalSpacing(2)
        self.glInterview.setObjectName(_fromUtf8("glInterview"))
        self.lblCode = QtGui.QLabel(self.pgIntBasic)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.glInterview.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblDescription = QtGui.QLabel(self.pgIntBasic)
        self.lblDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.glInterview.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.lblStartDateTime = QtGui.QLabel(self.pgIntBasic)
        self.lblStartDateTime.setObjectName(_fromUtf8("lblStartDateTime"))
        self.glInterview.addWidget(self.lblStartDateTime, 2, 0, 1, 1)
        self.leInterviewCode = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewCode.sizePolicy().hasHeightForWidth())
        self.leInterviewCode.setSizePolicy(sizePolicy)
        self.leInterviewCode.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leInterviewCode.setObjectName(_fromUtf8("leInterviewCode"))
        self.glInterview.addWidget(self.leInterviewCode, 0, 1, 1, 1)
        self.lblNotes = QtGui.QLabel(self.pgIntBasic)
        self.lblNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNotes.setObjectName(_fromUtf8("lblNotes"))
        self.glInterview.addWidget(self.lblNotes, 1, 2, 1, 1)
        self.pteInterviewNote = QtGui.QPlainTextEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteInterviewNote.sizePolicy().hasHeightForWidth())
        self.pteInterviewNote.setSizePolicy(sizePolicy)
        self.pteInterviewNote.setMinimumSize(QtCore.QSize(50, 0))
        self.pteInterviewNote.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteInterviewNote.setObjectName(_fromUtf8("pteInterviewNote"))
        self.glInterview.addWidget(self.pteInterviewNote, 1, 3, 1, 1)
        self.lblEndDateTime = QtGui.QLabel(self.pgIntBasic)
        self.lblEndDateTime.setObjectName(_fromUtf8("lblEndDateTime"))
        self.glInterview.addWidget(self.lblEndDateTime, 4, 0, 1, 1)
        self.lblLocation = QtGui.QLabel(self.pgIntBasic)
        self.lblLocation.setObjectName(_fromUtf8("lblLocation"))
        self.glInterview.addWidget(self.lblLocation, 0, 2, 1, 1)
        self.leInterviewLocation = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewLocation.sizePolicy().hasHeightForWidth())
        self.leInterviewLocation.setSizePolicy(sizePolicy)
        self.leInterviewLocation.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewLocation.setObjectName(_fromUtf8("leInterviewLocation"))
        self.glInterview.addWidget(self.leInterviewLocation, 0, 3, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.pgIntBasic)
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.glInterview.addWidget(self.lblSecurity, 2, 2, 1, 1)
        self.lblInterviewerCreator = QtGui.QLabel(self.pgIntBasic)
        self.lblInterviewerCreator.setObjectName(_fromUtf8("lblInterviewerCreator"))
        self.glInterview.addWidget(self.lblInterviewerCreator, 4, 2, 1, 1)
        self.leInterviewer = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewer.sizePolicy().hasHeightForWidth())
        self.leInterviewer.setSizePolicy(sizePolicy)
        self.leInterviewer.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewer.setObjectName(_fromUtf8("leInterviewer"))
        self.glInterview.addWidget(self.leInterviewer, 4, 3, 1, 1)
        self.dteStart = QtGui.QDateTimeEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteStart.sizePolicy().hasHeightForWidth())
        self.dteStart.setSizePolicy(sizePolicy)
        self.dteStart.setMinimumSize(QtCore.QSize(50, 0))
        self.dteStart.setObjectName(_fromUtf8("dteStart"))
        self.glInterview.addWidget(self.dteStart, 2, 1, 1, 1)
        self.pteInterviewDescription = QtGui.QPlainTextEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteInterviewDescription.sizePolicy().hasHeightForWidth())
        self.pteInterviewDescription.setSizePolicy(sizePolicy)
        self.pteInterviewDescription.setMinimumSize(QtCore.QSize(50, 0))
        self.pteInterviewDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteInterviewDescription.setObjectName(_fromUtf8("pteInterviewDescription"))
        self.glInterview.addWidget(self.pteInterviewDescription, 1, 1, 1, 1)
        self.dteEnd = QtGui.QDateTimeEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteEnd.sizePolicy().hasHeightForWidth())
        self.dteEnd.setSizePolicy(sizePolicy)
        self.dteEnd.setMinimumSize(QtCore.QSize(50, 0))
        self.dteEnd.setObjectName(_fromUtf8("dteEnd"))
        self.glInterview.addWidget(self.dteEnd, 4, 1, 1, 1)
        self.lblTags = QtGui.QLabel(self.pgIntBasic)
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.glInterview.addWidget(self.lblTags, 5, 0, 1, 1)
        self.leInterviewTags = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewTags.sizePolicy().hasHeightForWidth())
        self.leInterviewTags.setSizePolicy(sizePolicy)
        self.leInterviewTags.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewTags.setObjectName(_fromUtf8("leInterviewTags"))
        self.glInterview.addWidget(self.leInterviewTags, 5, 1, 1, 1)
        self.cbInterviewSecurity = QtGui.QComboBox(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInterviewSecurity.sizePolicy().hasHeightForWidth())
        self.cbInterviewSecurity.setSizePolicy(sizePolicy)
        self.cbInterviewSecurity.setMinimumSize(QtCore.QSize(50, 0))
        self.cbInterviewSecurity.setObjectName(_fromUtf8("cbInterviewSecurity"))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.glInterview.addWidget(self.cbInterviewSecurity, 2, 3, 1, 1)
        self.lblStatus = QtGui.QLabel(self.pgIntBasic)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.glInterview.addWidget(self.lblStatus, 5, 2, 1, 1)
        self.cbInterviewStatus = QtGui.QComboBox(self.pgIntBasic)
        self.cbInterviewStatus.setObjectName(_fromUtf8("cbInterviewStatus"))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.glInterview.addWidget(self.cbInterviewStatus, 5, 3, 1, 1)
        self.gridLayout_19.addLayout(self.glInterview, 0, 0, 1, 1)
        self.tbxInterview.addItem(self.pgIntBasic, _fromUtf8(""))
        self.pgIntParticipants = QtGui.QWidget()
        self.pgIntParticipants.setGeometry(QtCore.QRect(0, 0, 756, 245))
        self.pgIntParticipants.setObjectName(_fromUtf8("pgIntParticipants"))
        self.gridLayout0 = QtGui.QGridLayout(self.pgIntParticipants)
        self.gridLayout0.setMargin(0)
        self.gridLayout0.setObjectName(_fromUtf8("gridLayout0"))
        self.glIntCont = QtGui.QGridLayout()
        self.glIntCont.setObjectName(_fromUtf8("glIntCont"))
        self.leIntPartFamily = QtGui.QLineEdit(self.pgIntParticipants)
        self.leIntPartFamily.setObjectName(_fromUtf8("leIntPartFamily"))
        self.glIntCont.addWidget(self.leIntPartFamily, 2, 2, 1, 1)
        self.lblIntPartCommunity = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartCommunity.setObjectName(_fromUtf8("lblIntPartCommunity"))
        self.glIntCont.addWidget(self.lblIntPartCommunity, 1, 0, 1, 1)
        self.leIntPartCommunity = QtGui.QLineEdit(self.pgIntParticipants)
        self.leIntPartCommunity.setObjectName(_fromUtf8("leIntPartCommunity"))
        self.glIntCont.addWidget(self.leIntPartCommunity, 1, 2, 1, 1)
        self.lblIntPartFamily = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartFamily.setObjectName(_fromUtf8("lblIntPartFamily"))
        self.glIntCont.addWidget(self.lblIntPartFamily, 2, 0, 1, 1)
        self.lblIntPartName = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartName.setObjectName(_fromUtf8("lblIntPartName"))
        self.glIntCont.addWidget(self.lblIntPartName, 0, 0, 1, 1)
        self.cbIntPartName = QtGui.QComboBox(self.pgIntParticipants)
        self.cbIntPartName.setObjectName(_fromUtf8("cbIntPartName"))
        self.glIntCont.addWidget(self.cbIntPartName, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.glIntCont.addItem(spacerItem1, 3, 2, 1, 1)
        self.gridLayout0.addLayout(self.glIntCont, 0, 1, 1, 1)
        self.vlInterviewParticipants = QtGui.QVBoxLayout()
        self.vlInterviewParticipants.setObjectName(_fromUtf8("vlInterviewParticipants"))
        self.lblInterviewParticipants = QtGui.QLabel(self.pgIntParticipants)
        self.lblInterviewParticipants.setObjectName(_fromUtf8("lblInterviewParticipants"))
        self.vlInterviewParticipants.addWidget(self.lblInterviewParticipants)
        self.tblInterviewParticipants = QtGui.QTableWidget(self.pgIntParticipants)
        self.tblInterviewParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviewParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviewParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviewParticipants.setObjectName(_fromUtf8("tblInterviewParticipants"))
        self.tblInterviewParticipants.setColumnCount(0)
        self.tblInterviewParticipants.setRowCount(0)
        self.vlInterviewParticipants.addWidget(self.tblInterviewParticipants)
        self.hlInterviewParticipants = QtGui.QHBoxLayout()
        self.hlInterviewParticipants.setObjectName(_fromUtf8("hlInterviewParticipants"))
        self.pbIntPartNew = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartNew.setObjectName(_fromUtf8("pbIntPartNew"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartNew)
        self.pbIntPartSave = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartSave.setEnabled(False)
        self.pbIntPartSave.setObjectName(_fromUtf8("pbIntPartSave"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartSave)
        self.pbIntPartCancel = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartCancel.setEnabled(False)
        self.pbIntPartCancel.setObjectName(_fromUtf8("pbIntPartCancel"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartCancel)
        self.pbIntPartDelete = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartDelete.setEnabled(False)
        self.pbIntPartDelete.setObjectName(_fromUtf8("pbIntPartDelete"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartDelete)
        self.vlInterviewParticipants.addLayout(self.hlInterviewParticipants)
        self.gridLayout0.addLayout(self.vlInterviewParticipants, 0, 0, 1, 1)
        self.tbxInterview.addItem(self.pgIntParticipants, _fromUtf8(""))
        self.gridLayout1.addWidget(self.tbxInterview, 3, 0, 1, 1)
        self.frInterviewControls = QtGui.QFrame(self.tbInterviews)
        self.frInterviewControls.setObjectName(_fromUtf8("frInterviewControls"))
        self.hlInterviewList = QtGui.QHBoxLayout(self.frInterviewControls)
        self.hlInterviewList.setObjectName(_fromUtf8("hlInterviewList"))
        self.pbIntNew = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntNew.setObjectName(_fromUtf8("pbIntNew"))
        self.hlInterviewList.addWidget(self.pbIntNew)
        self.pbIntSave = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntSave.setEnabled(False)
        self.pbIntSave.setObjectName(_fromUtf8("pbIntSave"))
        self.hlInterviewList.addWidget(self.pbIntSave)
        self.pbIntCancel = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntCancel.setEnabled(False)
        self.pbIntCancel.setObjectName(_fromUtf8("pbIntCancel"))
        self.hlInterviewList.addWidget(self.pbIntCancel)
        self.pbIntDelete = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntDelete.setEnabled(False)
        self.pbIntDelete.setObjectName(_fromUtf8("pbIntDelete"))
        self.hlInterviewList.addWidget(self.pbIntDelete)
        self.gridLayout1.addWidget(self.frInterviewControls, 2, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbInterviews, _fromUtf8(""))
        self.tbAbout = QtGui.QWidget()
        self.tbAbout.setObjectName(_fromUtf8("tbAbout"))
        self.gridLayout = QtGui.QGridLayout(self.tbAbout)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.teAbout = QtGui.QTextEdit(self.tbAbout)
        self.teAbout.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teAbout.sizePolicy().hasHeightForWidth())
        self.teAbout.setSizePolicy(sizePolicy)
        self.teAbout.setAcceptDrops(False)
        self.teAbout.setUndoRedoEnabled(False)
        self.teAbout.setReadOnly(True)
        self.teAbout.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.teAbout.setObjectName(_fromUtf8("teAbout"))
        self.gridLayout.addWidget(self.teAbout, 0, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbAbout, _fromUtf8(""))
        self.gridLayout2.addWidget(self.twMapBioSettings, 0, 0, 1, 1)
        self.pbDialogClose = QtGui.QPushButton(mapbioManager)
        self.pbDialogClose.setObjectName(_fromUtf8("pbDialogClose"))
        self.gridLayout2.addWidget(self.pbDialogClose, 1, 0, 1, 1)

        self.retranslateUi(mapbioManager)
        self.twMapBioSettings.setCurrentIndex(0)
        self.tbxParticipants.setCurrentIndex(0)
        self.tbxInterview.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioManager)
        mapbioManager.setTabOrder(self.twMapBioSettings, self.leProjectDir)
        mapbioManager.setTabOrder(self.leProjectDir, self.tbSelectProjectDir)
        mapbioManager.setTabOrder(self.tbSelectProjectDir, self.cbProjectDatabase)
        mapbioManager.setTabOrder(self.cbProjectDatabase, self.cbMaxScale)
        mapbioManager.setTabOrder(self.cbMaxScale, self.cbMinScale)
        mapbioManager.setTabOrder(self.cbMinScale, self.cbZoomRangeNotices)
        mapbioManager.setTabOrder(self.cbZoomRangeNotices, self.leQgsProject)
        mapbioManager.setTabOrder(self.leQgsProject, self.tbSelectQgsProject)
        mapbioManager.setTabOrder(self.tbSelectQgsProject, self.tblBaseGroups)
        mapbioManager.setTabOrder(self.tblBaseGroups, self.cbProjectGroups)
        mapbioManager.setTabOrder(self.cbProjectGroups, self.pbAddBaseGroup)
        mapbioManager.setTabOrder(self.pbAddBaseGroup, self.pbRemoveBaseGroup)
        mapbioManager.setTabOrder(self.pbRemoveBaseGroup, self.cbBoundaryLayer)
        mapbioManager.setTabOrder(self.cbBoundaryLayer, self.cbEnableReference)
        mapbioManager.setTabOrder(self.cbEnableReference, self.cbReferenceLayer)
        mapbioManager.setTabOrder(self.cbReferenceLayer, self.pbSaveSettings)
        mapbioManager.setTabOrder(self.pbSaveSettings, self.pbCancelSettings)
        mapbioManager.setTabOrder(self.pbCancelSettings, self.pbTransfer)
        mapbioManager.setTabOrder(self.pbTransfer, self.leProjectCode)
        mapbioManager.setTabOrder(self.leProjectCode, self.leProjectTags)
        mapbioManager.setTabOrder(self.leProjectTags, self.pteProjectDescription)
        mapbioManager.setTabOrder(self.pteProjectDescription, self.pteTimeOfYear)
        mapbioManager.setTabOrder(self.pteTimeOfYear, self.pteDateAndTime)
        mapbioManager.setTabOrder(self.pteDateAndTime, self.pteContentCodes)
        mapbioManager.setTabOrder(self.pteContentCodes, self.pteProjectNote)
        mapbioManager.setTabOrder(self.pteProjectNote, self.pbProjectSave)
        mapbioManager.setTabOrder(self.pbProjectSave, self.pbProjectCancel)
        mapbioManager.setTabOrder(self.pbProjectCancel, self.tblParticipants)
        mapbioManager.setTabOrder(self.tblParticipants, self.pbParticipantNew)
        mapbioManager.setTabOrder(self.pbParticipantNew, self.pbParticipantSave)
        mapbioManager.setTabOrder(self.pbParticipantSave, self.pbParticipantCancel)
        mapbioManager.setTabOrder(self.pbParticipantCancel, self.pbParticipantDelete)
        mapbioManager.setTabOrder(self.pbParticipantDelete, self.leParticipantCode)
        mapbioManager.setTabOrder(self.leParticipantCode, self.leFirstName)
        mapbioManager.setTabOrder(self.leFirstName, self.leLastName)
        mapbioManager.setTabOrder(self.leLastName, self.leEmail)
        mapbioManager.setTabOrder(self.leEmail, self.leCommunity)
        mapbioManager.setTabOrder(self.leCommunity, self.leFamily)
        mapbioManager.setTabOrder(self.leFamily, self.leMaidenName)
        mapbioManager.setTabOrder(self.leMaidenName, self.cbGender)
        mapbioManager.setTabOrder(self.cbGender, self.cbMaritalStatus)
        mapbioManager.setTabOrder(self.cbMaritalStatus, self.leBirthDate)
        mapbioManager.setTabOrder(self.leBirthDate, self.leParticipantTags)
        mapbioManager.setTabOrder(self.leParticipantTags, self.pteParticipantNote)
        mapbioManager.setTabOrder(self.pteParticipantNote, self.tblAddresses)
        mapbioManager.setTabOrder(self.tblAddresses, self.pbAddNew)
        mapbioManager.setTabOrder(self.pbAddNew, self.pbAddSave)
        mapbioManager.setTabOrder(self.pbAddSave, self.pbAddCancel)
        mapbioManager.setTabOrder(self.pbAddCancel, self.pbAddDelete)
        mapbioManager.setTabOrder(self.pbAddDelete, self.cbAddType)
        mapbioManager.setTabOrder(self.cbAddType, self.leLineOne)
        mapbioManager.setTabOrder(self.leLineOne, self.leLineTwo)
        mapbioManager.setTabOrder(self.leLineTwo, self.leCity)
        mapbioManager.setTabOrder(self.leCity, self.leProvince)
        mapbioManager.setTabOrder(self.leProvince, self.leCountry)
        mapbioManager.setTabOrder(self.leCountry, self.lePostalCode)
        mapbioManager.setTabOrder(self.lePostalCode, self.tblTelecoms)
        mapbioManager.setTabOrder(self.tblTelecoms, self.pbTelNew)
        mapbioManager.setTabOrder(self.pbTelNew, self.pbTelSave)
        mapbioManager.setTabOrder(self.pbTelSave, self.pbTelCancel)
        mapbioManager.setTabOrder(self.pbTelCancel, self.pbTelDelete)
        mapbioManager.setTabOrder(self.pbTelDelete, self.cbTelType)
        mapbioManager.setTabOrder(self.cbTelType, self.leTelNumber)
        mapbioManager.setTabOrder(self.leTelNumber, self.tblInterviews)
        mapbioManager.setTabOrder(self.tblInterviews, self.pbIntNew)
        mapbioManager.setTabOrder(self.pbIntNew, self.pbIntSave)
        mapbioManager.setTabOrder(self.pbIntSave, self.pbIntCancel)
        mapbioManager.setTabOrder(self.pbIntCancel, self.pbIntDelete)
        mapbioManager.setTabOrder(self.pbIntDelete, self.leInterviewCode)
        mapbioManager.setTabOrder(self.leInterviewCode, self.pteInterviewDescription)
        mapbioManager.setTabOrder(self.pteInterviewDescription, self.dteStart)
        mapbioManager.setTabOrder(self.dteStart, self.dteEnd)
        mapbioManager.setTabOrder(self.dteEnd, self.leInterviewTags)
        mapbioManager.setTabOrder(self.leInterviewTags, self.leInterviewLocation)
        mapbioManager.setTabOrder(self.leInterviewLocation, self.pteInterviewNote)
        mapbioManager.setTabOrder(self.pteInterviewNote, self.cbInterviewSecurity)
        mapbioManager.setTabOrder(self.cbInterviewSecurity, self.leInterviewer)
        mapbioManager.setTabOrder(self.leInterviewer, self.cbInterviewStatus)
        mapbioManager.setTabOrder(self.cbInterviewStatus, self.tblInterviewParticipants)
        mapbioManager.setTabOrder(self.tblInterviewParticipants, self.pbIntPartNew)
        mapbioManager.setTabOrder(self.pbIntPartNew, self.pbIntPartSave)
        mapbioManager.setTabOrder(self.pbIntPartSave, self.pbIntPartCancel)
        mapbioManager.setTabOrder(self.pbIntPartCancel, self.pbIntPartDelete)
        mapbioManager.setTabOrder(self.pbIntPartDelete, self.cbIntPartName)
        mapbioManager.setTabOrder(self.cbIntPartName, self.leIntPartCommunity)
        mapbioManager.setTabOrder(self.leIntPartCommunity, self.leIntPartFamily)
        mapbioManager.setTabOrder(self.leIntPartFamily, self.teAbout)
        mapbioManager.setTabOrder(self.teAbout, self.pbDialogClose)
        mapbioManager.setTabOrder(self.pbDialogClose, self.cbDefaultCode)
        mapbioManager.setTabOrder(self.cbDefaultCode, self.cbPointCode)
        mapbioManager.setTabOrder(self.cbPointCode, self.cbLineCode)
        mapbioManager.setTabOrder(self.cbLineCode, self.cbPolygonCode)

    def retranslateUi(self, mapbioManager):
        mapbioManager.setWindowTitle(_translate("mapbioManager", "Dialog", None))
        self.lblMaxScale.setText(_translate("mapbioManager", "Maximum Map Scale", None))
        self.cbMinScale.setItemText(0, _translate("mapbioManager", "1:10,000", None))
        self.cbMinScale.setItemText(1, _translate("mapbioManager", "1:15,000", None))
        self.cbMinScale.setItemText(2, _translate("mapbioManager", "1:25,000", None))
        self.cbMinScale.setItemText(3, _translate("mapbioManager", "1:50,000", None))
        self.cbMinScale.setItemText(4, _translate("mapbioManager", "1:100,000", None))
        self.cbMinScale.setItemText(5, _translate("mapbioManager", "1:250,000", None))
        self.cbMinScale.setItemText(6, _translate("mapbioManager", "1:500,000", None))
        self.cbMinScale.setItemText(7, _translate("mapbioManager", "1:750,000", None))
        self.cbMinScale.setItemText(8, _translate("mapbioManager", "1:1,000,000", None))
        self.cbMinScale.setItemText(9, _translate("mapbioManager", "1:2,500,000", None))
        self.cbMaxScale.setItemText(0, _translate("mapbioManager", "1:5,000", None))
        self.cbMaxScale.setItemText(1, _translate("mapbioManager", "1:10,000", None))
        self.cbMaxScale.setItemText(2, _translate("mapbioManager", "1:15,000", None))
        self.cbMaxScale.setItemText(3, _translate("mapbioManager", "1:25,000", None))
        self.cbMaxScale.setItemText(4, _translate("mapbioManager", "1:50,000", None))
        self.cbMaxScale.setItemText(5, _translate("mapbioManager", "1:100,000", None))
        self.cbMaxScale.setItemText(6, _translate("mapbioManager", "1:250,000", None))
        self.cbMaxScale.setItemText(7, _translate("mapbioManager", "1:500,000", None))
        self.cbMaxScale.setItemText(8, _translate("mapbioManager", "1:750,000", None))
        self.cbMaxScale.setItemText(9, _translate("mapbioManager", "1:1,000,000", None))
        self.cbZoomRangeNotices.setItemText(0, _translate("mapbioManager", "No", None))
        self.cbZoomRangeNotices.setItemText(1, _translate("mapbioManager", "Yes", None))
        self.lblZoomNotices.setText(_translate("mapbioManager", "Show Zoom Range Notices", None))
        self.lblProjectsDir.setText(_translate("mapbioManager", "Projects Directory", None))
        self.lblProjectDatabase.setText(_translate("mapbioManager", "Project Database", None))
        self.tbSelectProjectDir.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Click here to set the LOUIS Map Biographer default projects directory.</p></body></html>", None))
        self.tbSelectProjectDir.setText(_translate("mapbioManager", "...", None))
        self.lblMinScale.setText(_translate("mapbioManager", "Minimum Map Scale", None))
        self.lblQgsProject.setText(_translate("mapbioManager", "QGIS Project", None))
        self.tbSelectQgsProject.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Click here to select the QGIS project to use with LOUIS Map Biographer</p></body></html>", None))
        self.tbSelectQgsProject.setText(_translate("mapbioManager", "...", None))
        self.lblBaseGroupOptions.setText(_translate("mapbioManager", "Use project groups as base layers ", None))
        self.pbAddBaseGroup.setText(_translate("mapbioManager", "Add", None))
        self.pbRemoveBaseGroup.setText(_translate("mapbioManager", "Remove", None))
        self.lblBaseLayerGroups.setText(_translate("mapbioManager", "Base Layer Groups           ", None))
        self.lblProjectBoundary.setText(_translate("mapbioManager", "Project Boundary Layer ", None))
        self.lblEnableReference.setText(_translate("mapbioManager", "Enable Reference Layer", None))
        self.cbEnableReference.setItemText(0, _translate("mapbioManager", "No", None))
        self.cbEnableReference.setItemText(1, _translate("mapbioManager", "Yes", None))
        self.lblReferenceLayer.setText(_translate("mapbioManager", "Project Reference Layer", None))
        self.pbSaveSettings.setText(_translate("mapbioManager", "Save Settings", None))
        self.pbCancelSettings.setText(_translate("mapbioManager", "Cancel", None))
        self.pbTransfer.setText(_translate("mapbioManager", "Transfer Data", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbSettings), _translate("mapbioManager", "Map Biographer Settings", None))
        self.lblProjCode.setText(_translate("mapbioManager", "Project Code", None))
        self.leProjectCode.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a code for this project.</p></body></html>", None))
        self.lblProjTags.setText(_translate("mapbioManager", "Tags", None))
        self.leProjectTags.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a list of tags or phrases separated by commas here such as:</p><p>Review Needed,Confirmation Meeting Needed,Confirm Contact Details</p></body></html>", None))
        self.lblProjDescription.setText(_translate("mapbioManager", "Description", None))
        self.pteProjectDescription.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a brief description of the project here.</p></body></html>", None))
        self.lblTimeOfYear.setText(_translate("mapbioManager", "Times of Year", None))
        self.pteTimeOfYear.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter time of year options (one per line) using as a list of months and a name as per the following example:</p><p>12,1,2 = Winter<br/>3,4,5 = Spring<br/>6,7,8 = Summer<br/>9,10,11 = Autumn</p></body></html>", None))
        self.lblDateAndTime.setText(_translate("mapbioManager", "Dates And Times", None))
        self.pteDateAndTime.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter custom date and time ranges using the following format:</p><p>1900-01-01 : 1967-12-31 = Before Bennett Dam<br/>1968-01-01 : 2014-08-31 = After Bennett Dam until today</p></body></html>", None))
        self.lblContentCodes.setText(_translate("mapbioManager", "Content Codes", None))
        self.pteContentCodes.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a list of codes (one per line) in the following format:</p><p>BP = Berry Picking<br/>CB = Cabin</p><p><br/></p></body></html>", None))
        self.lblDefaultPointCode.setText(_translate("mapbioManager", "Default Point Code", None))
        self.lblDefaultCode.setText(_translate("mapbioManager", "Default Content Code", None))
        self.lblDefaultPolygonCode.setText(_translate("mapbioManager", "Default Polygon Code", None))
        self.lblDefaultLineCode.setText(_translate("mapbioManager", "Default Line Code", None))
        self.lblProjNote.setText(_translate("mapbioManager", "Notes", None))
        self.pteProjectNote.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter project notes here.</p></body></html>", None))
        self.pbProjectSave.setText(_translate("mapbioManager", "Save", None))
        self.pbProjectCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbProjectDetails), _translate("mapbioManager", "Project Details", None))
        self.lblParticipants.setText(_translate("mapbioManager", "Participants", None))
        self.lblFamilyGroup.setText(_translate("mapbioManager", "Family Group", None))
        self.lblEmail.setText(_translate("mapbioManager", "Email Address", None))
        self.lblCommunityName.setText(_translate("mapbioManager", "Community", None))
        self.lblParticipantCode.setText(_translate("mapbioManager", "Participant Code", None))
        self.lblFirstName.setText(_translate("mapbioManager", "First Name", None))
        self.lblLastName.setText(_translate("mapbioManager", "Last Name", None))
        self.lblParticipantTags.setText(_translate("mapbioManager", "Tags", None))
        self.lblBirthDate.setText(_translate("mapbioManager", "Birth Date", None))
        self.lblMaritalStatus.setText(_translate("mapbioManager", "Marital Status", None))
        self.cbMaritalStatus.setItemText(0, _translate("mapbioManager", "Unknown", None))
        self.cbMaritalStatus.setItemText(1, _translate("mapbioManager", "Single", None))
        self.cbMaritalStatus.setItemText(2, _translate("mapbioManager", "Married", None))
        self.cbMaritalStatus.setItemText(3, _translate("mapbioManager", "Divorced", None))
        self.cbMaritalStatus.setItemText(4, _translate("mapbioManager", "Refused", None))
        self.cbMaritalStatus.setItemText(5, _translate("mapbioManager", "Other", None))
        self.lblGender.setText(_translate("mapbioManager", "Gender", None))
        self.cbGender.setItemText(0, _translate("mapbioManager", "Unknown", None))
        self.cbGender.setItemText(1, _translate("mapbioManager", "Male", None))
        self.cbGender.setItemText(2, _translate("mapbioManager", "Female", None))
        self.cbGender.setItemText(3, _translate("mapbioManager", "Refused", None))
        self.cbGender.setItemText(4, _translate("mapbioManager", "Other", None))
        self.lblMaidenName.setText(_translate("mapbioManager", "Maiden Name", None))
        self.lblParticipantNotes.setText(_translate("mapbioManager", "Notes", None))
        self.leBirthDate.setInputMask(_translate("mapbioManager", "9999-99-99; ", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgBasicInfo), _translate("mapbioManager", "Basic Information", None))
        self.lblAddresses.setText(_translate("mapbioManager", "Address List", None))
        self.pbAddNew.setText(_translate("mapbioManager", "New", None))
        self.pbAddSave.setText(_translate("mapbioManager", "Save", None))
        self.pbAddCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbAddDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblCountry.setText(_translate("mapbioManager", "Country", None))
        self.lblAddType.setText(_translate("mapbioManager", "Type", None))
        self.lblLineTwo.setText(_translate("mapbioManager", "Line Two", None))
        self.lblProvince.setText(_translate("mapbioManager", "Province", None))
        self.cbAddType.setItemText(0, _translate("mapbioManager", "Home", None))
        self.cbAddType.setItemText(1, _translate("mapbioManager", "Work", None))
        self.cbAddType.setItemText(2, _translate("mapbioManager", "PO Box", None))
        self.cbAddType.setItemText(3, _translate("mapbioManager", "Other", None))
        self.lblCity.setText(_translate("mapbioManager", "City", None))
        self.lblPostalCode.setText(_translate("mapbioManager", "Postal Code", None))
        self.lblLineOne.setText(_translate("mapbioManager", "Line One", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgAddresses), _translate("mapbioManager", "Addresses", None))
        self.lblTelecoms.setText(_translate("mapbioManager", "Telecoms List", None))
        self.pbTelNew.setText(_translate("mapbioManager", "New", None))
        self.pbTelSave.setText(_translate("mapbioManager", "Save", None))
        self.pbTelCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbTelDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblTelType.setText(_translate("mapbioManager", "Type", None))
        self.cbTelType.setItemText(0, _translate("mapbioManager", "Home", None))
        self.cbTelType.setItemText(1, _translate("mapbioManager", "Work", None))
        self.cbTelType.setItemText(2, _translate("mapbioManager", "Mobile", None))
        self.cbTelType.setItemText(3, _translate("mapbioManager", "Pager", None))
        self.cbTelType.setItemText(4, _translate("mapbioManager", "Fax", None))
        self.cbTelType.setItemText(5, _translate("mapbioManager", "Other", None))
        self.lblTelecom.setText(_translate("mapbioManager", "Number", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgTelecoms), _translate("mapbioManager", "Phones / Faxes", None))
        self.pbParticipantNew.setText(_translate("mapbioManager", "New", None))
        self.pbParticipantSave.setText(_translate("mapbioManager", "Save", None))
        self.pbParticipantCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbParticipantDelete.setText(_translate("mapbioManager", "Delete", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbPeople), _translate("mapbioManager", "Participants", None))
        self.lblInterviews.setText(_translate("mapbioManager", "Interview List", None))
        self.lblCode.setText(_translate("mapbioManager", "Interview Code", None))
        self.lblDescription.setText(_translate("mapbioManager", "Description", None))
        self.lblStartDateTime.setText(_translate("mapbioManager", "Start Date / Time", None))
        self.lblNotes.setText(_translate("mapbioManager", "Notes", None))
        self.lblEndDateTime.setText(_translate("mapbioManager", "End Date / Time", None))
        self.lblLocation.setText(_translate("mapbioManager", "Interview Location", None))
        self.lblSecurity.setText(_translate("mapbioManager", "Default Security", None))
        self.lblInterviewerCreator.setText(_translate("mapbioManager", "Interviewer Name", None))
        self.dteStart.setDisplayFormat(_translate("mapbioManager", "yyyy-MM-dd HH:mm", None))
        self.dteEnd.setDisplayFormat(_translate("mapbioManager", "yyyy-MM-dd HH:mm", None))
        self.lblTags.setText(_translate("mapbioManager", "Tags", None))
        self.cbInterviewSecurity.setItemText(0, _translate("mapbioManager", "Public", None))
        self.cbInterviewSecurity.setItemText(1, _translate("mapbioManager", "Community", None))
        self.cbInterviewSecurity.setItemText(2, _translate("mapbioManager", "Private", None))
        self.lblStatus.setText(_translate("mapbioManager", "Interview Status", None))
        self.cbInterviewStatus.setItemText(0, _translate("mapbioManager", "New", None))
        self.cbInterviewStatus.setItemText(1, _translate("mapbioManager", "Completed", None))
        self.cbInterviewStatus.setItemText(2, _translate("mapbioManager", "Transcribed", None))
        self.cbInterviewStatus.setItemText(3, _translate("mapbioManager", "Uploaded", None))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntBasic), _translate("mapbioManager", "Interview Information", None))
        self.lblIntPartCommunity.setText(_translate("mapbioManager", "Community", None))
        self.lblIntPartFamily.setText(_translate("mapbioManager", "Family Group", None))
        self.lblIntPartName.setText(_translate("mapbioManager", "Name", None))
        self.lblInterviewParticipants.setText(_translate("mapbioManager", "Participants", None))
        self.pbIntPartNew.setText(_translate("mapbioManager", "New", None))
        self.pbIntPartSave.setText(_translate("mapbioManager", "Save", None))
        self.pbIntPartCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbIntPartDelete.setText(_translate("mapbioManager", "Delete", None))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntParticipants), _translate("mapbioManager", "Interview Participants", None))
        self.pbIntNew.setText(_translate("mapbioManager", "New", None))
        self.pbIntSave.setText(_translate("mapbioManager", "Save", None))
        self.pbIntCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbIntDelete.setText(_translate("mapbioManager", "Delete", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbInterviews), _translate("mapbioManager", "Interviews", None))
        self.teAbout.setHtml(_translate("mapbioManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LOUIS Map Biographer Version 0.9.6 - Second Beta Testing Version</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PLEASE NOTE: This version of LOUIS Map Biographer is an early release as part of our Beta Testing Program that will operate from 2015-04-01 to 2015-05-15. This version of LOUIS Map Biographer has been released to get user feedback on reliability and ease-of-use; caution is recommended for use with live studies. For more information about the testing program or to submit comments about this version please visit <a href=\"http://aproposinfosystems.com/products/mapbiographer\"><span style=\" text-decoration: underline; color:#0000ff;\">aproposinfosystems.com/products/mapbiographer</span></a> or our contact page at <a href=\"http://aproposinfosystems.com/contact\"><span style=\" text-decoration: underline; color:#0000ff;\">aproposinfosystems.com/contact</span></a>.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ABOUT LOUIS Map Biographer</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LOUIS Map Biographer is a free / open source solution for direct to digital capture of land use information through in-person interviews. LOUIS Map Biographer is designed to support the best practice ideas for Use and Occupancy mapping studies outlined in <span style=\" font-style:italic;\">Living Proof</span><span style=\" vertical-align:super;\">1</span>. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LOUIS Map Biographer is part of the Land Occupancy and Use Information Systems (LOUIS) tool kit. LOUIS Map Biographer can be used on its own or together with other parts of the LOUIS tool kit. For more information about LOUIS tool kit visit: <a href=\"http://louistk.ca\"><span style=\" text-decoration: underline; color:#0000ff;\">louistk.ca</span></a></p>\n"
"<hr />\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 - Tobias, Terry N., 2009. <a href=\"http://ecotrust.ca/first-nations/new-book-use-and-occupancy-map-surveys-now-available\"><span style=\" text-decoration: underline; color:#0000ff;\">Living Proof: The essential data-collection guide for Indigenous Use-and-Occupancy map surveys</span></a>.  Ecostrust Canada and Union of BC Indian Chiefs, British Columbia, Canada.</p></body></html>", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbAbout), _translate("mapbioManager", "About", None))
        self.pbDialogClose.setText(_translate("mapbioManager", "Close", None))

