# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_settings.ui'
#
# Created: Mon Sep 22 15:49:05 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapBiographerSettings(object):
    def setupUi(self, mapBiographerSettings):
        mapBiographerSettings.setObjectName(_fromUtf8("mapBiographerSettings"))
        mapBiographerSettings.resize(800, 740)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapBiographerSettings.sizePolicy().hasHeightForWidth())
        mapBiographerSettings.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapBiographerSettings.setWindowIcon(icon)
        self.wbMapBiographer = QtGui.QTabWidget(mapBiographerSettings)
        self.wbMapBiographer.setEnabled(True)
        self.wbMapBiographer.setGeometry(QtCore.QRect(10, 0, 780, 681))
        self.wbMapBiographer.setObjectName(_fromUtf8("wbMapBiographer"))
        self.twSettings = QtGui.QWidget()
        self.twSettings.setObjectName(_fromUtf8("twSettings"))
        self.gridLayoutWidget = QtGui.QWidget(self.twSettings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(8, 20, 761, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.glAccountSettings = QtGui.QGridLayout(self.gridLayoutWidget)
        self.glAccountSettings.setMargin(0)
        self.glAccountSettings.setObjectName(_fromUtf8("glAccountSettings"))
        self.lblProjectsDir = QtGui.QLabel(self.gridLayoutWidget)
        self.lblProjectsDir.setObjectName(_fromUtf8("lblProjectsDir"))
        self.glAccountSettings.addWidget(self.lblProjectsDir, 0, 0, 1, 1)
        self.hlProjectDir = QtGui.QHBoxLayout()
        self.hlProjectDir.setObjectName(_fromUtf8("hlProjectDir"))
        self.leProjectDir = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leProjectDir.setEnabled(True)
        self.leProjectDir.setReadOnly(True)
        self.leProjectDir.setObjectName(_fromUtf8("leProjectDir"))
        self.hlProjectDir.addWidget(self.leProjectDir)
        self.tbSelectProjectDir = QtGui.QToolButton(self.gridLayoutWidget)
        self.tbSelectProjectDir.setObjectName(_fromUtf8("tbSelectProjectDir"))
        self.hlProjectDir.addWidget(self.tbSelectProjectDir)
        self.glAccountSettings.addLayout(self.hlProjectDir, 0, 2, 1, 1)
        self.lblProjectDatabase = QtGui.QLabel(self.gridLayoutWidget)
        self.lblProjectDatabase.setObjectName(_fromUtf8("lblProjectDatabase"))
        self.glAccountSettings.addWidget(self.lblProjectDatabase, 1, 0, 1, 1)
        self.hlProjectDB = QtGui.QHBoxLayout()
        self.hlProjectDB.setObjectName(_fromUtf8("hlProjectDB"))
        self.cbProjectDatabase = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbProjectDatabase.setObjectName(_fromUtf8("cbProjectDatabase"))
        self.hlProjectDB.addWidget(self.cbProjectDatabase)
        self.glAccountSettings.addLayout(self.hlProjectDB, 1, 2, 1, 1)
        self.hlnSettings1 = QtGui.QFrame(self.twSettings)
        self.hlnSettings1.setGeometry(QtCore.QRect(10, 100, 761, 20))
        self.hlnSettings1.setFrameShape(QtGui.QFrame.HLine)
        self.hlnSettings1.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnSettings1.setObjectName(_fromUtf8("hlnSettings1"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.twSettings)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(90, 604, 597, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.hlSettings = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hlSettings.setMargin(0)
        self.hlSettings.setObjectName(_fromUtf8("hlSettings"))
        self.pbSaveSettings = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pbSaveSettings.setObjectName(_fromUtf8("pbSaveSettings"))
        self.hlSettings.addWidget(self.pbSaveSettings)
        self.pbCancelSettings = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pbCancelSettings.setObjectName(_fromUtf8("pbCancelSettings"))
        self.hlSettings.addWidget(self.pbCancelSettings)
        self.pbExport = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pbExport.setObjectName(_fromUtf8("pbExport"))
        self.hlSettings.addWidget(self.pbExport)
        self.hlnSettings2 = QtGui.QFrame(self.twSettings)
        self.hlnSettings2.setGeometry(QtCore.QRect(10, 410, 761, 16))
        self.hlnSettings2.setFrameShape(QtGui.QFrame.HLine)
        self.hlnSettings2.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnSettings2.setObjectName(_fromUtf8("hlnSettings2"))
        self.formLayoutWidget = QtGui.QWidget(self.twSettings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 120, 761, 289))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblQgsProject = QtGui.QLabel(self.formLayoutWidget)
        self.lblQgsProject.setObjectName(_fromUtf8("lblQgsProject"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblQgsProject)
        self.hlQgsProject = QtGui.QHBoxLayout()
        self.hlQgsProject.setObjectName(_fromUtf8("hlQgsProject"))
        self.leQgsProject = QtGui.QLineEdit(self.formLayoutWidget)
        self.leQgsProject.setEnabled(True)
        self.leQgsProject.setReadOnly(True)
        self.leQgsProject.setObjectName(_fromUtf8("leQgsProject"))
        self.hlQgsProject.addWidget(self.leQgsProject)
        self.tbSelectQgsProject = QtGui.QToolButton(self.formLayoutWidget)
        self.tbSelectQgsProject.setObjectName(_fromUtf8("tbSelectQgsProject"))
        self.hlQgsProject.addWidget(self.tbSelectQgsProject)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.hlQgsProject)
        self.hlBaseLayers = QtGui.QHBoxLayout()
        self.hlBaseLayers.setObjectName(_fromUtf8("hlBaseLayers"))
        self.tblBaseGroups = QtGui.QTableWidget(self.formLayoutWidget)
        self.tblBaseGroups.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblBaseGroups.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblBaseGroups.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblBaseGroups.setObjectName(_fromUtf8("tblBaseGroups"))
        self.tblBaseGroups.setColumnCount(0)
        self.tblBaseGroups.setRowCount(0)
        self.hlBaseLayers.addWidget(self.tblBaseGroups)
        self.vlBaseGroupActions = QtGui.QVBoxLayout()
        self.vlBaseGroupActions.setObjectName(_fromUtf8("vlBaseGroupActions"))
        self.lblBaseGroupOptions = QtGui.QLabel(self.formLayoutWidget)
        self.lblBaseGroupOptions.setMinimumSize(QtCore.QSize(200, 0))
        self.lblBaseGroupOptions.setObjectName(_fromUtf8("lblBaseGroupOptions"))
        self.vlBaseGroupActions.addWidget(self.lblBaseGroupOptions)
        self.cbProjectGroups = QtGui.QComboBox(self.formLayoutWidget)
        self.cbProjectGroups.setObjectName(_fromUtf8("cbProjectGroups"))
        self.vlBaseGroupActions.addWidget(self.cbProjectGroups)
        self.hlBaseGroups = QtGui.QHBoxLayout()
        self.hlBaseGroups.setObjectName(_fromUtf8("hlBaseGroups"))
        self.pbAddBaseGroup = QtGui.QPushButton(self.formLayoutWidget)
        self.pbAddBaseGroup.setObjectName(_fromUtf8("pbAddBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbAddBaseGroup)
        self.pbRemoveBaseGroup = QtGui.QPushButton(self.formLayoutWidget)
        self.pbRemoveBaseGroup.setEnabled(False)
        self.pbRemoveBaseGroup.setObjectName(_fromUtf8("pbRemoveBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbRemoveBaseGroup)
        self.vlBaseGroupActions.addLayout(self.hlBaseGroups)
        self.hlBaseLayers.addLayout(self.vlBaseGroupActions)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.hlBaseLayers)
        self.lblBaseLayerGroups = QtGui.QLabel(self.formLayoutWidget)
        self.lblBaseLayerGroups.setObjectName(_fromUtf8("lblBaseLayerGroups"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblBaseLayerGroups)
        self.cbBoundaryLayer = QtGui.QComboBox(self.formLayoutWidget)
        self.cbBoundaryLayer.setObjectName(_fromUtf8("cbBoundaryLayer"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbBoundaryLayer)
        self.lblProjectBoundary = QtGui.QLabel(self.formLayoutWidget)
        self.lblProjectBoundary.setObjectName(_fromUtf8("lblProjectBoundary"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblProjectBoundary)
        self.lblEnableReference = QtGui.QLabel(self.formLayoutWidget)
        self.lblEnableReference.setObjectName(_fromUtf8("lblEnableReference"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblEnableReference)
        self.cbEnableReference = QtGui.QComboBox(self.formLayoutWidget)
        self.cbEnableReference.setObjectName(_fromUtf8("cbEnableReference"))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbEnableReference)
        self.lblReferenceLayer = QtGui.QLabel(self.formLayoutWidget)
        self.lblReferenceLayer.setObjectName(_fromUtf8("lblReferenceLayer"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblReferenceLayer)
        self.cbReferenceLayer = QtGui.QComboBox(self.formLayoutWidget)
        self.cbReferenceLayer.setObjectName(_fromUtf8("cbReferenceLayer"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbReferenceLayer)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.twSettings)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 428, 761, 111))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.grHeritageSettings = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.grHeritageSettings.setMargin(0)
        self.grHeritageSettings.setObjectName(_fromUtf8("grHeritageSettings"))
        self.leHeritageUser = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.leHeritageUser.setEnabled(True)
        self.leHeritageUser.setObjectName(_fromUtf8("leHeritageUser"))
        self.grHeritageSettings.addWidget(self.leHeritageUser, 2, 1, 1, 1)
        self.leHeritageCommunity = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.leHeritageCommunity.setEnabled(True)
        self.leHeritageCommunity.setObjectName(_fromUtf8("leHeritageCommunity"))
        self.grHeritageSettings.addWidget(self.leHeritageCommunity, 1, 1, 1, 1)
        self.lblClientCommunity = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblClientCommunity.setObjectName(_fromUtf8("lblClientCommunity"))
        self.grHeritageSettings.addWidget(self.lblClientCommunity, 1, 0, 1, 1)
        self.lblUser = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblUser.setObjectName(_fromUtf8("lblUser"))
        self.grHeritageSettings.addWidget(self.lblUser, 2, 0, 1, 1)
        self.lblAccount = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblAccount.setObjectName(_fromUtf8("lblAccount"))
        self.grHeritageSettings.addWidget(self.lblAccount, 0, 0, 1, 1)
        self.hlAccountSettings = QtGui.QHBoxLayout()
        self.hlAccountSettings.setObjectName(_fromUtf8("hlAccountSettings"))
        self.rdoHasHeritage = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.rdoHasHeritage.setEnabled(False)
        self.rdoHasHeritage.setChecked(True)
        self.rdoHasHeritage.setObjectName(_fromUtf8("rdoHasHeritage"))
        self.hlAccountSettings.addWidget(self.rdoHasHeritage)
        self.rdoNoHeritage = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.rdoNoHeritage.setEnabled(False)
        self.rdoNoHeritage.setObjectName(_fromUtf8("rdoNoHeritage"))
        self.hlAccountSettings.addWidget(self.rdoNoHeritage)
        self.grHeritageSettings.addLayout(self.hlAccountSettings, 0, 1, 1, 1)
        self.hlnSettings2_2 = QtGui.QFrame(self.twSettings)
        self.hlnSettings2_2.setGeometry(QtCore.QRect(10, 586, 761, 16))
        self.hlnSettings2_2.setFrameShape(QtGui.QFrame.HLine)
        self.hlnSettings2_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnSettings2_2.setObjectName(_fromUtf8("hlnSettings2_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.twSettings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(182, 543, 416, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbPullData = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pbPullData.setEnabled(False)
        self.pbPullData.setObjectName(_fromUtf8("pbPullData"))
        self.horizontalLayout.addWidget(self.pbPullData)
        self.pbPushData = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pbPushData.setEnabled(False)
        self.pbPushData.setObjectName(_fromUtf8("pbPushData"))
        self.horizontalLayout.addWidget(self.pbPushData)
        self.wbMapBiographer.addTab(self.twSettings, _fromUtf8(""))
        self.twProject = QtGui.QWidget()
        self.twProject.setObjectName(_fromUtf8("twProject"))
        self.layoutWidget = QtGui.QWidget(self.twProject)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 10, 411, 561))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vlProjectDefaults = QtGui.QVBoxLayout(self.layoutWidget)
        self.vlProjectDefaults.setMargin(0)
        self.vlProjectDefaults.setObjectName(_fromUtf8("vlProjectDefaults"))
        self.lblContentCodes = QtGui.QLabel(self.layoutWidget)
        self.lblContentCodes.setObjectName(_fromUtf8("lblContentCodes"))
        self.vlProjectDefaults.addWidget(self.lblContentCodes)
        self.pteContentCodes = QtGui.QPlainTextEdit(self.layoutWidget)
        self.pteContentCodes.setObjectName(_fromUtf8("pteContentCodes"))
        self.vlProjectDefaults.addWidget(self.pteContentCodes)
        self.lblTimePeriods = QtGui.QLabel(self.layoutWidget)
        self.lblTimePeriods.setObjectName(_fromUtf8("lblTimePeriods"))
        self.vlProjectDefaults.addWidget(self.lblTimePeriods)
        self.pteTimePeriods = QtGui.QPlainTextEdit(self.layoutWidget)
        self.pteTimePeriods.setObjectName(_fromUtf8("pteTimePeriods"))
        self.vlProjectDefaults.addWidget(self.pteTimePeriods)
        self.lblAnnualVariation = QtGui.QLabel(self.layoutWidget)
        self.lblAnnualVariation.setObjectName(_fromUtf8("lblAnnualVariation"))
        self.vlProjectDefaults.addWidget(self.lblAnnualVariation)
        self.pteAnnualVariation = QtGui.QPlainTextEdit(self.layoutWidget)
        self.pteAnnualVariation.setObjectName(_fromUtf8("pteAnnualVariation"))
        self.vlProjectDefaults.addWidget(self.pteAnnualVariation)
        self.layoutWidget_2 = QtGui.QWidget(self.twProject)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 341, 561))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.glProjects = QtGui.QGridLayout(self.layoutWidget_2)
        self.glProjects.setMargin(0)
        self.glProjects.setObjectName(_fromUtf8("glProjects"))
        self.lblProjNote = QtGui.QLabel(self.layoutWidget_2)
        self.lblProjNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjNote.setObjectName(_fromUtf8("lblProjNote"))
        self.glProjects.addWidget(self.lblProjNote, 3, 0, 1, 1)
        self.lblProjCode = QtGui.QLabel(self.layoutWidget_2)
        self.lblProjCode.setObjectName(_fromUtf8("lblProjCode"))
        self.glProjects.addWidget(self.lblProjCode, 0, 0, 1, 1)
        self.pteProjectCitations = QtGui.QPlainTextEdit(self.layoutWidget_2)
        self.pteProjectCitations.setObjectName(_fromUtf8("pteProjectCitations"))
        self.glProjects.addWidget(self.pteProjectCitations, 4, 2, 1, 1)
        self.lblProjTags = QtGui.QLabel(self.layoutWidget_2)
        self.lblProjTags.setObjectName(_fromUtf8("lblProjTags"))
        self.glProjects.addWidget(self.lblProjTags, 2, 0, 1, 1)
        self.lblProjDescription = QtGui.QLabel(self.layoutWidget_2)
        self.lblProjDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjDescription.setObjectName(_fromUtf8("lblProjDescription"))
        self.glProjects.addWidget(self.lblProjDescription, 1, 0, 1, 1)
        self.leProjectCode = QtGui.QLineEdit(self.layoutWidget_2)
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.glProjects.addWidget(self.leProjectCode, 0, 2, 1, 1)
        self.leProjectTags = QtGui.QLineEdit(self.layoutWidget_2)
        self.leProjectTags.setObjectName(_fromUtf8("leProjectTags"))
        self.glProjects.addWidget(self.leProjectTags, 2, 2, 1, 1)
        self.pteProjectDescription = QtGui.QPlainTextEdit(self.layoutWidget_2)
        self.pteProjectDescription.setObjectName(_fromUtf8("pteProjectDescription"))
        self.glProjects.addWidget(self.pteProjectDescription, 1, 2, 1, 1)
        self.lblCitations = QtGui.QLabel(self.layoutWidget_2)
        self.lblCitations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblCitations.setObjectName(_fromUtf8("lblCitations"))
        self.glProjects.addWidget(self.lblCitations, 4, 0, 1, 1)
        self.pteProjectNote = QtGui.QPlainTextEdit(self.layoutWidget_2)
        self.pteProjectNote.setObjectName(_fromUtf8("pteProjectNote"))
        self.glProjects.addWidget(self.pteProjectNote, 3, 2, 1, 1)
        self.hlnDetails = QtGui.QFrame(self.twProject)
        self.hlnDetails.setGeometry(QtCore.QRect(10, 580, 761, 16))
        self.hlnDetails.setFrameShape(QtGui.QFrame.HLine)
        self.hlnDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnDetails.setObjectName(_fromUtf8("hlnDetails"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.twProject)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 600, 581, 33))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.hlSettings_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.hlSettings_2.setMargin(0)
        self.hlSettings_2.setObjectName(_fromUtf8("hlSettings_2"))
        self.pbProjectSave = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pbProjectSave.setObjectName(_fromUtf8("pbProjectSave"))
        self.hlSettings_2.addWidget(self.pbProjectSave)
        self.pbProjectCancel = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pbProjectCancel.setEnabled(True)
        self.pbProjectCancel.setObjectName(_fromUtf8("pbProjectCancel"))
        self.hlSettings_2.addWidget(self.pbProjectCancel)
        self.wbMapBiographer.addTab(self.twProject, _fromUtf8(""))
        self.twParticipants = QtGui.QWidget()
        self.twParticipants.setEnabled(True)
        self.twParticipants.setObjectName(_fromUtf8("twParticipants"))
        self.lineParticipants = QtGui.QFrame(self.twParticipants)
        self.lineParticipants.setGeometry(QtCore.QRect(10, 230, 761, 16))
        self.lineParticipants.setFrameShape(QtGui.QFrame.HLine)
        self.lineParticipants.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineParticipants.setObjectName(_fromUtf8("lineParticipants"))
        self.tbxParticipants = QtGui.QToolBox(self.twParticipants)
        self.tbxParticipants.setEnabled(True)
        self.tbxParticipants.setGeometry(QtCore.QRect(10, 250, 761, 391))
        self.tbxParticipants.setObjectName(_fromUtf8("tbxParticipants"))
        self.pgBasicInfo = QtGui.QWidget()
        self.pgBasicInfo.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgBasicInfo.setObjectName(_fromUtf8("pgBasicInfo"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.pgBasicInfo)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 751, 281))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.glParticipants = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.glParticipants.setMargin(0)
        self.glParticipants.setObjectName(_fromUtf8("glParticipants"))
        self.lblFamilyGroup = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblFamilyGroup.setObjectName(_fromUtf8("lblFamilyGroup"))
        self.glParticipants.addWidget(self.lblFamilyGroup, 5, 0, 1, 1)
        self.lblEmail = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.glParticipants.addWidget(self.lblEmail, 3, 0, 1, 1)
        self.lblCommunityName = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblCommunityName.setObjectName(_fromUtf8("lblCommunityName"))
        self.glParticipants.addWidget(self.lblCommunityName, 4, 0, 1, 1)
        self.leFirstName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leFirstName.setObjectName(_fromUtf8("leFirstName"))
        self.glParticipants.addWidget(self.leFirstName, 1, 2, 1, 1)
        self.leCommunity = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leCommunity.setObjectName(_fromUtf8("leCommunity"))
        self.glParticipants.addWidget(self.leCommunity, 4, 2, 1, 1)
        self.leEmail = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leEmail.setObjectName(_fromUtf8("leEmail"))
        self.glParticipants.addWidget(self.leEmail, 3, 2, 1, 1)
        self.lblParticipantUserName = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblParticipantUserName.setObjectName(_fromUtf8("lblParticipantUserName"))
        self.glParticipants.addWidget(self.lblParticipantUserName, 0, 0, 1, 1)
        self.lblFirstName = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblFirstName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.glParticipants.addWidget(self.lblFirstName, 1, 0, 1, 1)
        self.lblLastName = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.glParticipants.addWidget(self.lblLastName, 2, 0, 1, 1)
        self.leFamily = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leFamily.setObjectName(_fromUtf8("leFamily"))
        self.glParticipants.addWidget(self.leFamily, 5, 2, 1, 1)
        self.leParticipantUserName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leParticipantUserName.setObjectName(_fromUtf8("leParticipantUserName"))
        self.glParticipants.addWidget(self.leParticipantUserName, 0, 2, 1, 1)
        self.leLastName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leLastName.setObjectName(_fromUtf8("leLastName"))
        self.glParticipants.addWidget(self.leLastName, 2, 2, 1, 1)
        self.lblParticipantTags = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblParticipantTags.setObjectName(_fromUtf8("lblParticipantTags"))
        self.glParticipants.addWidget(self.lblParticipantTags, 4, 4, 1, 1)
        self.leParticipantTags = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leParticipantTags.setObjectName(_fromUtf8("leParticipantTags"))
        self.glParticipants.addWidget(self.leParticipantTags, 4, 6, 1, 1)
        self.lblBirthDate = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.glParticipants.addWidget(self.lblBirthDate, 3, 4, 1, 1)
        self.lblMaritalStatus = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblMaritalStatus.setObjectName(_fromUtf8("lblMaritalStatus"))
        self.glParticipants.addWidget(self.lblMaritalStatus, 2, 4, 1, 1)
        self.cbMaritalStatus = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.cbMaritalStatus.setObjectName(_fromUtf8("cbMaritalStatus"))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.glParticipants.addWidget(self.cbMaritalStatus, 2, 6, 1, 1)
        self.lblGender = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblGender.setObjectName(_fromUtf8("lblGender"))
        self.glParticipants.addWidget(self.lblGender, 1, 4, 1, 1)
        self.cbGender = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.cbGender.setObjectName(_fromUtf8("cbGender"))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.glParticipants.addWidget(self.cbGender, 1, 6, 1, 1)
        self.lblMaidenName = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblMaidenName.setObjectName(_fromUtf8("lblMaidenName"))
        self.glParticipants.addWidget(self.lblMaidenName, 0, 4, 1, 1)
        self.leMaidenName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leMaidenName.setObjectName(_fromUtf8("leMaidenName"))
        self.glParticipants.addWidget(self.leMaidenName, 0, 6, 1, 1)
        self.lblParticipantNotes = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lblParticipantNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblParticipantNotes.setObjectName(_fromUtf8("lblParticipantNotes"))
        self.glParticipants.addWidget(self.lblParticipantNotes, 5, 4, 1, 1)
        self.pteParticipantNote = QtGui.QPlainTextEdit(self.gridLayoutWidget_3)
        self.pteParticipantNote.setObjectName(_fromUtf8("pteParticipantNote"))
        self.glParticipants.addWidget(self.pteParticipantNote, 5, 6, 1, 1)
        self.leBirthDate = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leBirthDate.setObjectName(_fromUtf8("leBirthDate"))
        self.glParticipants.addWidget(self.leBirthDate, 3, 6, 1, 1)
        self.tbxParticipants.addItem(self.pgBasicInfo, _fromUtf8(""))
        self.pgAddresses = QtGui.QWidget()
        self.pgAddresses.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgAddresses.setObjectName(_fromUtf8("pgAddresses"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.pgAddresses)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 362, 281))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.vlAddressList = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vlAddressList.setMargin(0)
        self.vlAddressList.setObjectName(_fromUtf8("vlAddressList"))
        self.lblAddresses = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblAddresses.setObjectName(_fromUtf8("lblAddresses"))
        self.vlAddressList.addWidget(self.lblAddresses)
        self.tblAddresses = QtGui.QTableWidget(self.verticalLayoutWidget_4)
        self.tblAddresses.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblAddresses.setTabKeyNavigation(False)
        self.tblAddresses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblAddresses.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAddresses.setObjectName(_fromUtf8("tblAddresses"))
        self.tblAddresses.setColumnCount(0)
        self.tblAddresses.setRowCount(0)
        self.vlAddressList.addWidget(self.tblAddresses)
        self.hlAddressList = QtGui.QHBoxLayout()
        self.hlAddressList.setObjectName(_fromUtf8("hlAddressList"))
        self.pbAddNew = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbAddNew.setObjectName(_fromUtf8("pbAddNew"))
        self.hlAddressList.addWidget(self.pbAddNew)
        self.pbAddSave = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbAddSave.setEnabled(False)
        self.pbAddSave.setObjectName(_fromUtf8("pbAddSave"))
        self.hlAddressList.addWidget(self.pbAddSave)
        self.pbAddCancel = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbAddCancel.setEnabled(False)
        self.pbAddCancel.setObjectName(_fromUtf8("pbAddCancel"))
        self.hlAddressList.addWidget(self.pbAddCancel)
        self.pbAddDelete = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbAddDelete.setEnabled(False)
        self.pbAddDelete.setObjectName(_fromUtf8("pbAddDelete"))
        self.hlAddressList.addWidget(self.pbAddDelete)
        self.vlAddressList.addLayout(self.hlAddressList)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.pgAddresses)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(370, 0, 381, 281))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.grAddresses = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.grAddresses.setMargin(0)
        self.grAddresses.setObjectName(_fromUtf8("grAddresses"))
        self.leLineTwo = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leLineTwo.setObjectName(_fromUtf8("leLineTwo"))
        self.grAddresses.addWidget(self.leLineTwo, 2, 2, 1, 1)
        self.leCity = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leCity.setObjectName(_fromUtf8("leCity"))
        self.grAddresses.addWidget(self.leCity, 3, 2, 1, 1)
        self.lblCountry = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblCountry.setObjectName(_fromUtf8("lblCountry"))
        self.grAddresses.addWidget(self.lblCountry, 5, 0, 1, 1)
        self.lblAddType = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblAddType.setObjectName(_fromUtf8("lblAddType"))
        self.grAddresses.addWidget(self.lblAddType, 0, 0, 1, 1)
        self.lblLineTwo = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblLineTwo.setObjectName(_fromUtf8("lblLineTwo"))
        self.grAddresses.addWidget(self.lblLineTwo, 2, 0, 1, 1)
        self.lblProvince = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblProvince.setObjectName(_fromUtf8("lblProvince"))
        self.grAddresses.addWidget(self.lblProvince, 4, 0, 1, 1)
        self.cbAddType = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cbAddType.setObjectName(_fromUtf8("cbAddType"))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.grAddresses.addWidget(self.cbAddType, 0, 2, 1, 1)
        self.lblCity = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblCity.setObjectName(_fromUtf8("lblCity"))
        self.grAddresses.addWidget(self.lblCity, 3, 0, 1, 1)
        self.leProvince = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leProvince.setObjectName(_fromUtf8("leProvince"))
        self.grAddresses.addWidget(self.leProvince, 4, 2, 1, 1)
        self.leCountry = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leCountry.setObjectName(_fromUtf8("leCountry"))
        self.grAddresses.addWidget(self.leCountry, 5, 2, 1, 1)
        self.lblPostalCode = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblPostalCode.setObjectName(_fromUtf8("lblPostalCode"))
        self.grAddresses.addWidget(self.lblPostalCode, 6, 0, 1, 1)
        self.lePostalCode = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.lePostalCode.setObjectName(_fromUtf8("lePostalCode"))
        self.grAddresses.addWidget(self.lePostalCode, 6, 2, 1, 1)
        self.lblLineOne = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblLineOne.setObjectName(_fromUtf8("lblLineOne"))
        self.grAddresses.addWidget(self.lblLineOne, 1, 0, 1, 1)
        self.leLineOne = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.leLineOne.setObjectName(_fromUtf8("leLineOne"))
        self.grAddresses.addWidget(self.leLineOne, 1, 2, 1, 1)
        self.tbxParticipants.addItem(self.pgAddresses, _fromUtf8(""))
        self.pgTelecoms = QtGui.QWidget()
        self.pgTelecoms.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgTelecoms.setObjectName(_fromUtf8("pgTelecoms"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.pgTelecoms)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 362, 281))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.vlTelecomList = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vlTelecomList.setMargin(0)
        self.vlTelecomList.setObjectName(_fromUtf8("vlTelecomList"))
        self.lblTelecoms = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.lblTelecoms.setObjectName(_fromUtf8("lblTelecoms"))
        self.vlTelecomList.addWidget(self.lblTelecoms)
        self.tblTelecoms = QtGui.QTableWidget(self.verticalLayoutWidget_5)
        self.tblTelecoms.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblTelecoms.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblTelecoms.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblTelecoms.setObjectName(_fromUtf8("tblTelecoms"))
        self.tblTelecoms.setColumnCount(0)
        self.tblTelecoms.setRowCount(0)
        self.vlTelecomList.addWidget(self.tblTelecoms)
        self.hlTelecomList = QtGui.QHBoxLayout()
        self.hlTelecomList.setObjectName(_fromUtf8("hlTelecomList"))
        self.pbTelNew = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.pbTelNew.setObjectName(_fromUtf8("pbTelNew"))
        self.hlTelecomList.addWidget(self.pbTelNew)
        self.pbTelSave = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.pbTelSave.setEnabled(False)
        self.pbTelSave.setObjectName(_fromUtf8("pbTelSave"))
        self.hlTelecomList.addWidget(self.pbTelSave)
        self.pbTelCancel = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.pbTelCancel.setEnabled(False)
        self.pbTelCancel.setObjectName(_fromUtf8("pbTelCancel"))
        self.hlTelecomList.addWidget(self.pbTelCancel)
        self.pbTelDelete = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.pbTelDelete.setEnabled(False)
        self.pbTelDelete.setObjectName(_fromUtf8("pbTelDelete"))
        self.hlTelecomList.addWidget(self.pbTelDelete)
        self.vlTelecomList.addLayout(self.hlTelecomList)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.pgTelecoms)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(370, 0, 381, 97))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblTelType = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblTelType.setObjectName(_fromUtf8("lblTelType"))
        self.gridLayout.addWidget(self.lblTelType, 0, 0, 1, 1)
        self.cbTelType = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cbTelType.setObjectName(_fromUtf8("cbTelType"))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbTelType, 0, 1, 1, 1)
        self.lblTelecom = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblTelecom.setObjectName(_fromUtf8("lblTelecom"))
        self.gridLayout.addWidget(self.lblTelecom, 1, 0, 1, 1)
        self.leTelNumber = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.leTelNumber.setObjectName(_fromUtf8("leTelNumber"))
        self.gridLayout.addWidget(self.leTelNumber, 1, 1, 1, 1)
        self.tbxParticipants.addItem(self.pgTelecoms, _fromUtf8(""))
        self.frParticipants = QtGui.QFrame(self.twParticipants)
        self.frParticipants.setEnabled(True)
        self.frParticipants.setGeometry(QtCore.QRect(10, 10, 761, 221))
        self.frParticipants.setFrameShape(QtGui.QFrame.NoFrame)
        self.frParticipants.setFrameShadow(QtGui.QFrame.Plain)
        self.frParticipants.setObjectName(_fromUtf8("frParticipants"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frParticipants)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 761, 221))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.vlParticipantsList = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vlParticipantsList.setMargin(0)
        self.vlParticipantsList.setObjectName(_fromUtf8("vlParticipantsList"))
        self.lblParticipants = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.vlParticipantsList.addWidget(self.lblParticipants)
        self.tblParticipants = QtGui.QTableWidget(self.verticalLayoutWidget_3)
        self.tblParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblParticipants.setTabKeyNavigation(False)
        self.tblParticipants.setProperty("showDropIndicator", False)
        self.tblParticipants.setDragDropOverwriteMode(False)
        self.tblParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblParticipants.setObjectName(_fromUtf8("tblParticipants"))
        self.tblParticipants.setColumnCount(0)
        self.tblParticipants.setRowCount(0)
        self.vlParticipantsList.addWidget(self.tblParticipants)
        self.hzParticipantList = QtGui.QHBoxLayout()
        self.hzParticipantList.setObjectName(_fromUtf8("hzParticipantList"))
        self.pbParticipantNew = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pbParticipantNew.setObjectName(_fromUtf8("pbParticipantNew"))
        self.hzParticipantList.addWidget(self.pbParticipantNew)
        self.pbParticipantSave = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pbParticipantSave.setEnabled(False)
        self.pbParticipantSave.setObjectName(_fromUtf8("pbParticipantSave"))
        self.hzParticipantList.addWidget(self.pbParticipantSave)
        self.pbParticipantCancel = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pbParticipantCancel.setEnabled(False)
        self.pbParticipantCancel.setObjectName(_fromUtf8("pbParticipantCancel"))
        self.hzParticipantList.addWidget(self.pbParticipantCancel)
        self.pbParticipantDelete = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pbParticipantDelete.setEnabled(False)
        self.pbParticipantDelete.setObjectName(_fromUtf8("pbParticipantDelete"))
        self.hzParticipantList.addWidget(self.pbParticipantDelete)
        self.vlParticipantsList.addLayout(self.hzParticipantList)
        self.wbMapBiographer.addTab(self.twParticipants, _fromUtf8(""))
        self.twInterviews = QtGui.QWidget()
        self.twInterviews.setEnabled(True)
        self.twInterviews.setObjectName(_fromUtf8("twInterviews"))
        self.lineInterviews = QtGui.QFrame(self.twInterviews)
        self.lineInterviews.setGeometry(QtCore.QRect(10, 230, 761, 16))
        self.lineInterviews.setFrameShape(QtGui.QFrame.HLine)
        self.lineInterviews.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineInterviews.setObjectName(_fromUtf8("lineInterviews"))
        self.tbxInterview = QtGui.QToolBox(self.twInterviews)
        self.tbxInterview.setGeometry(QtCore.QRect(10, 250, 761, 381))
        self.tbxInterview.setObjectName(_fromUtf8("tbxInterview"))
        self.pgIntBasic = QtGui.QWidget()
        self.pgIntBasic.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgIntBasic.setObjectName(_fromUtf8("pgIntBasic"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.pgIntBasic)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 761, 311))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.glInterview = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.glInterview.setMargin(0)
        self.glInterview.setObjectName(_fromUtf8("glInterview"))
        self.leInterviewCode = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leInterviewCode.setObjectName(_fromUtf8("leInterviewCode"))
        self.glInterview.addWidget(self.leInterviewCode, 0, 2, 1, 1)
        self.lblCode = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.glInterview.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblLocation = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblLocation.setObjectName(_fromUtf8("lblLocation"))
        self.glInterview.addWidget(self.lblLocation, 0, 3, 1, 1)
        self.pteInterviewDescription = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.pteInterviewDescription.setObjectName(_fromUtf8("pteInterviewDescription"))
        self.glInterview.addWidget(self.pteInterviewDescription, 1, 2, 1, 1)
        self.leInterviewLocation = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leInterviewLocation.setObjectName(_fromUtf8("leInterviewLocation"))
        self.glInterview.addWidget(self.leInterviewLocation, 0, 5, 1, 1)
        self.pteInterviewNote = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.pteInterviewNote.setObjectName(_fromUtf8("pteInterviewNote"))
        self.glInterview.addWidget(self.pteInterviewNote, 1, 5, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.glInterview.addWidget(self.lblSecurity, 2, 3, 1, 1)
        self.lblStartDate = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblStartDate.setObjectName(_fromUtf8("lblStartDate"))
        self.glInterview.addWidget(self.lblStartDate, 2, 0, 1, 1)
        self.dteStart = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dteStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.dteStart.setTime(QtCore.QTime(12, 0, 0))
        self.dteStart.setObjectName(_fromUtf8("dteStart"))
        self.glInterview.addWidget(self.dteStart, 2, 2, 1, 1)
        self.cbInterviewSecurity = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cbInterviewSecurity.setObjectName(_fromUtf8("cbInterviewSecurity"))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.glInterview.addWidget(self.cbInterviewSecurity, 2, 5, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.glInterview.addWidget(self.lblEndDate, 3, 0, 1, 1)
        self.dteEnd = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dteEnd.setTime(QtCore.QTime(12, 0, 0))
        self.dteEnd.setObjectName(_fromUtf8("dteEnd"))
        self.glInterview.addWidget(self.dteEnd, 3, 2, 1, 1)
        self.lblDescription = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.glInterview.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.lblNotes = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNotes.setObjectName(_fromUtf8("lblNotes"))
        self.glInterview.addWidget(self.lblNotes, 1, 3, 1, 1)
        self.lblTags = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.glInterview.addWidget(self.lblTags, 4, 0, 1, 1)
        self.leInterviewTags = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leInterviewTags.setObjectName(_fromUtf8("leInterviewTags"))
        self.glInterview.addWidget(self.leInterviewTags, 4, 2, 1, 1)
        self.lblInterviewer = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblInterviewer.setObjectName(_fromUtf8("lblInterviewer"))
        self.glInterview.addWidget(self.lblInterviewer, 3, 3, 1, 1)
        self.cbInterviewer = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cbInterviewer.setObjectName(_fromUtf8("cbInterviewer"))
        self.glInterview.addWidget(self.cbInterviewer, 3, 5, 1, 1)
        self.tbxInterview.addItem(self.pgIntBasic, _fromUtf8(""))
        self.pgIntParticipants = QtGui.QWidget()
        self.pgIntParticipants.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgIntParticipants.setObjectName(_fromUtf8("pgIntParticipants"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.pgIntParticipants)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 371, 311))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.vlInterviewParticipants = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.vlInterviewParticipants.setMargin(0)
        self.vlInterviewParticipants.setObjectName(_fromUtf8("vlInterviewParticipants"))
        self.lblInterviewParticipants = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.lblInterviewParticipants.setObjectName(_fromUtf8("lblInterviewParticipants"))
        self.vlInterviewParticipants.addWidget(self.lblInterviewParticipants)
        self.tblInterviewParticipants = QtGui.QTableWidget(self.verticalLayoutWidget_6)
        self.tblInterviewParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviewParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviewParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviewParticipants.setObjectName(_fromUtf8("tblInterviewParticipants"))
        self.tblInterviewParticipants.setColumnCount(0)
        self.tblInterviewParticipants.setRowCount(0)
        self.vlInterviewParticipants.addWidget(self.tblInterviewParticipants)
        self.hlInterviewParticipants = QtGui.QHBoxLayout()
        self.hlInterviewParticipants.setObjectName(_fromUtf8("hlInterviewParticipants"))
        self.pbIntPartNew = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pbIntPartNew.setObjectName(_fromUtf8("pbIntPartNew"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartNew)
        self.pbIntPartSave = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pbIntPartSave.setEnabled(False)
        self.pbIntPartSave.setObjectName(_fromUtf8("pbIntPartSave"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartSave)
        self.pbIntPartCancel = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pbIntPartCancel.setEnabled(False)
        self.pbIntPartCancel.setObjectName(_fromUtf8("pbIntPartCancel"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartCancel)
        self.pbIntPartDelete = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pbIntPartDelete.setEnabled(False)
        self.pbIntPartDelete.setObjectName(_fromUtf8("pbIntPartDelete"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartDelete)
        self.vlInterviewParticipants.addLayout(self.hlInterviewParticipants)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.pgIntParticipants)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(380, 0, 381, 131))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.glIntCont = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.glIntCont.setMargin(0)
        self.glIntCont.setObjectName(_fromUtf8("glIntCont"))
        self.lblIntPartFamily = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblIntPartFamily.setObjectName(_fromUtf8("lblIntPartFamily"))
        self.glIntCont.addWidget(self.lblIntPartFamily, 2, 0, 1, 1)
        self.lblIntPartName = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblIntPartName.setObjectName(_fromUtf8("lblIntPartName"))
        self.glIntCont.addWidget(self.lblIntPartName, 0, 0, 1, 1)
        self.leIntPartFamily = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.leIntPartFamily.setObjectName(_fromUtf8("leIntPartFamily"))
        self.glIntCont.addWidget(self.leIntPartFamily, 2, 2, 1, 1)
        self.lblIntPartCommunity = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblIntPartCommunity.setObjectName(_fromUtf8("lblIntPartCommunity"))
        self.glIntCont.addWidget(self.lblIntPartCommunity, 1, 0, 1, 1)
        self.leIntPartCommunity = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.leIntPartCommunity.setObjectName(_fromUtf8("leIntPartCommunity"))
        self.glIntCont.addWidget(self.leIntPartCommunity, 1, 2, 1, 1)
        self.cbIntPartName = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cbIntPartName.setObjectName(_fromUtf8("cbIntPartName"))
        self.glIntCont.addWidget(self.cbIntPartName, 0, 2, 1, 1)
        self.tbxInterview.addItem(self.pgIntParticipants, _fromUtf8(""))
        self.frInterviews = QtGui.QFrame(self.twInterviews)
        self.frInterviews.setGeometry(QtCore.QRect(10, 10, 761, 221))
        self.frInterviews.setFrameShape(QtGui.QFrame.NoFrame)
        self.frInterviews.setFrameShadow(QtGui.QFrame.Plain)
        self.frInterviews.setObjectName(_fromUtf8("frInterviews"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frInterviews)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 221))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlInterviewList = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlInterviewList.setMargin(0)
        self.vlInterviewList.setObjectName(_fromUtf8("vlInterviewList"))
        self.lblInterviews = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblInterviews.setObjectName(_fromUtf8("lblInterviews"))
        self.vlInterviewList.addWidget(self.lblInterviews)
        self.tblInterviews = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.tblInterviews.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviews.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviews.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviews.setObjectName(_fromUtf8("tblInterviews"))
        self.tblInterviews.setColumnCount(0)
        self.tblInterviews.setRowCount(0)
        self.vlInterviewList.addWidget(self.tblInterviews)
        self.hlInterviewList = QtGui.QHBoxLayout()
        self.hlInterviewList.setObjectName(_fromUtf8("hlInterviewList"))
        self.pbIntNew = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbIntNew.setObjectName(_fromUtf8("pbIntNew"))
        self.hlInterviewList.addWidget(self.pbIntNew)
        self.pbIntSave = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbIntSave.setEnabled(False)
        self.pbIntSave.setObjectName(_fromUtf8("pbIntSave"))
        self.hlInterviewList.addWidget(self.pbIntSave)
        self.pbIntCancel = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbIntCancel.setEnabled(False)
        self.pbIntCancel.setObjectName(_fromUtf8("pbIntCancel"))
        self.hlInterviewList.addWidget(self.pbIntCancel)
        self.pbIntDelete = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbIntDelete.setEnabled(False)
        self.pbIntDelete.setObjectName(_fromUtf8("pbIntDelete"))
        self.hlInterviewList.addWidget(self.pbIntDelete)
        self.vlInterviewList.addLayout(self.hlInterviewList)
        self.wbMapBiographer.addTab(self.twInterviews, _fromUtf8(""))
        self.twAbout = QtGui.QWidget()
        self.twAbout.setObjectName(_fromUtf8("twAbout"))
        self.teAbout = QtGui.QTextEdit(self.twAbout)
        self.teAbout.setEnabled(True)
        self.teAbout.setGeometry(QtCore.QRect(10, 10, 761, 621))
        self.teAbout.setAcceptDrops(False)
        self.teAbout.setUndoRedoEnabled(False)
        self.teAbout.setReadOnly(True)
        self.teAbout.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.teAbout.setObjectName(_fromUtf8("teAbout"))
        self.wbMapBiographer.addTab(self.twAbout, _fromUtf8(""))
        self.pbDialogClose = QtGui.QPushButton(mapBiographerSettings)
        self.pbDialogClose.setGeometry(QtCore.QRect(690, 700, 95, 31))
        self.pbDialogClose.setObjectName(_fromUtf8("pbDialogClose"))

        self.retranslateUi(mapBiographerSettings)
        self.wbMapBiographer.setCurrentIndex(0)
        self.tbxParticipants.setCurrentIndex(0)
        self.tbxInterview.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapBiographerSettings)
        mapBiographerSettings.setTabOrder(self.wbMapBiographer, self.leProjectDir)
        mapBiographerSettings.setTabOrder(self.leProjectDir, self.tbSelectProjectDir)
        mapBiographerSettings.setTabOrder(self.tbSelectProjectDir, self.cbProjectDatabase)
        mapBiographerSettings.setTabOrder(self.cbProjectDatabase, self.leQgsProject)
        mapBiographerSettings.setTabOrder(self.leQgsProject, self.tbSelectQgsProject)
        mapBiographerSettings.setTabOrder(self.tbSelectQgsProject, self.tblBaseGroups)
        mapBiographerSettings.setTabOrder(self.tblBaseGroups, self.cbProjectGroups)
        mapBiographerSettings.setTabOrder(self.cbProjectGroups, self.pbAddBaseGroup)
        mapBiographerSettings.setTabOrder(self.pbAddBaseGroup, self.pbRemoveBaseGroup)
        mapBiographerSettings.setTabOrder(self.pbRemoveBaseGroup, self.cbBoundaryLayer)
        mapBiographerSettings.setTabOrder(self.cbBoundaryLayer, self.cbEnableReference)
        mapBiographerSettings.setTabOrder(self.cbEnableReference, self.cbReferenceLayer)
        mapBiographerSettings.setTabOrder(self.cbReferenceLayer, self.rdoHasHeritage)
        mapBiographerSettings.setTabOrder(self.rdoHasHeritage, self.rdoNoHeritage)
        mapBiographerSettings.setTabOrder(self.rdoNoHeritage, self.leHeritageCommunity)
        mapBiographerSettings.setTabOrder(self.leHeritageCommunity, self.leHeritageUser)
        mapBiographerSettings.setTabOrder(self.leHeritageUser, self.pbPullData)
        mapBiographerSettings.setTabOrder(self.pbPullData, self.pbPushData)
        mapBiographerSettings.setTabOrder(self.pbPushData, self.pbSaveSettings)
        mapBiographerSettings.setTabOrder(self.pbSaveSettings, self.pbCancelSettings)
        mapBiographerSettings.setTabOrder(self.pbCancelSettings, self.pbExport)
        mapBiographerSettings.setTabOrder(self.pbExport, self.leProjectCode)
        mapBiographerSettings.setTabOrder(self.leProjectCode, self.pteProjectDescription)
        mapBiographerSettings.setTabOrder(self.pteProjectDescription, self.leProjectTags)
        mapBiographerSettings.setTabOrder(self.leProjectTags, self.pteProjectNote)
        mapBiographerSettings.setTabOrder(self.pteProjectNote, self.pteProjectCitations)
        mapBiographerSettings.setTabOrder(self.pteProjectCitations, self.pteContentCodes)
        mapBiographerSettings.setTabOrder(self.pteContentCodes, self.pteTimePeriods)
        mapBiographerSettings.setTabOrder(self.pteTimePeriods, self.pteAnnualVariation)
        mapBiographerSettings.setTabOrder(self.pteAnnualVariation, self.pbProjectSave)
        mapBiographerSettings.setTabOrder(self.pbProjectSave, self.pbProjectCancel)
        mapBiographerSettings.setTabOrder(self.pbProjectCancel, self.tblParticipants)
        mapBiographerSettings.setTabOrder(self.tblParticipants, self.pbParticipantNew)
        mapBiographerSettings.setTabOrder(self.pbParticipantNew, self.pbParticipantSave)
        mapBiographerSettings.setTabOrder(self.pbParticipantSave, self.pbParticipantCancel)
        mapBiographerSettings.setTabOrder(self.pbParticipantCancel, self.pbParticipantDelete)
        mapBiographerSettings.setTabOrder(self.pbParticipantDelete, self.leParticipantUserName)
        mapBiographerSettings.setTabOrder(self.leParticipantUserName, self.leFirstName)
        mapBiographerSettings.setTabOrder(self.leFirstName, self.leLastName)
        mapBiographerSettings.setTabOrder(self.leLastName, self.leEmail)
        mapBiographerSettings.setTabOrder(self.leEmail, self.leCommunity)
        mapBiographerSettings.setTabOrder(self.leCommunity, self.leFamily)
        mapBiographerSettings.setTabOrder(self.leFamily, self.leMaidenName)
        mapBiographerSettings.setTabOrder(self.leMaidenName, self.cbGender)
        mapBiographerSettings.setTabOrder(self.cbGender, self.cbMaritalStatus)
        mapBiographerSettings.setTabOrder(self.cbMaritalStatus, self.leBirthDate)
        mapBiographerSettings.setTabOrder(self.leBirthDate, self.leParticipantTags)
        mapBiographerSettings.setTabOrder(self.leParticipantTags, self.pteParticipantNote)
        mapBiographerSettings.setTabOrder(self.pteParticipantNote, self.tblAddresses)
        mapBiographerSettings.setTabOrder(self.tblAddresses, self.pbAddNew)
        mapBiographerSettings.setTabOrder(self.pbAddNew, self.pbAddSave)
        mapBiographerSettings.setTabOrder(self.pbAddSave, self.pbAddCancel)
        mapBiographerSettings.setTabOrder(self.pbAddCancel, self.pbAddDelete)
        mapBiographerSettings.setTabOrder(self.pbAddDelete, self.cbAddType)
        mapBiographerSettings.setTabOrder(self.cbAddType, self.leLineOne)
        mapBiographerSettings.setTabOrder(self.leLineOne, self.leLineTwo)
        mapBiographerSettings.setTabOrder(self.leLineTwo, self.leCity)
        mapBiographerSettings.setTabOrder(self.leCity, self.leProvince)
        mapBiographerSettings.setTabOrder(self.leProvince, self.leCountry)
        mapBiographerSettings.setTabOrder(self.leCountry, self.lePostalCode)
        mapBiographerSettings.setTabOrder(self.lePostalCode, self.tblTelecoms)
        mapBiographerSettings.setTabOrder(self.tblTelecoms, self.pbTelNew)
        mapBiographerSettings.setTabOrder(self.pbTelNew, self.pbTelSave)
        mapBiographerSettings.setTabOrder(self.pbTelSave, self.pbTelCancel)
        mapBiographerSettings.setTabOrder(self.pbTelCancel, self.pbTelDelete)
        mapBiographerSettings.setTabOrder(self.pbTelDelete, self.cbTelType)
        mapBiographerSettings.setTabOrder(self.cbTelType, self.leTelNumber)
        mapBiographerSettings.setTabOrder(self.leTelNumber, self.tblInterviews)
        mapBiographerSettings.setTabOrder(self.tblInterviews, self.pbIntNew)
        mapBiographerSettings.setTabOrder(self.pbIntNew, self.pbIntSave)
        mapBiographerSettings.setTabOrder(self.pbIntSave, self.pbIntCancel)
        mapBiographerSettings.setTabOrder(self.pbIntCancel, self.pbIntDelete)
        mapBiographerSettings.setTabOrder(self.pbIntDelete, self.leInterviewCode)
        mapBiographerSettings.setTabOrder(self.leInterviewCode, self.pteInterviewDescription)
        mapBiographerSettings.setTabOrder(self.pteInterviewDescription, self.dteStart)
        mapBiographerSettings.setTabOrder(self.dteStart, self.dteEnd)
        mapBiographerSettings.setTabOrder(self.dteEnd, self.leInterviewTags)
        mapBiographerSettings.setTabOrder(self.leInterviewTags, self.leInterviewLocation)
        mapBiographerSettings.setTabOrder(self.leInterviewLocation, self.pteInterviewNote)
        mapBiographerSettings.setTabOrder(self.pteInterviewNote, self.cbInterviewSecurity)
        mapBiographerSettings.setTabOrder(self.cbInterviewSecurity, self.cbInterviewer)
        mapBiographerSettings.setTabOrder(self.cbInterviewer, self.tblParticipants)
        mapBiographerSettings.setTabOrder(self.tblParticipants, self.tblInterviewParticipants)
        mapBiographerSettings.setTabOrder(self.tblInterviewParticipants, self.pbIntPartNew)
        mapBiographerSettings.setTabOrder(self.pbIntPartNew, self.pbIntPartSave)
        mapBiographerSettings.setTabOrder(self.pbIntPartSave, self.pbIntPartCancel)
        mapBiographerSettings.setTabOrder(self.pbIntPartCancel, self.pbIntPartDelete)
        mapBiographerSettings.setTabOrder(self.pbIntPartDelete, self.cbIntPartName)
        mapBiographerSettings.setTabOrder(self.cbIntPartName, self.leIntPartCommunity)
        mapBiographerSettings.setTabOrder(self.leIntPartCommunity, self.leIntPartFamily)
        mapBiographerSettings.setTabOrder(self.leIntPartFamily, self.teAbout)
        mapBiographerSettings.setTabOrder(self.teAbout, self.pbDialogClose)

    def retranslateUi(self, mapBiographerSettings):
        mapBiographerSettings.setWindowTitle(QtGui.QApplication.translate("mapBiographerSettings", "LOUIS Map Biographer - Project Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectsDir.setText(QtGui.QApplication.translate("mapBiographerSettings", "Projects Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSelectProjectDir.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Click here to set the LOUIS Map Biographer default projects directory.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSelectProjectDir.setText(QtGui.QApplication.translate("mapBiographerSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectDatabase.setText(QtGui.QApplication.translate("mapBiographerSettings", "Project Database", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSettings.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSettings.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbExport.setText(QtGui.QApplication.translate("mapBiographerSettings", "Export Interviews", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQgsProject.setText(QtGui.QApplication.translate("mapBiographerSettings", "QGIS Project", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSelectQgsProject.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Click here to select the QGIS project to use with LOUIS Map Biographer</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSelectQgsProject.setText(QtGui.QApplication.translate("mapBiographerSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBaseGroupOptions.setText(QtGui.QApplication.translate("mapBiographerSettings", "Use project groups as base layers ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddBaseGroup.setText(QtGui.QApplication.translate("mapBiographerSettings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveBaseGroup.setText(QtGui.QApplication.translate("mapBiographerSettings", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBaseLayerGroups.setText(QtGui.QApplication.translate("mapBiographerSettings", "Base Layer Groups           ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectBoundary.setText(QtGui.QApplication.translate("mapBiographerSettings", "Project Boundary Layer ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEnableReference.setText(QtGui.QApplication.translate("mapBiographerSettings", "Enable Reference Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbEnableReference.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbEnableReference.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReferenceLayer.setText(QtGui.QApplication.translate("mapBiographerSettings", "Project Reference Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClientCommunity.setText(QtGui.QApplication.translate("mapBiographerSettings", "Community Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUser.setText(QtGui.QApplication.translate("mapBiographerSettings", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAccount.setText(QtGui.QApplication.translate("mapBiographerSettings", "LOUIS Heritage Account", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoHasHeritage.setText(QtGui.QApplication.translate("mapBiographerSettings", "I have an account", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoNoHeritage.setText(QtGui.QApplication.translate("mapBiographerSettings", "I don\'t have an account yet", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPullData.setText(QtGui.QApplication.translate("mapBiographerSettings", "Download New Interviews", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPushData.setText(QtGui.QApplication.translate("mapBiographerSettings", "Upload Completed Interviews", None, QtGui.QApplication.UnicodeUTF8))
        self.wbMapBiographer.setTabText(self.wbMapBiographer.indexOf(self.twSettings), QtGui.QApplication.translate("mapBiographerSettings", "Map Biographer Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lblContentCodes.setText(QtGui.QApplication.translate("mapBiographerSettings", "Content Codes", None, QtGui.QApplication.UnicodeUTF8))
        self.pteContentCodes.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter a list of codes (one per line) in the following format:</p><p>BP = Berry Picking<br/>CB = Cabin</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimePeriods.setText(QtGui.QApplication.translate("mapBiographerSettings", "Time Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.pteTimePeriods.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter time periods (one per line) using the following format:</p><p>1900-01-01 : 1967-12-31 = Before Bennett Dam<br/>1968-01-01 : 2014-08-31 = After Bennett Dam until today</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAnnualVariation.setText(QtGui.QApplication.translate("mapBiographerSettings", "Annual Variation", None, QtGui.QApplication.UnicodeUTF8))
        self.pteAnnualVariation.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter annual variation options (one per line) using the following format:</p><p>Dec,Jan,Feb = Winter<br/>Mar,Apr,May = Spring<br/>Jun,Jul,Aug = Summer<br/>Sep,Oct,Nov = Autumn</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjNote.setText(QtGui.QApplication.translate("mapBiographerSettings", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjCode.setText(QtGui.QApplication.translate("mapBiographerSettings", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.pteProjectCitations.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter the way this project should be cited here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjTags.setText(QtGui.QApplication.translate("mapBiographerSettings", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjDescription.setText(QtGui.QApplication.translate("mapBiographerSettings", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.leProjectCode.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter a code for this project.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leProjectTags.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter a list of tags or phrases separated by commas here such as:</p><p>Review Needed,Confirmation Meeting Needed,Confirm Contact Details</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pteProjectDescription.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter a brief description of the project here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCitations.setText(QtGui.QApplication.translate("mapBiographerSettings", "Citations", None, QtGui.QApplication.UnicodeUTF8))
        self.pteProjectNote.setToolTip(QtGui.QApplication.translate("mapBiographerSettings", "<html><head/><body><p>Enter project notes here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pbProjectSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbProjectCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.wbMapBiographer.setTabText(self.wbMapBiographer.indexOf(self.twProject), QtGui.QApplication.translate("mapBiographerSettings", "Project Details", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFamilyGroup.setText(QtGui.QApplication.translate("mapBiographerSettings", "Family Group", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("mapBiographerSettings", "Email Address", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCommunityName.setText(QtGui.QApplication.translate("mapBiographerSettings", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipantUserName.setText(QtGui.QApplication.translate("mapBiographerSettings", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFirstName.setText(QtGui.QApplication.translate("mapBiographerSettings", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLastName.setText(QtGui.QApplication.translate("mapBiographerSettings", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipantTags.setText(QtGui.QApplication.translate("mapBiographerSettings", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBirthDate.setText(QtGui.QApplication.translate("mapBiographerSettings", "Birth Date", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaritalStatus.setText(QtGui.QApplication.translate("mapBiographerSettings", "Marital Status", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(2, QtGui.QApplication.translate("mapBiographerSettings", "Married", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(3, QtGui.QApplication.translate("mapBiographerSettings", "Divorced", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(4, QtGui.QApplication.translate("mapBiographerSettings", "Refused", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMaritalStatus.setItemText(5, QtGui.QApplication.translate("mapBiographerSettings", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGender.setText(QtGui.QApplication.translate("mapBiographerSettings", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGender.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGender.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGender.setItemText(2, QtGui.QApplication.translate("mapBiographerSettings", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGender.setItemText(3, QtGui.QApplication.translate("mapBiographerSettings", "Refused", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGender.setItemText(4, QtGui.QApplication.translate("mapBiographerSettings", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaidenName.setText(QtGui.QApplication.translate("mapBiographerSettings", "Maiden Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipantNotes.setText(QtGui.QApplication.translate("mapBiographerSettings", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.leBirthDate.setInputMask(QtGui.QApplication.translate("mapBiographerSettings", "9999-99-99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgBasicInfo), QtGui.QApplication.translate("mapBiographerSettings", "Basic Information", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddresses.setText(QtGui.QApplication.translate("mapBiographerSettings", "Address List", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddNew.setText(QtGui.QApplication.translate("mapBiographerSettings", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddDelete.setText(QtGui.QApplication.translate("mapBiographerSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCountry.setText(QtGui.QApplication.translate("mapBiographerSettings", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddType.setText(QtGui.QApplication.translate("mapBiographerSettings", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLineTwo.setText(QtGui.QApplication.translate("mapBiographerSettings", "Line Two", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProvince.setText(QtGui.QApplication.translate("mapBiographerSettings", "Province", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddType.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddType.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Work", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddType.setItemText(2, QtGui.QApplication.translate("mapBiographerSettings", "PO Box", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddType.setItemText(3, QtGui.QApplication.translate("mapBiographerSettings", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCity.setText(QtGui.QApplication.translate("mapBiographerSettings", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPostalCode.setText(QtGui.QApplication.translate("mapBiographerSettings", "Postal Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLineOne.setText(QtGui.QApplication.translate("mapBiographerSettings", "Line One", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgAddresses), QtGui.QApplication.translate("mapBiographerSettings", "Addresses", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelecoms.setText(QtGui.QApplication.translate("mapBiographerSettings", "Telecoms List", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTelNew.setText(QtGui.QApplication.translate("mapBiographerSettings", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTelSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTelCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTelDelete.setText(QtGui.QApplication.translate("mapBiographerSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelType.setText(QtGui.QApplication.translate("mapBiographerSettings", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Work", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(2, QtGui.QApplication.translate("mapBiographerSettings", "Mobile", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(3, QtGui.QApplication.translate("mapBiographerSettings", "Pager", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(4, QtGui.QApplication.translate("mapBiographerSettings", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTelType.setItemText(5, QtGui.QApplication.translate("mapBiographerSettings", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelecom.setText(QtGui.QApplication.translate("mapBiographerSettings", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgTelecoms), QtGui.QApplication.translate("mapBiographerSettings", "Phones / Faxes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipants.setText(QtGui.QApplication.translate("mapBiographerSettings", "People", None, QtGui.QApplication.UnicodeUTF8))
        self.pbParticipantNew.setText(QtGui.QApplication.translate("mapBiographerSettings", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbParticipantSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbParticipantCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbParticipantDelete.setText(QtGui.QApplication.translate("mapBiographerSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.wbMapBiographer.setTabText(self.wbMapBiographer.indexOf(self.twParticipants), QtGui.QApplication.translate("mapBiographerSettings", "People", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("mapBiographerSettings", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocation.setText(QtGui.QApplication.translate("mapBiographerSettings", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSecurity.setText(QtGui.QApplication.translate("mapBiographerSettings", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartDate.setText(QtGui.QApplication.translate("mapBiographerSettings", "Start Date / Time", None, QtGui.QApplication.UnicodeUTF8))
        self.dteStart.setDisplayFormat(QtGui.QApplication.translate("mapBiographerSettings", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInterviewSecurity.setItemText(0, QtGui.QApplication.translate("mapBiographerSettings", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInterviewSecurity.setItemText(1, QtGui.QApplication.translate("mapBiographerSettings", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInterviewSecurity.setItemText(2, QtGui.QApplication.translate("mapBiographerSettings", "Restricted", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInterviewSecurity.setItemText(3, QtGui.QApplication.translate("mapBiographerSettings", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("mapBiographerSettings", "End Date / Time", None, QtGui.QApplication.UnicodeUTF8))
        self.dteEnd.setDisplayFormat(QtGui.QApplication.translate("mapBiographerSettings", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescription.setText(QtGui.QApplication.translate("mapBiographerSettings", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNotes.setText(QtGui.QApplication.translate("mapBiographerSettings", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTags.setText(QtGui.QApplication.translate("mapBiographerSettings", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterviewer.setText(QtGui.QApplication.translate("mapBiographerSettings", "Interviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntBasic), QtGui.QApplication.translate("mapBiographerSettings", "Interview Information", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterviewParticipants.setText(QtGui.QApplication.translate("mapBiographerSettings", "Participants", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntPartNew.setText(QtGui.QApplication.translate("mapBiographerSettings", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntPartSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntPartCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntPartDelete.setText(QtGui.QApplication.translate("mapBiographerSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIntPartFamily.setText(QtGui.QApplication.translate("mapBiographerSettings", "Family Group", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIntPartName.setText(QtGui.QApplication.translate("mapBiographerSettings", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIntPartCommunity.setText(QtGui.QApplication.translate("mapBiographerSettings", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntParticipants), QtGui.QApplication.translate("mapBiographerSettings", "Interview Participants", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterviews.setText(QtGui.QApplication.translate("mapBiographerSettings", "Interview List", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntNew.setText(QtGui.QApplication.translate("mapBiographerSettings", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntSave.setText(QtGui.QApplication.translate("mapBiographerSettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntCancel.setText(QtGui.QApplication.translate("mapBiographerSettings", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIntDelete.setText(QtGui.QApplication.translate("mapBiographerSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.wbMapBiographer.setTabText(self.wbMapBiographer.indexOf(self.twInterviews), QtGui.QApplication.translate("mapBiographerSettings", "Interviews", None, QtGui.QApplication.UnicodeUTF8))
        self.teAbout.setHtml(QtGui.QApplication.translate("mapBiographerSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LOUIS Map Biographer Version 0.8.3 - Alpha Testing Version</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PLEASE NOTE: This version of LOUIS Map Biographer is an early release as part of our Alpha Testing Program that will operate from 2014-09-02 to 2014-10-31. This version of LOUIS Map Biographer has been released to get user feedback on functional adequacy and ease-of-use; it is not recommended for use with live studies. For more information about the testing program or to submit comments about this version please visit <a href=\"http://aproposinfosystems.com/products/mapbiographer\"><span style=\" text-decoration: underline; color:#0000ff;\">aproposinfosystems.com/products/mapbiographer</span></a> or our contact page at <a href=\"http://aproposinfosystems.com/contact\"><span style=\" text-decoration: underline; color:#0000ff;\">aproposinfosystems.com/contact</span></a>.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ABOUT LOUIS Map Biographer</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LOUIS Map Biographer is a free / open source solution for direct to digital capture of land use information through in-person interviews. LOUIS Map Biographer is designed to support the best practice ideas for Use and Occupancy mapping studies outlined in <span style=\" font-style:italic;\">Living Proof</span><span style=\" vertical-align:super;\">1</span>. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LOUIS Map Biographer is part of the Land Occupancy and Use Information Systems (LOUIS) tool kit. LOUIS Map Biographer can be used on its own or together with other parts of the LOUIS tool kit. For more information about LOUIS tool kit visit: <a href=\"http://louistk.ca\"><span style=\" text-decoration: underline; color:#0000ff;\">louistk.ca</span></a></p>\n"
"<hr />\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 - Tobias, Terry N., 2009. <a href=\"http://ecotrust.ca/first-nations/new-book-use-and-occupancy-map-surveys-now-available\"><span style=\" text-decoration: underline; color:#0000ff;\">Living Proof: The essential data-collection guide for Indigenous Use-and-Occupancy map surveys</span></a>.  Ecostrust Canada and Union of BC Indian Chiefs, British Columbia, Canada.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.wbMapBiographer.setTabText(self.wbMapBiographer.indexOf(self.twAbout), QtGui.QApplication.translate("mapBiographerSettings", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDialogClose.setText(QtGui.QApplication.translate("mapBiographerSettings", "Close", None, QtGui.QApplication.UnicodeUTF8))

