# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_porter.ui'
#
# Created by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapbioPorter(object):
    def setupUi(self, mapbioPorter):
        mapbioPorter.setObjectName(_fromUtf8("mapbioPorter"))
        mapbioPorter.resize(500, 488)
        mapbioPorter.setMinimumSize(QtCore.QSize(500, 100))
        mapbioPorter.setMaximumSize(QtCore.QSize(500, 488))
        mapbioPorter.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtGui.QVBoxLayout(mapbioPorter)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.hlSelectAction = QtGui.QHBoxLayout()
        self.hlSelectAction.setObjectName(_fromUtf8("hlSelectAction"))
        self.lblTransferAction = QtGui.QLabel(mapbioPorter)
        self.lblTransferAction.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblTransferAction.setObjectName(_fromUtf8("lblTransferAction"))
        self.hlSelectAction.addWidget(self.lblTransferAction)
        self.cbTransferAction = QtGui.QComboBox(mapbioPorter)
        self.cbTransferAction.setObjectName(_fromUtf8("cbTransferAction"))
        self.cbTransferAction.addItem(_fromUtf8(""))
        self.cbTransferAction.addItem(_fromUtf8(""))
        self.cbTransferAction.addItem(_fromUtf8(""))
        self.cbTransferAction.addItem(_fromUtf8(""))
        self.cbTransferAction.addItem(_fromUtf8(""))
        self.hlSelectAction.addWidget(self.cbTransferAction)
        self.verticalLayout_3.addLayout(self.hlSelectAction)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.frHeritageLogin = QtGui.QFrame(mapbioPorter)
        self.frHeritageLogin.setFrameShape(QtGui.QFrame.NoFrame)
        self.frHeritageLogin.setFrameShadow(QtGui.QFrame.Plain)
        self.frHeritageLogin.setObjectName(_fromUtf8("frHeritageLogin"))
        self.gridLayout = QtGui.QGridLayout(self.frHeritageLogin)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblUserName = QtGui.QLabel(self.frHeritageLogin)
        self.lblUserName.setMinimumSize(QtCore.QSize(100, 0))
        self.lblUserName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblUserName.setObjectName(_fromUtf8("lblUserName"))
        self.gridLayout.addWidget(self.lblUserName, 1, 0, 1, 1)
        self.lePassword = QtGui.QLineEdit(self.frHeritageLogin)
        self.lePassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lePassword.setObjectName(_fromUtf8("lePassword"))
        self.gridLayout.addWidget(self.lePassword, 2, 1, 1, 1)
        self.leUserName = QtGui.QLineEdit(self.frHeritageLogin)
        self.leUserName.setObjectName(_fromUtf8("leUserName"))
        self.gridLayout.addWidget(self.leUserName, 1, 1, 1, 1)
        self.lblPassword = QtGui.QLabel(self.frHeritageLogin)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.gridLayout.addWidget(self.lblPassword, 2, 0, 1, 1)
        self.lblURL = QtGui.QLabel(self.frHeritageLogin)
        self.lblURL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblURL.setObjectName(_fromUtf8("lblURL"))
        self.gridLayout.addWidget(self.lblURL, 0, 0, 1, 1)
        self.leURL = QtGui.QLineEdit(self.frHeritageLogin)
        self.leURL.setObjectName(_fromUtf8("leURL"))
        self.gridLayout.addWidget(self.leURL, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frHeritageLogin)
        self.frHeritageInfo = QtGui.QFrame(mapbioPorter)
        self.frHeritageInfo.setFrameShape(QtGui.QFrame.NoFrame)
        self.frHeritageInfo.setFrameShadow(QtGui.QFrame.Plain)
        self.frHeritageInfo.setObjectName(_fromUtf8("frHeritageInfo"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frHeritageInfo)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pteReport = QtGui.QPlainTextEdit(self.frHeritageInfo)
        self.pteReport.setEnabled(True)
        self.pteReport.setAcceptDrops(False)
        self.pteReport.setUndoRedoEnabled(False)
        self.pteReport.setReadOnly(True)
        self.pteReport.setObjectName(_fromUtf8("pteReport"))
        self.verticalLayout.addWidget(self.pteReport)
        self.hlHeritageProject = QtGui.QHBoxLayout()
        self.hlHeritageProject.setObjectName(_fromUtf8("hlHeritageProject"))
        self.lblProject = QtGui.QLabel(self.frHeritageInfo)
        self.lblProject.setObjectName(_fromUtf8("lblProject"))
        self.hlHeritageProject.addWidget(self.lblProject)
        self.cbProject = QtGui.QComboBox(self.frHeritageInfo)
        self.cbProject.setObjectName(_fromUtf8("cbProject"))
        self.hlHeritageProject.addWidget(self.cbProject)
        self.verticalLayout.addLayout(self.hlHeritageProject)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbImport = QtGui.QPushButton(self.frHeritageInfo)
        self.pbImport.setEnabled(False)
        self.pbImport.setObjectName(_fromUtf8("pbImport"))
        self.horizontalLayout_2.addWidget(self.pbImport)
        self.pbUpload = QtGui.QPushButton(self.frHeritageInfo)
        self.pbUpload.setEnabled(False)
        self.pbUpload.setObjectName(_fromUtf8("pbUpload"))
        self.horizontalLayout_2.addWidget(self.pbUpload)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.frHeritageInfo)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frProgress = QtGui.QFrame(mapbioPorter)
        self.frProgress.setMaximumSize(QtCore.QSize(16777215, 135))
        self.frProgress.setObjectName(_fromUtf8("frProgress"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frProgress)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblAllProgress = QtGui.QLabel(self.frProgress)
        self.lblAllProgress.setObjectName(_fromUtf8("lblAllProgress"))
        self.verticalLayout_2.addWidget(self.lblAllProgress)
        self.pbAllProgress = QtGui.QProgressBar(self.frProgress)
        self.pbAllProgress.setProperty("value", 0)
        self.pbAllProgress.setObjectName(_fromUtf8("pbAllProgress"))
        self.verticalLayout_2.addWidget(self.pbAllProgress)
        self.lblStepProgress = QtGui.QLabel(self.frProgress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStepProgress.sizePolicy().hasHeightForWidth())
        self.lblStepProgress.setSizePolicy(sizePolicy)
        self.lblStepProgress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblStepProgress.setObjectName(_fromUtf8("lblStepProgress"))
        self.verticalLayout_2.addWidget(self.lblStepProgress)
        self.pbStepProgress = QtGui.QProgressBar(self.frProgress)
        self.pbStepProgress.setProperty("value", 0)
        self.pbStepProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStepProgress.setTextVisible(True)
        self.pbStepProgress.setObjectName(_fromUtf8("pbStepProgress"))
        self.verticalLayout_2.addWidget(self.pbStepProgress)
        self.verticalLayout_3.addWidget(self.frProgress)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbTransfer = QtGui.QPushButton(mapbioPorter)
        self.pbTransfer.setEnabled(False)
        self.pbTransfer.setObjectName(_fromUtf8("pbTransfer"))
        self.horizontalLayout.addWidget(self.pbTransfer)
        self.pbCancel = QtGui.QPushButton(mapbioPorter)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout.addWidget(self.pbCancel)
        self.pbClose = QtGui.QPushButton(mapbioPorter)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.horizontalLayout.addWidget(self.pbClose)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(mapbioPorter)
        QtCore.QMetaObject.connectSlotsByName(mapbioPorter)
        mapbioPorter.setTabOrder(self.cbTransferAction, self.leURL)
        mapbioPorter.setTabOrder(self.leURL, self.leUserName)
        mapbioPorter.setTabOrder(self.leUserName, self.lePassword)
        mapbioPorter.setTabOrder(self.lePassword, self.cbProject)
        mapbioPorter.setTabOrder(self.cbProject, self.pteReport)
        mapbioPorter.setTabOrder(self.pteReport, self.pbImport)
        mapbioPorter.setTabOrder(self.pbImport, self.pbUpload)
        mapbioPorter.setTabOrder(self.pbUpload, self.pbTransfer)
        mapbioPorter.setTabOrder(self.pbTransfer, self.pbCancel)
        mapbioPorter.setTabOrder(self.pbCancel, self.pbClose)

    def retranslateUi(self, mapbioPorter):
        mapbioPorter.setWindowTitle(_translate("mapbioPorter", "Transfer Data", None))
        self.lblTransferAction.setText(_translate("mapbioPorter", "Select Action:", None))
        self.cbTransferAction.setItemText(0, _translate("mapbioPorter", "--None--", None))
        self.cbTransferAction.setItemText(1, _translate("mapbioPorter", "Create Heritage Archive", None))
        self.cbTransferAction.setItemText(2, _translate("mapbioPorter", "Create GeoJSON & Shapefile Archive", None))
        self.cbTransferAction.setItemText(3, _translate("mapbioPorter", "Download New Interviews", None))
        self.cbTransferAction.setItemText(4, _translate("mapbioPorter", "Upload Completed Interviews", None))
        self.lblUserName.setText(_translate("mapbioPorter", "User Name:", None))
        self.lblPassword.setText(_translate("mapbioPorter", "Password: ", None))
        self.lblURL.setText(_translate("mapbioPorter", "Heritage URL:", None))
        self.leURL.setText(_translate("mapbioPorter", "https://louistoolkit.ca", None))
        self.lblProject.setText(_translate("mapbioPorter", "Select Heritage Destination Project", None))
        self.pbImport.setText(_translate("mapbioPorter", "Import", None))
        self.pbUpload.setText(_translate("mapbioPorter", "Upload", None))
        self.lblAllProgress.setText(_translate("mapbioPorter", "Overall Progress:", None))
        self.lblStepProgress.setText(_translate("mapbioPorter", "Current Step:", None))
        self.pbTransfer.setText(_translate("mapbioPorter", "Transfer Data", None))
        self.pbCancel.setText(_translate("mapbioPorter", "Cancel", None))
        self.pbClose.setText(_translate("mapbioPorter", "Close", None))

