# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_manager.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapbioManager(object):
    def setupUi(self, mapbioManager):
        mapbioManager.setObjectName(_fromUtf8("mapbioManager"))
        mapbioManager.resize(788, 711)
        self.gridLayout_14 = QtGui.QGridLayout(mapbioManager)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.twMapBioSettings = QtGui.QTabWidget(mapbioManager)
        self.twMapBioSettings.setObjectName(_fromUtf8("twMapBioSettings"))
        self.tbSettings = QtGui.QWidget()
        self.tbSettings.setObjectName(_fromUtf8("tbSettings"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tbSettings)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.glMapBioSettings = QtGui.QGridLayout()
        self.glMapBioSettings.setObjectName(_fromUtf8("glMapBioSettings"))
        self.hlProjectDir = QtGui.QHBoxLayout()
        self.hlProjectDir.setObjectName(_fromUtf8("hlProjectDir"))
        self.leProjectDir = QtGui.QLineEdit(self.tbSettings)
        self.leProjectDir.setEnabled(True)
        self.leProjectDir.setReadOnly(True)
        self.leProjectDir.setObjectName(_fromUtf8("leProjectDir"))
        self.hlProjectDir.addWidget(self.leProjectDir)
        self.tbSelectProjectDir = QtGui.QToolButton(self.tbSettings)
        self.tbSelectProjectDir.setObjectName(_fromUtf8("tbSelectProjectDir"))
        self.hlProjectDir.addWidget(self.tbSelectProjectDir)
        self.glMapBioSettings.addLayout(self.hlProjectDir, 0, 1, 1, 1)
        self.cbCurrentProject = QtGui.QComboBox(self.tbSettings)
        self.cbCurrentProject.setObjectName(_fromUtf8("cbCurrentProject"))
        self.glMapBioSettings.addWidget(self.cbCurrentProject, 1, 1, 1, 1)
        self.lblCurrentProject = QtGui.QLabel(self.tbSettings)
        self.lblCurrentProject.setObjectName(_fromUtf8("lblCurrentProject"))
        self.glMapBioSettings.addWidget(self.lblCurrentProject, 1, 0, 1, 1)
        self.lblProjectsDir = QtGui.QLabel(self.tbSettings)
        self.lblProjectsDir.setObjectName(_fromUtf8("lblProjectsDir"))
        self.glMapBioSettings.addWidget(self.lblProjectsDir, 0, 0, 1, 1)
        self.lblOggEnc = QtGui.QLabel(self.tbSettings)
        self.lblOggEnc.setObjectName(_fromUtf8("lblOggEnc"))
        self.glMapBioSettings.addWidget(self.lblOggEnc, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.leOggEnc = QtGui.QLineEdit(self.tbSettings)
        self.leOggEnc.setObjectName(_fromUtf8("leOggEnc"))
        self.horizontalLayout_2.addWidget(self.leOggEnc)
        self.tbOggEnc = QtGui.QToolButton(self.tbSettings)
        self.tbOggEnc.setObjectName(_fromUtf8("tbOggEnc"))
        self.horizontalLayout_2.addWidget(self.tbOggEnc)
        self.glMapBioSettings.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.glMapBioSettings, 0, 0, 1, 1)
        self.hlSettingsButtons = QtGui.QHBoxLayout()
        self.hlSettingsButtons.setObjectName(_fromUtf8("hlSettingsButtons"))
        self.pbSaveSettings = QtGui.QPushButton(self.tbSettings)
        self.pbSaveSettings.setObjectName(_fromUtf8("pbSaveSettings"))
        self.hlSettingsButtons.addWidget(self.pbSaveSettings)
        self.pbCancelSettings = QtGui.QPushButton(self.tbSettings)
        self.pbCancelSettings.setObjectName(_fromUtf8("pbCancelSettings"))
        self.hlSettingsButtons.addWidget(self.pbCancelSettings)
        self.pbDeleteProject = QtGui.QPushButton(self.tbSettings)
        self.pbDeleteProject.setEnabled(False)
        self.pbDeleteProject.setObjectName(_fromUtf8("pbDeleteProject"))
        self.hlSettingsButtons.addWidget(self.pbDeleteProject)
        self.pbTransfer = QtGui.QPushButton(self.tbSettings)
        self.pbTransfer.setObjectName(_fromUtf8("pbTransfer"))
        self.hlSettingsButtons.addWidget(self.pbTransfer)
        self.pbSystemTest = QtGui.QPushButton(self.tbSettings)
        self.pbSystemTest.setObjectName(_fromUtf8("pbSystemTest"))
        self.hlSettingsButtons.addWidget(self.pbSystemTest)
        self.gridLayout_3.addLayout(self.hlSettingsButtons, 1, 0, 1, 1)
        self.lnBelowLMBSettings = QtGui.QFrame(self.tbSettings)
        self.lnBelowLMBSettings.setFrameShape(QtGui.QFrame.HLine)
        self.lnBelowLMBSettings.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnBelowLMBSettings.setObjectName(_fromUtf8("lnBelowLMBSettings"))
        self.gridLayout_3.addWidget(self.lnBelowLMBSettings, 2, 0, 1, 1)
        self.lblProjectMapSettings = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProjectMapSettings.setFont(font)
        self.lblProjectMapSettings.setObjectName(_fromUtf8("lblProjectMapSettings"))
        self.gridLayout_3.addWidget(self.lblProjectMapSettings, 3, 0, 1, 1)
        self.frProjectMapSettings = QtGui.QFrame(self.tbSettings)
        self.frProjectMapSettings.setObjectName(_fromUtf8("frProjectMapSettings"))
        self.flQGISSettings = QtGui.QFormLayout(self.frProjectMapSettings)
        self.flQGISSettings.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flQGISSettings.setMargin(0)
        self.flQGISSettings.setObjectName(_fromUtf8("flQGISSettings"))
        self.lblQgsProject = QtGui.QLabel(self.frProjectMapSettings)
        self.lblQgsProject.setObjectName(_fromUtf8("lblQgsProject"))
        self.flQGISSettings.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblQgsProject)
        self.hlQgsProject = QtGui.QHBoxLayout()
        self.hlQgsProject.setObjectName(_fromUtf8("hlQgsProject"))
        self.leQgsProject = QtGui.QLineEdit(self.frProjectMapSettings)
        self.leQgsProject.setEnabled(True)
        self.leQgsProject.setReadOnly(True)
        self.leQgsProject.setObjectName(_fromUtf8("leQgsProject"))
        self.hlQgsProject.addWidget(self.leQgsProject)
        self.tbSelectQgsProject = QtGui.QToolButton(self.frProjectMapSettings)
        self.tbSelectQgsProject.setObjectName(_fromUtf8("tbSelectQgsProject"))
        self.hlQgsProject.addWidget(self.tbSelectQgsProject)
        self.flQGISSettings.setLayout(3, QtGui.QFormLayout.FieldRole, self.hlQgsProject)
        self.lblBaseLayerGroups = QtGui.QLabel(self.frProjectMapSettings)
        self.lblBaseLayerGroups.setMinimumSize(QtCore.QSize(176, 0))
        self.lblBaseLayerGroups.setObjectName(_fromUtf8("lblBaseLayerGroups"))
        self.flQGISSettings.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblBaseLayerGroups)
        self.hlBaseLayers = QtGui.QHBoxLayout()
        self.hlBaseLayers.setObjectName(_fromUtf8("hlBaseLayers"))
        self.tblBaseGroups = QtGui.QTableWidget(self.frProjectMapSettings)
        self.tblBaseGroups.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblBaseGroups.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblBaseGroups.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblBaseGroups.setObjectName(_fromUtf8("tblBaseGroups"))
        self.tblBaseGroups.setColumnCount(0)
        self.tblBaseGroups.setRowCount(0)
        self.hlBaseLayers.addWidget(self.tblBaseGroups)
        self.vlBaseGroupActions = QtGui.QVBoxLayout()
        self.vlBaseGroupActions.setObjectName(_fromUtf8("vlBaseGroupActions"))
        self.lblBaseGroupOptions = QtGui.QLabel(self.frProjectMapSettings)
        self.lblBaseGroupOptions.setMinimumSize(QtCore.QSize(200, 0))
        self.lblBaseGroupOptions.setObjectName(_fromUtf8("lblBaseGroupOptions"))
        self.vlBaseGroupActions.addWidget(self.lblBaseGroupOptions)
        self.cbProjectGroups = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbProjectGroups.setObjectName(_fromUtf8("cbProjectGroups"))
        self.vlBaseGroupActions.addWidget(self.cbProjectGroups)
        self.hlBaseGroups = QtGui.QHBoxLayout()
        self.hlBaseGroups.setObjectName(_fromUtf8("hlBaseGroups"))
        self.pbAddBaseGroup = QtGui.QPushButton(self.frProjectMapSettings)
        self.pbAddBaseGroup.setObjectName(_fromUtf8("pbAddBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbAddBaseGroup)
        self.pbRemoveBaseGroup = QtGui.QPushButton(self.frProjectMapSettings)
        self.pbRemoveBaseGroup.setEnabled(False)
        self.pbRemoveBaseGroup.setObjectName(_fromUtf8("pbRemoveBaseGroup"))
        self.hlBaseGroups.addWidget(self.pbRemoveBaseGroup)
        self.vlBaseGroupActions.addLayout(self.hlBaseGroups)
        self.hlBaseLayers.addLayout(self.vlBaseGroupActions)
        self.flQGISSettings.setLayout(4, QtGui.QFormLayout.FieldRole, self.hlBaseLayers)
        self.lblMaxScale = QtGui.QLabel(self.frProjectMapSettings)
        self.lblMaxScale.setObjectName(_fromUtf8("lblMaxScale"))
        self.flQGISSettings.setWidget(8, QtGui.QFormLayout.LabelRole, self.lblMaxScale)
        self.cbMaxScale = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbMaxScale.setObjectName(_fromUtf8("cbMaxScale"))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.cbMaxScale.addItem(_fromUtf8(""))
        self.flQGISSettings.setWidget(8, QtGui.QFormLayout.FieldRole, self.cbMaxScale)
        self.lblMinScale = QtGui.QLabel(self.frProjectMapSettings)
        self.lblMinScale.setObjectName(_fromUtf8("lblMinScale"))
        self.flQGISSettings.setWidget(9, QtGui.QFormLayout.LabelRole, self.lblMinScale)
        self.cbMinScale = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbMinScale.setObjectName(_fromUtf8("cbMinScale"))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.cbMinScale.addItem(_fromUtf8(""))
        self.flQGISSettings.setWidget(9, QtGui.QFormLayout.FieldRole, self.cbMinScale)
        self.lblZoomNotices = QtGui.QLabel(self.frProjectMapSettings)
        self.lblZoomNotices.setObjectName(_fromUtf8("lblZoomNotices"))
        self.flQGISSettings.setWidget(10, QtGui.QFormLayout.LabelRole, self.lblZoomNotices)
        self.cbZoomRangeNotices = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbZoomRangeNotices.setObjectName(_fromUtf8("cbZoomRangeNotices"))
        self.cbZoomRangeNotices.addItem(_fromUtf8(""))
        self.cbZoomRangeNotices.addItem(_fromUtf8(""))
        self.flQGISSettings.setWidget(10, QtGui.QFormLayout.FieldRole, self.cbZoomRangeNotices)
        self.lblProjectBoundary = QtGui.QLabel(self.frProjectMapSettings)
        self.lblProjectBoundary.setObjectName(_fromUtf8("lblProjectBoundary"))
        self.flQGISSettings.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblProjectBoundary)
        self.lblEnableReference = QtGui.QLabel(self.frProjectMapSettings)
        self.lblEnableReference.setObjectName(_fromUtf8("lblEnableReference"))
        self.flQGISSettings.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblEnableReference)
        self.lblReferenceLayer = QtGui.QLabel(self.frProjectMapSettings)
        self.lblReferenceLayer.setObjectName(_fromUtf8("lblReferenceLayer"))
        self.flQGISSettings.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblReferenceLayer)
        self.cbBoundaryLayer = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbBoundaryLayer.setObjectName(_fromUtf8("cbBoundaryLayer"))
        self.flQGISSettings.setWidget(5, QtGui.QFormLayout.FieldRole, self.cbBoundaryLayer)
        self.cbEnableReference = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbEnableReference.setObjectName(_fromUtf8("cbEnableReference"))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.cbEnableReference.addItem(_fromUtf8(""))
        self.flQGISSettings.setWidget(6, QtGui.QFormLayout.FieldRole, self.cbEnableReference)
        self.cbReferenceLayer = QtGui.QComboBox(self.frProjectMapSettings)
        self.cbReferenceLayer.setObjectName(_fromUtf8("cbReferenceLayer"))
        self.flQGISSettings.setWidget(7, QtGui.QFormLayout.FieldRole, self.cbReferenceLayer)
        self.gridLayout_3.addWidget(self.frProjectMapSettings, 4, 0, 1, 1)
        self.hlnSettingsAboveButtons = QtGui.QFrame(self.tbSettings)
        self.hlnSettingsAboveButtons.setFrameShape(QtGui.QFrame.HLine)
        self.hlnSettingsAboveButtons.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlnSettingsAboveButtons.setObjectName(_fromUtf8("hlnSettingsAboveButtons"))
        self.gridLayout_3.addWidget(self.hlnSettingsAboveButtons, 5, 0, 1, 1)
        self.hlLMBProjectDefaults = QtGui.QHBoxLayout()
        self.hlLMBProjectDefaults.setObjectName(_fromUtf8("hlLMBProjectDefaults"))
        self.pbSaveProjectMapSettings = QtGui.QPushButton(self.tbSettings)
        self.pbSaveProjectMapSettings.setObjectName(_fromUtf8("pbSaveProjectMapSettings"))
        self.hlLMBProjectDefaults.addWidget(self.pbSaveProjectMapSettings)
        self.pbCancelProjectMapSettings = QtGui.QPushButton(self.tbSettings)
        self.pbCancelProjectMapSettings.setObjectName(_fromUtf8("pbCancelProjectMapSettings"))
        self.hlLMBProjectDefaults.addWidget(self.pbCancelProjectMapSettings)
        self.gridLayout_3.addLayout(self.hlLMBProjectDefaults, 6, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbSettings, _fromUtf8(""))
        self.tbProjectDetails = QtGui.QWidget()
        self.tbProjectDetails.setObjectName(_fromUtf8("tbProjectDetails"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tbProjectDetails)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.frContentCode = QtGui.QFrame(self.tbProjectDetails)
        self.frContentCode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frContentCode.setFrameShadow(QtGui.QFrame.Plain)
        self.frContentCode.setObjectName(_fromUtf8("frContentCode"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frContentCode)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vlProjectDetails = QtGui.QVBoxLayout()
        self.vlProjectDetails.setSpacing(2)
        self.vlProjectDetails.setObjectName(_fromUtf8("vlProjectDetails"))
        self.lblProjCode = QtGui.QLabel(self.frContentCode)
        self.lblProjCode.setObjectName(_fromUtf8("lblProjCode"))
        self.vlProjectDetails.addWidget(self.lblProjCode)
        self.leProjectCode = QtGui.QLineEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectCode.sizePolicy().hasHeightForWidth())
        self.leProjectCode.setSizePolicy(sizePolicy)
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.vlProjectDetails.addWidget(self.leProjectCode)
        self.lblProjDescription = QtGui.QLabel(self.frContentCode)
        self.lblProjDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjDescription.setObjectName(_fromUtf8("lblProjDescription"))
        self.vlProjectDetails.addWidget(self.lblProjDescription)
        self.pteProjectDescription = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteProjectDescription.sizePolicy().hasHeightForWidth())
        self.pteProjectDescription.setSizePolicy(sizePolicy)
        self.pteProjectDescription.setMinimumSize(QtCore.QSize(0, 50))
        self.pteProjectDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteProjectDescription.setObjectName(_fromUtf8("pteProjectDescription"))
        self.vlProjectDetails.addWidget(self.pteProjectDescription)
        self.cbUseHeritage = QtGui.QCheckBox(self.frContentCode)
        self.cbUseHeritage.setObjectName(_fromUtf8("cbUseHeritage"))
        self.vlProjectDetails.addWidget(self.cbUseHeritage)
        self.lblProjOther = QtGui.QLabel(self.frContentCode)
        self.lblProjOther.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblProjOther.setObjectName(_fromUtf8("lblProjOther"))
        self.vlProjectDetails.addWidget(self.lblProjOther)
        self.pteProjectOther = QtGui.QPlainTextEdit(self.frContentCode)
        self.pteProjectOther.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteProjectOther.sizePolicy().hasHeightForWidth())
        self.pteProjectOther.setSizePolicy(sizePolicy)
        self.pteProjectOther.setMinimumSize(QtCore.QSize(0, 100))
        self.pteProjectOther.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pteProjectOther.setAutoFillBackground(False)
        self.pteProjectOther.setReadOnly(True)
        self.pteProjectOther.setBackgroundVisible(False)
        self.pteProjectOther.setObjectName(_fromUtf8("pteProjectOther"))
        self.vlProjectDetails.addWidget(self.pteProjectOther)
        self.lblCustomFields = QtGui.QLabel(self.frContentCode)
        self.lblCustomFields.setObjectName(_fromUtf8("lblCustomFields"))
        self.vlProjectDetails.addWidget(self.lblCustomFields)
        self.pteCustomFields = QtGui.QPlainTextEdit(self.frContentCode)
        self.pteCustomFields.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteCustomFields.sizePolicy().hasHeightForWidth())
        self.pteCustomFields.setSizePolicy(sizePolicy)
        self.pteCustomFields.setMinimumSize(QtCore.QSize(0, 50))
        self.pteCustomFields.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteCustomFields.setAutoFillBackground(False)
        self.pteCustomFields.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pteCustomFields.setReadOnly(True)
        self.pteCustomFields.setBackgroundVisible(False)
        self.pteCustomFields.setObjectName(_fromUtf8("pteCustomFields"))
        self.vlProjectDetails.addWidget(self.pteCustomFields)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblDateAndTime = QtGui.QLabel(self.frContentCode)
        self.lblDateAndTime.setObjectName(_fromUtf8("lblDateAndTime"))
        self.horizontalLayout_4.addWidget(self.lblDateAndTime)
        self.cbUsePeriod = QtGui.QCheckBox(self.frContentCode)
        self.cbUsePeriod.setObjectName(_fromUtf8("cbUsePeriod"))
        self.horizontalLayout_4.addWidget(self.cbUsePeriod)
        self.vlProjectDetails.addLayout(self.horizontalLayout_4)
        self.pteDateAndTime = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteDateAndTime.sizePolicy().hasHeightForWidth())
        self.pteDateAndTime.setSizePolicy(sizePolicy)
        self.pteDateAndTime.setMinimumSize(QtCore.QSize(0, 75))
        self.pteDateAndTime.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteDateAndTime.setObjectName(_fromUtf8("pteDateAndTime"))
        self.vlProjectDetails.addWidget(self.pteDateAndTime)
        self.gridLayout_2.addLayout(self.vlProjectDetails, 0, 0, 1, 1)
        self.vlContentCoding = QtGui.QVBoxLayout()
        self.vlContentCoding.setSpacing(2)
        self.vlContentCoding.setObjectName(_fromUtf8("vlContentCoding"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblTimeOfYear = QtGui.QLabel(self.frContentCode)
        self.lblTimeOfYear.setObjectName(_fromUtf8("lblTimeOfYear"))
        self.horizontalLayout_5.addWidget(self.lblTimeOfYear)
        self.cbTimeOfYear = QtGui.QCheckBox(self.frContentCode)
        self.cbTimeOfYear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbTimeOfYear.setObjectName(_fromUtf8("cbTimeOfYear"))
        self.horizontalLayout_5.addWidget(self.cbTimeOfYear)
        self.vlContentCoding.addLayout(self.horizontalLayout_5)
        self.pteTimeOfYear = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteTimeOfYear.sizePolicy().hasHeightForWidth())
        self.pteTimeOfYear.setSizePolicy(sizePolicy)
        self.pteTimeOfYear.setMinimumSize(QtCore.QSize(0, 75))
        self.pteTimeOfYear.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteTimeOfYear.setObjectName(_fromUtf8("pteTimeOfYear"))
        self.vlContentCoding.addWidget(self.pteTimeOfYear)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblContentCodes = QtGui.QLabel(self.frContentCode)
        self.lblContentCodes.setObjectName(_fromUtf8("lblContentCodes"))
        self.horizontalLayout_3.addWidget(self.lblContentCodes)
        self.tbSortCodes = QtGui.QToolButton(self.frContentCode)
        self.tbSortCodes.setObjectName(_fromUtf8("tbSortCodes"))
        self.horizontalLayout_3.addWidget(self.tbSortCodes)
        self.vlContentCoding.addLayout(self.horizontalLayout_3)
        self.pteContentCodes = QtGui.QPlainTextEdit(self.frContentCode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteContentCodes.sizePolicy().hasHeightForWidth())
        self.pteContentCodes.setSizePolicy(sizePolicy)
        self.pteContentCodes.setMinimumSize(QtCore.QSize(0, 250))
        self.pteContentCodes.setMaximumSize(QtCore.QSize(16777215, 500))
        self.pteContentCodes.setObjectName(_fromUtf8("pteContentCodes"))
        self.vlContentCoding.addWidget(self.pteContentCodes)
        self.lblDefaultCodes = QtGui.QLabel(self.frContentCode)
        self.lblDefaultCodes.setObjectName(_fromUtf8("lblDefaultCodes"))
        self.vlContentCoding.addWidget(self.lblDefaultCodes)
        self.glContentCodes = QtGui.QGridLayout()
        self.glContentCodes.setObjectName(_fromUtf8("glContentCodes"))
        self.lblDefaultCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultCode.setObjectName(_fromUtf8("lblDefaultCode"))
        self.glContentCodes.addWidget(self.lblDefaultCode, 0, 0, 1, 1)
        self.lblDefaultPointCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultPointCode.setObjectName(_fromUtf8("lblDefaultPointCode"))
        self.glContentCodes.addWidget(self.lblDefaultPointCode, 1, 0, 1, 1)
        self.cbDefaultCode = QtGui.QComboBox(self.frContentCode)
        self.cbDefaultCode.setObjectName(_fromUtf8("cbDefaultCode"))
        self.glContentCodes.addWidget(self.cbDefaultCode, 0, 1, 1, 1)
        self.cbPointCode = QtGui.QComboBox(self.frContentCode)
        self.cbPointCode.setObjectName(_fromUtf8("cbPointCode"))
        self.glContentCodes.addWidget(self.cbPointCode, 1, 1, 1, 1)
        self.lblDefaultLineCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultLineCode.setObjectName(_fromUtf8("lblDefaultLineCode"))
        self.glContentCodes.addWidget(self.lblDefaultLineCode, 0, 2, 1, 1)
        self.cbLineCode = QtGui.QComboBox(self.frContentCode)
        self.cbLineCode.setObjectName(_fromUtf8("cbLineCode"))
        self.glContentCodes.addWidget(self.cbLineCode, 0, 3, 1, 1)
        self.lblDefaultPolygonCode = QtGui.QLabel(self.frContentCode)
        self.lblDefaultPolygonCode.setObjectName(_fromUtf8("lblDefaultPolygonCode"))
        self.glContentCodes.addWidget(self.lblDefaultPolygonCode, 1, 2, 1, 1)
        self.cbPolygonCode = QtGui.QComboBox(self.frContentCode)
        self.cbPolygonCode.setObjectName(_fromUtf8("cbPolygonCode"))
        self.glContentCodes.addWidget(self.cbPolygonCode, 1, 3, 1, 1)
        self.vlContentCoding.addLayout(self.glContentCodes)
        self.gridLayout_2.addLayout(self.vlContentCoding, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frContentCode, 0, 0, 1, 1)
        self.hlProjectButtons = QtGui.QHBoxLayout()
        self.hlProjectButtons.setObjectName(_fromUtf8("hlProjectButtons"))
        self.pbProjectDetailsSave = QtGui.QPushButton(self.tbProjectDetails)
        self.pbProjectDetailsSave.setObjectName(_fromUtf8("pbProjectDetailsSave"))
        self.hlProjectButtons.addWidget(self.pbProjectDetailsSave)
        self.pbProjectDetailsCancel = QtGui.QPushButton(self.tbProjectDetails)
        self.pbProjectDetailsCancel.setEnabled(True)
        self.pbProjectDetailsCancel.setObjectName(_fromUtf8("pbProjectDetailsCancel"))
        self.hlProjectButtons.addWidget(self.pbProjectDetailsCancel)
        self.gridLayout_15.addLayout(self.hlProjectButtons, 1, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbProjectDetails, _fromUtf8(""))
        self.tbPeople = QtGui.QWidget()
        self.tbPeople.setObjectName(_fromUtf8("tbPeople"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tbPeople)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblParticipants = QtGui.QLabel(self.tbPeople)
        self.lblParticipants.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.verticalLayout_2.addWidget(self.lblParticipants)
        self.tblParticipants = QtGui.QTableWidget(self.tbPeople)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblParticipants.sizePolicy().hasHeightForWidth())
        self.tblParticipants.setSizePolicy(sizePolicy)
        self.tblParticipants.setMinimumSize(QtCore.QSize(0, 100))
        self.tblParticipants.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tblParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblParticipants.setTabKeyNavigation(False)
        self.tblParticipants.setProperty("showDropIndicator", False)
        self.tblParticipants.setDragDropOverwriteMode(False)
        self.tblParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblParticipants.setObjectName(_fromUtf8("tblParticipants"))
        self.tblParticipants.setColumnCount(0)
        self.tblParticipants.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tblParticipants)
        self.frPeopleControls = QtGui.QFrame(self.tbPeople)
        self.frPeopleControls.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frPeopleControls.setObjectName(_fromUtf8("frPeopleControls"))
        self.hzParticipantList = QtGui.QHBoxLayout(self.frPeopleControls)
        self.hzParticipantList.setObjectName(_fromUtf8("hzParticipantList"))
        self.pbParticipantNew = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantNew.setObjectName(_fromUtf8("pbParticipantNew"))
        self.hzParticipantList.addWidget(self.pbParticipantNew)
        self.pbParticipantSave = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantSave.setEnabled(False)
        self.pbParticipantSave.setObjectName(_fromUtf8("pbParticipantSave"))
        self.hzParticipantList.addWidget(self.pbParticipantSave)
        self.pbParticipantCancel = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantCancel.setEnabled(False)
        self.pbParticipantCancel.setObjectName(_fromUtf8("pbParticipantCancel"))
        self.hzParticipantList.addWidget(self.pbParticipantCancel)
        self.pbParticipantDelete = QtGui.QPushButton(self.frPeopleControls)
        self.pbParticipantDelete.setEnabled(False)
        self.pbParticipantDelete.setObjectName(_fromUtf8("pbParticipantDelete"))
        self.hzParticipantList.addWidget(self.pbParticipantDelete)
        self.verticalLayout_2.addWidget(self.frPeopleControls)
        self.gridLayout_13.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tbxParticipants = QtGui.QToolBox(self.tbPeople)
        self.tbxParticipants.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbxParticipants.sizePolicy().hasHeightForWidth())
        self.tbxParticipants.setSizePolicy(sizePolicy)
        self.tbxParticipants.setMinimumSize(QtCore.QSize(440, 365))
        self.tbxParticipants.setObjectName(_fromUtf8("tbxParticipants"))
        self.pgBasicInfo = QtGui.QWidget()
        self.pgBasicInfo.setGeometry(QtCore.QRect(0, 0, 440, 516))
        self.pgBasicInfo.setObjectName(_fromUtf8("pgBasicInfo"))
        self.gridLayout_12 = QtGui.QGridLayout(self.pgBasicInfo)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.glParticipants = QtGui.QGridLayout()
        self.glParticipants.setObjectName(_fromUtf8("glParticipants"))
        self.leParticipantCode = QtGui.QLineEdit(self.pgBasicInfo)
        self.leParticipantCode.setObjectName(_fromUtf8("leParticipantCode"))
        self.glParticipants.addWidget(self.leParticipantCode, 0, 1, 1, 1)
        self.leEmail = QtGui.QLineEdit(self.pgBasicInfo)
        self.leEmail.setObjectName(_fromUtf8("leEmail"))
        self.glParticipants.addWidget(self.leEmail, 3, 1, 1, 1)
        self.lblEmail = QtGui.QLabel(self.pgBasicInfo)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.glParticipants.addWidget(self.lblEmail, 3, 0, 1, 1)
        self.lblFamilyGroup = QtGui.QLabel(self.pgBasicInfo)
        self.lblFamilyGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFamilyGroup.setObjectName(_fromUtf8("lblFamilyGroup"))
        self.glParticipants.addWidget(self.lblFamilyGroup, 5, 0, 1, 1)
        self.lblFirstName = QtGui.QLabel(self.pgBasicInfo)
        self.lblFirstName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblFirstName.setObjectName(_fromUtf8("lblFirstName"))
        self.glParticipants.addWidget(self.lblFirstName, 1, 0, 1, 1)
        self.lblLastName = QtGui.QLabel(self.pgBasicInfo)
        self.lblLastName.setObjectName(_fromUtf8("lblLastName"))
        self.glParticipants.addWidget(self.lblLastName, 2, 0, 1, 1)
        self.lblParticipantCode = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantCode.setObjectName(_fromUtf8("lblParticipantCode"))
        self.glParticipants.addWidget(self.lblParticipantCode, 0, 0, 1, 1)
        self.lblCommunityName = QtGui.QLabel(self.pgBasicInfo)
        self.lblCommunityName.setObjectName(_fromUtf8("lblCommunityName"))
        self.glParticipants.addWidget(self.lblCommunityName, 4, 0, 1, 1)
        self.leFamily = QtGui.QLineEdit(self.pgBasicInfo)
        self.leFamily.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leFamily.setObjectName(_fromUtf8("leFamily"))
        self.glParticipants.addWidget(self.leFamily, 5, 1, 1, 1)
        self.leMaidenName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leMaidenName.setObjectName(_fromUtf8("leMaidenName"))
        self.glParticipants.addWidget(self.leMaidenName, 6, 1, 1, 1)
        self.lblMaidenName = QtGui.QLabel(self.pgBasicInfo)
        self.lblMaidenName.setObjectName(_fromUtf8("lblMaidenName"))
        self.glParticipants.addWidget(self.lblMaidenName, 6, 0, 1, 1)
        self.leLastName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leLastName.setObjectName(_fromUtf8("leLastName"))
        self.glParticipants.addWidget(self.leLastName, 2, 1, 1, 1)
        self.leFirstName = QtGui.QLineEdit(self.pgBasicInfo)
        self.leFirstName.setObjectName(_fromUtf8("leFirstName"))
        self.glParticipants.addWidget(self.leFirstName, 1, 1, 1, 1)
        self.leCommunity = QtGui.QLineEdit(self.pgBasicInfo)
        self.leCommunity.setObjectName(_fromUtf8("leCommunity"))
        self.glParticipants.addWidget(self.leCommunity, 4, 1, 1, 1)
        self.gridLayout_12.addLayout(self.glParticipants, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblGender = QtGui.QLabel(self.pgBasicInfo)
        self.lblGender.setMinimumSize(QtCore.QSize(107, 0))
        self.lblGender.setObjectName(_fromUtf8("lblGender"))
        self.horizontalLayout.addWidget(self.lblGender)
        self.cbGender = QtGui.QComboBox(self.pgBasicInfo)
        self.cbGender.setObjectName(_fromUtf8("cbGender"))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.cbGender.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbGender)
        self.lblMaritalStatus = QtGui.QLabel(self.pgBasicInfo)
        self.lblMaritalStatus.setObjectName(_fromUtf8("lblMaritalStatus"))
        self.horizontalLayout.addWidget(self.lblMaritalStatus)
        self.cbMaritalStatus = QtGui.QComboBox(self.pgBasicInfo)
        self.cbMaritalStatus.setObjectName(_fromUtf8("cbMaritalStatus"))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.cbMaritalStatus.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbMaritalStatus)
        self.gridLayout_12.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lblParticipantNote = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblParticipantNote.setObjectName(_fromUtf8("lblParticipantNote"))
        self.gridLayout_11.addWidget(self.lblParticipantNote, 2, 0, 1, 1)
        self.lblParticipantTags = QtGui.QLabel(self.pgBasicInfo)
        self.lblParticipantTags.setObjectName(_fromUtf8("lblParticipantTags"))
        self.gridLayout_11.addWidget(self.lblParticipantTags, 1, 0, 1, 1)
        self.lblBirthDate = QtGui.QLabel(self.pgBasicInfo)
        self.lblBirthDate.setMinimumSize(QtCore.QSize(107, 0))
        self.lblBirthDate.setObjectName(_fromUtf8("lblBirthDate"))
        self.gridLayout_11.addWidget(self.lblBirthDate, 0, 0, 1, 1)
        self.pteParticipantNote = QtGui.QPlainTextEdit(self.pgBasicInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteParticipantNote.sizePolicy().hasHeightForWidth())
        self.pteParticipantNote.setSizePolicy(sizePolicy)
        self.pteParticipantNote.setMinimumSize(QtCore.QSize(0, 50))
        self.pteParticipantNote.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pteParticipantNote.setObjectName(_fromUtf8("pteParticipantNote"))
        self.gridLayout_11.addWidget(self.pteParticipantNote, 2, 1, 1, 1)
        self.leParticipantTags = QtGui.QLineEdit(self.pgBasicInfo)
        self.leParticipantTags.setObjectName(_fromUtf8("leParticipantTags"))
        self.gridLayout_11.addWidget(self.leParticipantTags, 1, 1, 1, 1)
        self.leBirthDate = QtGui.QLineEdit(self.pgBasicInfo)
        self.leBirthDate.setObjectName(_fromUtf8("leBirthDate"))
        self.gridLayout_11.addWidget(self.leBirthDate, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 2, 0, 1, 1)
        self.tbxParticipants.addItem(self.pgBasicInfo, _fromUtf8(""))
        self.pgAddresses = QtGui.QWidget()
        self.pgAddresses.setGeometry(QtCore.QRect(0, 0, 222, 170))
        self.pgAddresses.setObjectName(_fromUtf8("pgAddresses"))
        self.gridLayout_9 = QtGui.QGridLayout(self.pgAddresses)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.vlAddressList = QtGui.QVBoxLayout()
        self.vlAddressList.setObjectName(_fromUtf8("vlAddressList"))
        self.tblAddresses = QtGui.QTableWidget(self.pgAddresses)
        self.tblAddresses.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblAddresses.setTabKeyNavigation(False)
        self.tblAddresses.setProperty("showDropIndicator", False)
        self.tblAddresses.setDragDropOverwriteMode(False)
        self.tblAddresses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblAddresses.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAddresses.setObjectName(_fromUtf8("tblAddresses"))
        self.tblAddresses.setColumnCount(0)
        self.tblAddresses.setRowCount(0)
        self.vlAddressList.addWidget(self.tblAddresses)
        self.hlAddressList = QtGui.QHBoxLayout()
        self.hlAddressList.setObjectName(_fromUtf8("hlAddressList"))
        self.pbAddNew = QtGui.QPushButton(self.pgAddresses)
        self.pbAddNew.setObjectName(_fromUtf8("pbAddNew"))
        self.hlAddressList.addWidget(self.pbAddNew)
        self.pbAddSave = QtGui.QPushButton(self.pgAddresses)
        self.pbAddSave.setEnabled(False)
        self.pbAddSave.setObjectName(_fromUtf8("pbAddSave"))
        self.hlAddressList.addWidget(self.pbAddSave)
        self.pbAddCancel = QtGui.QPushButton(self.pgAddresses)
        self.pbAddCancel.setEnabled(False)
        self.pbAddCancel.setObjectName(_fromUtf8("pbAddCancel"))
        self.hlAddressList.addWidget(self.pbAddCancel)
        self.pbAddDelete = QtGui.QPushButton(self.pgAddresses)
        self.pbAddDelete.setEnabled(False)
        self.pbAddDelete.setObjectName(_fromUtf8("pbAddDelete"))
        self.hlAddressList.addWidget(self.pbAddDelete)
        self.vlAddressList.addLayout(self.hlAddressList)
        self.gridLayout_9.addLayout(self.vlAddressList, 0, 0, 1, 1)
        self.grAddresses = QtGui.QGridLayout()
        self.grAddresses.setObjectName(_fromUtf8("grAddresses"))
        self.lblAddress = QtGui.QLabel(self.pgAddresses)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.grAddresses.addWidget(self.lblAddress, 1, 0, 1, 1)
        self.lblAddType = QtGui.QLabel(self.pgAddresses)
        self.lblAddType.setObjectName(_fromUtf8("lblAddType"))
        self.grAddresses.addWidget(self.lblAddType, 0, 0, 1, 1)
        self.pteAddress = QtGui.QPlainTextEdit(self.pgAddresses)
        self.pteAddress.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pteAddress.setObjectName(_fromUtf8("pteAddress"))
        self.grAddresses.addWidget(self.pteAddress, 1, 1, 1, 1)
        self.cbAddType = QtGui.QComboBox(self.pgAddresses)
        self.cbAddType.setObjectName(_fromUtf8("cbAddType"))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.cbAddType.addItem(_fromUtf8(""))
        self.grAddresses.addWidget(self.cbAddType, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.grAddresses, 1, 0, 1, 1)
        self.tbxParticipants.addItem(self.pgAddresses, _fromUtf8(""))
        self.pgTelecoms = QtGui.QWidget()
        self.pgTelecoms.setGeometry(QtCore.QRect(0, 0, 222, 153))
        self.pgTelecoms.setObjectName(_fromUtf8("pgTelecoms"))
        self.gridLayout_10 = QtGui.QGridLayout(self.pgTelecoms)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.vlTelecomList = QtGui.QVBoxLayout()
        self.vlTelecomList.setObjectName(_fromUtf8("vlTelecomList"))
        self.tblTelecoms = QtGui.QTableWidget(self.pgTelecoms)
        self.tblTelecoms.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblTelecoms.setTabKeyNavigation(False)
        self.tblTelecoms.setProperty("showDropIndicator", False)
        self.tblTelecoms.setDragDropOverwriteMode(False)
        self.tblTelecoms.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblTelecoms.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblTelecoms.setObjectName(_fromUtf8("tblTelecoms"))
        self.tblTelecoms.setColumnCount(0)
        self.tblTelecoms.setRowCount(0)
        self.vlTelecomList.addWidget(self.tblTelecoms)
        self.hlTelecomList = QtGui.QHBoxLayout()
        self.hlTelecomList.setObjectName(_fromUtf8("hlTelecomList"))
        self.pbTelNew = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelNew.setObjectName(_fromUtf8("pbTelNew"))
        self.hlTelecomList.addWidget(self.pbTelNew)
        self.pbTelSave = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelSave.setEnabled(False)
        self.pbTelSave.setObjectName(_fromUtf8("pbTelSave"))
        self.hlTelecomList.addWidget(self.pbTelSave)
        self.pbTelCancel = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelCancel.setEnabled(False)
        self.pbTelCancel.setObjectName(_fromUtf8("pbTelCancel"))
        self.hlTelecomList.addWidget(self.pbTelCancel)
        self.pbTelDelete = QtGui.QPushButton(self.pgTelecoms)
        self.pbTelDelete.setEnabled(False)
        self.pbTelDelete.setObjectName(_fromUtf8("pbTelDelete"))
        self.hlTelecomList.addWidget(self.pbTelDelete)
        self.vlTelecomList.addLayout(self.hlTelecomList)
        self.gridLayout_10.addLayout(self.vlTelecomList, 0, 0, 1, 1)
        self.glTelecoms = QtGui.QGridLayout()
        self.glTelecoms.setObjectName(_fromUtf8("glTelecoms"))
        self.lblTelType = QtGui.QLabel(self.pgTelecoms)
        self.lblTelType.setObjectName(_fromUtf8("lblTelType"))
        self.glTelecoms.addWidget(self.lblTelType, 0, 0, 1, 1)
        self.lblTelecom = QtGui.QLabel(self.pgTelecoms)
        self.lblTelecom.setObjectName(_fromUtf8("lblTelecom"))
        self.glTelecoms.addWidget(self.lblTelecom, 1, 0, 1, 1)
        self.leTelNumber = QtGui.QLineEdit(self.pgTelecoms)
        self.leTelNumber.setObjectName(_fromUtf8("leTelNumber"))
        self.glTelecoms.addWidget(self.leTelNumber, 1, 1, 1, 1)
        self.cbTelType = QtGui.QComboBox(self.pgTelecoms)
        self.cbTelType.setObjectName(_fromUtf8("cbTelType"))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.cbTelType.addItem(_fromUtf8(""))
        self.glTelecoms.addWidget(self.cbTelType, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.glTelecoms, 1, 0, 1, 1)
        self.tbxParticipants.addItem(self.pgTelecoms, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tbxParticipants, 0, 1, 1, 1)
        self.twMapBioSettings.addTab(self.tbPeople, _fromUtf8(""))
        self.tbInterviews = QtGui.QWidget()
        self.tbInterviews.setObjectName(_fromUtf8("tbInterviews"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tbInterviews)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblInterviews = QtGui.QLabel(self.tbInterviews)
        self.lblInterviews.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lblInterviews.setObjectName(_fromUtf8("lblInterviews"))
        self.verticalLayout.addWidget(self.lblInterviews)
        self.tblInterviews = QtGui.QTableWidget(self.tbInterviews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblInterviews.sizePolicy().hasHeightForWidth())
        self.tblInterviews.setSizePolicy(sizePolicy)
        self.tblInterviews.setMinimumSize(QtCore.QSize(0, 100))
        self.tblInterviews.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tblInterviews.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviews.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviews.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviews.setObjectName(_fromUtf8("tblInterviews"))
        self.tblInterviews.setColumnCount(0)
        self.tblInterviews.setRowCount(0)
        self.verticalLayout.addWidget(self.tblInterviews)
        self.frInterviewControls = QtGui.QFrame(self.tbInterviews)
        self.frInterviewControls.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frInterviewControls.setObjectName(_fromUtf8("frInterviewControls"))
        self.hlInterviewList = QtGui.QHBoxLayout(self.frInterviewControls)
        self.hlInterviewList.setObjectName(_fromUtf8("hlInterviewList"))
        self.pbIntNew = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntNew.setObjectName(_fromUtf8("pbIntNew"))
        self.hlInterviewList.addWidget(self.pbIntNew)
        self.pbIntCopy = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntCopy.setObjectName(_fromUtf8("pbIntCopy"))
        self.hlInterviewList.addWidget(self.pbIntCopy)
        self.pbIntSave = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntSave.setEnabled(False)
        self.pbIntSave.setObjectName(_fromUtf8("pbIntSave"))
        self.hlInterviewList.addWidget(self.pbIntSave)
        self.pbIntCancel = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntCancel.setEnabled(False)
        self.pbIntCancel.setObjectName(_fromUtf8("pbIntCancel"))
        self.hlInterviewList.addWidget(self.pbIntCancel)
        self.pbIntDelete = QtGui.QPushButton(self.frInterviewControls)
        self.pbIntDelete.setEnabled(False)
        self.pbIntDelete.setObjectName(_fromUtf8("pbIntDelete"))
        self.hlInterviewList.addWidget(self.pbIntDelete)
        self.verticalLayout.addWidget(self.frInterviewControls)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tbxInterview = QtGui.QToolBox(self.tbInterviews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbxInterview.sizePolicy().hasHeightForWidth())
        self.tbxInterview.setSizePolicy(sizePolicy)
        self.tbxInterview.setMinimumSize(QtCore.QSize(440, 315))
        self.tbxInterview.setObjectName(_fromUtf8("tbxInterview"))
        self.pgIntBasic = QtGui.QWidget()
        self.pgIntBasic.setGeometry(QtCore.QRect(0, 0, 440, 516))
        self.pgIntBasic.setObjectName(_fromUtf8("pgIntBasic"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pgIntBasic)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.glInterview = QtGui.QGridLayout()
        self.glInterview.setHorizontalSpacing(6)
        self.glInterview.setVerticalSpacing(2)
        self.glInterview.setObjectName(_fromUtf8("glInterview"))
        self.lblStartDateTime = QtGui.QLabel(self.pgIntBasic)
        self.lblStartDateTime.setMaximumSize(QtCore.QSize(16777215, 33))
        self.lblStartDateTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStartDateTime.setObjectName(_fromUtf8("lblStartDateTime"))
        self.glInterview.addWidget(self.lblStartDateTime, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.dteStart = QtGui.QDateTimeEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteStart.sizePolicy().hasHeightForWidth())
        self.dteStart.setSizePolicy(sizePolicy)
        self.dteStart.setMinimumSize(QtCore.QSize(50, 0))
        self.dteStart.setObjectName(_fromUtf8("dteStart"))
        self.horizontalLayout_6.addWidget(self.dteStart)
        self.tbUDStart = QtGui.QToolButton(self.pgIntBasic)
        self.tbUDStart.setObjectName(_fromUtf8("tbUDStart"))
        self.horizontalLayout_6.addWidget(self.tbUDStart)
        self.glInterview.addLayout(self.horizontalLayout_6, 8, 1, 1, 1)
        self.cbInterviewSecurity = QtGui.QComboBox(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInterviewSecurity.sizePolicy().hasHeightForWidth())
        self.cbInterviewSecurity.setSizePolicy(sizePolicy)
        self.cbInterviewSecurity.setMinimumSize(QtCore.QSize(50, 0))
        self.cbInterviewSecurity.setObjectName(_fromUtf8("cbInterviewSecurity"))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.cbInterviewSecurity.addItem(_fromUtf8(""))
        self.glInterview.addWidget(self.cbInterviewSecurity, 6, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.pgIntBasic)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.glInterview.addWidget(self.lblCode, 0, 0, 1, 1)
        self.leInterviewCode = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewCode.sizePolicy().hasHeightForWidth())
        self.leInterviewCode.setSizePolicy(sizePolicy)
        self.leInterviewCode.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leInterviewCode.setObjectName(_fromUtf8("leInterviewCode"))
        self.glInterview.addWidget(self.leInterviewCode, 0, 1, 1, 1)
        self.lblTitle = QtGui.QLabel(self.pgIntBasic)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.glInterview.addWidget(self.lblTitle, 1, 0, 1, 1)
        self.leInterviewTitle = QtGui.QLineEdit(self.pgIntBasic)
        self.leInterviewTitle.setObjectName(_fromUtf8("leInterviewTitle"))
        self.glInterview.addWidget(self.leInterviewTitle, 1, 1, 1, 1)
        self.lblLocation = QtGui.QLabel(self.pgIntBasic)
        self.lblLocation.setObjectName(_fromUtf8("lblLocation"))
        self.glInterview.addWidget(self.lblLocation, 3, 0, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.pgIntBasic)
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.glInterview.addWidget(self.lblSecurity, 6, 0, 1, 1)
        self.pteInterviewNote = QtGui.QPlainTextEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteInterviewNote.sizePolicy().hasHeightForWidth())
        self.pteInterviewNote.setSizePolicy(sizePolicy)
        self.pteInterviewNote.setMinimumSize(QtCore.QSize(50, 0))
        self.pteInterviewNote.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pteInterviewNote.setObjectName(_fromUtf8("pteInterviewNote"))
        self.glInterview.addWidget(self.pteInterviewNote, 4, 1, 1, 1)
        self.lblNote = QtGui.QLabel(self.pgIntBasic)
        self.lblNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.glInterview.addWidget(self.lblNote, 4, 0, 1, 1)
        self.leInterviewTags = QtGui.QLineEdit(self.pgIntBasic)
        self.leInterviewTags.setObjectName(_fromUtf8("leInterviewTags"))
        self.glInterview.addWidget(self.leInterviewTags, 5, 1, 1, 1)
        self.leInterviewLocation = QtGui.QLineEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewLocation.sizePolicy().hasHeightForWidth())
        self.leInterviewLocation.setSizePolicy(sizePolicy)
        self.leInterviewLocation.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewLocation.setObjectName(_fromUtf8("leInterviewLocation"))
        self.glInterview.addWidget(self.leInterviewLocation, 3, 1, 1, 1)
        self.lblTags = QtGui.QLabel(self.pgIntBasic)
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.glInterview.addWidget(self.lblTags, 5, 0, 1, 1)
        self.lblDescription = QtGui.QLabel(self.pgIntBasic)
        self.lblDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.glInterview.addWidget(self.lblDescription, 2, 0, 1, 1)
        self.pteInterviewDescription = QtGui.QPlainTextEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteInterviewDescription.sizePolicy().hasHeightForWidth())
        self.pteInterviewDescription.setSizePolicy(sizePolicy)
        self.pteInterviewDescription.setMinimumSize(QtCore.QSize(50, 0))
        self.pteInterviewDescription.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pteInterviewDescription.setObjectName(_fromUtf8("pteInterviewDescription"))
        self.glInterview.addWidget(self.pteInterviewDescription, 2, 1, 1, 1)
        self.lbInterviewStatus = QtGui.QLabel(self.pgIntBasic)
        self.lbInterviewStatus.setObjectName(_fromUtf8("lbInterviewStatus"))
        self.glInterview.addWidget(self.lbInterviewStatus, 7, 0, 1, 1)
        self.cbInterviewStatus = QtGui.QComboBox(self.pgIntBasic)
        self.cbInterviewStatus.setObjectName(_fromUtf8("cbInterviewStatus"))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.cbInterviewStatus.addItem(_fromUtf8(""))
        self.glInterview.addWidget(self.cbInterviewStatus, 7, 1, 1, 1)
        self.lblEndDateTime = QtGui.QLabel(self.pgIntBasic)
        self.lblEndDateTime.setMaximumSize(QtCore.QSize(16777215, 33))
        self.lblEndDateTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEndDateTime.setObjectName(_fromUtf8("lblEndDateTime"))
        self.glInterview.addWidget(self.lblEndDateTime, 9, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.dteEnd = QtGui.QDateTimeEdit(self.pgIntBasic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteEnd.sizePolicy().hasHeightForWidth())
        self.dteEnd.setSizePolicy(sizePolicy)
        self.dteEnd.setMinimumSize(QtCore.QSize(50, 0))
        self.dteEnd.setObjectName(_fromUtf8("dteEnd"))
        self.horizontalLayout_7.addWidget(self.dteEnd)
        self.tbUDEnd = QtGui.QToolButton(self.pgIntBasic)
        self.tbUDEnd.setObjectName(_fromUtf8("tbUDEnd"))
        self.horizontalLayout_7.addWidget(self.tbUDEnd)
        self.glInterview.addLayout(self.horizontalLayout_7, 9, 1, 1, 1)
        self.gridLayout_8.addLayout(self.glInterview, 0, 0, 1, 1)
        self.tbxInterview.addItem(self.pgIntBasic, _fromUtf8(""))
        self.pgIntExtra = QtGui.QWidget()
        self.pgIntExtra.setGeometry(QtCore.QRect(0, 0, 176, 327))
        self.pgIntExtra.setObjectName(_fromUtf8("pgIntExtra"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pgIntExtra)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblCitation = QtGui.QLabel(self.pgIntExtra)
        self.lblCitation.setObjectName(_fromUtf8("lblCitation"))
        self.gridLayout_7.addWidget(self.lblCitation, 3, 0, 1, 1)
        self.lblRightsStatement = QtGui.QLabel(self.pgIntExtra)
        self.lblRightsStatement.setObjectName(_fromUtf8("lblRightsStatement"))
        self.gridLayout_7.addWidget(self.lblRightsStatement, 4, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.pgIntExtra)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_7.addWidget(self.lblSource, 2, 0, 1, 1)
        self.lblSubject = QtGui.QLabel(self.pgIntExtra)
        self.lblSubject.setObjectName(_fromUtf8("lblSubject"))
        self.gridLayout_7.addWidget(self.lblSubject, 0, 0, 1, 1)
        self.leLanguage = QtGui.QLineEdit(self.pgIntExtra)
        self.leLanguage.setObjectName(_fromUtf8("leLanguage"))
        self.gridLayout_7.addWidget(self.leLanguage, 1, 1, 1, 1)
        self.leSubject = QtGui.QLineEdit(self.pgIntExtra)
        self.leSubject.setObjectName(_fromUtf8("leSubject"))
        self.gridLayout_7.addWidget(self.leSubject, 0, 1, 1, 1)
        self.lblLanguage = QtGui.QLabel(self.pgIntExtra)
        self.lblLanguage.setObjectName(_fromUtf8("lblLanguage"))
        self.gridLayout_7.addWidget(self.lblLanguage, 1, 0, 1, 1)
        self.lblRightsHolder = QtGui.QLabel(self.pgIntExtra)
        self.lblRightsHolder.setObjectName(_fromUtf8("lblRightsHolder"))
        self.gridLayout_7.addWidget(self.lblRightsHolder, 5, 0, 1, 1)
        self.leRightsHolder = QtGui.QLineEdit(self.pgIntExtra)
        self.leRightsHolder.setObjectName(_fromUtf8("leRightsHolder"))
        self.gridLayout_7.addWidget(self.leRightsHolder, 5, 1, 1, 1)
        self.pteRightsStatement = QtGui.QPlainTextEdit(self.pgIntExtra)
        self.pteRightsStatement.setObjectName(_fromUtf8("pteRightsStatement"))
        self.gridLayout_7.addWidget(self.pteRightsStatement, 4, 1, 1, 1)
        self.pteCitation = QtGui.QPlainTextEdit(self.pgIntExtra)
        self.pteCitation.setObjectName(_fromUtf8("pteCitation"))
        self.gridLayout_7.addWidget(self.pteCitation, 3, 1, 1, 1)
        self.pteSource = QtGui.QPlainTextEdit(self.pgIntExtra)
        self.pteSource.setObjectName(_fromUtf8("pteSource"))
        self.gridLayout_7.addWidget(self.pteSource, 2, 1, 1, 1)
        self.lblInterviewCreator = QtGui.QLabel(self.pgIntExtra)
        self.lblInterviewCreator.setObjectName(_fromUtf8("lblInterviewCreator"))
        self.gridLayout_7.addWidget(self.lblInterviewCreator, 6, 0, 1, 1)
        self.leInterviewPublisher = QtGui.QLineEdit(self.pgIntExtra)
        self.leInterviewPublisher.setObjectName(_fromUtf8("leInterviewPublisher"))
        self.gridLayout_7.addWidget(self.leInterviewPublisher, 6, 1, 1, 1)
        self.leInterviewCreator = QtGui.QLineEdit(self.pgIntExtra)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leInterviewCreator.sizePolicy().hasHeightForWidth())
        self.leInterviewCreator.setSizePolicy(sizePolicy)
        self.leInterviewCreator.setMinimumSize(QtCore.QSize(50, 0))
        self.leInterviewCreator.setObjectName(_fromUtf8("leInterviewCreator"))
        self.gridLayout_7.addWidget(self.leInterviewCreator, 7, 1, 1, 1)
        self.lblInterviewPublisher = QtGui.QLabel(self.pgIntExtra)
        self.lblInterviewPublisher.setObjectName(_fromUtf8("lblInterviewPublisher"))
        self.gridLayout_7.addWidget(self.lblInterviewPublisher, 7, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tbxInterview.addItem(self.pgIntExtra, _fromUtf8(""))
        self.pgIntParticipants = QtGui.QWidget()
        self.pgIntParticipants.setGeometry(QtCore.QRect(0, 0, 222, 209))
        self.pgIntParticipants.setObjectName(_fromUtf8("pgIntParticipants"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pgIntParticipants)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.vlInterviewParticipants = QtGui.QVBoxLayout()
        self.vlInterviewParticipants.setObjectName(_fromUtf8("vlInterviewParticipants"))
        self.lblInterviewParticipants = QtGui.QLabel(self.pgIntParticipants)
        self.lblInterviewParticipants.setObjectName(_fromUtf8("lblInterviewParticipants"))
        self.vlInterviewParticipants.addWidget(self.lblInterviewParticipants)
        self.tblInterviewParticipants = QtGui.QTableWidget(self.pgIntParticipants)
        self.tblInterviewParticipants.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblInterviewParticipants.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInterviewParticipants.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblInterviewParticipants.setObjectName(_fromUtf8("tblInterviewParticipants"))
        self.tblInterviewParticipants.setColumnCount(0)
        self.tblInterviewParticipants.setRowCount(0)
        self.vlInterviewParticipants.addWidget(self.tblInterviewParticipants)
        self.hlInterviewParticipants = QtGui.QHBoxLayout()
        self.hlInterviewParticipants.setObjectName(_fromUtf8("hlInterviewParticipants"))
        self.pbIntPartNew = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartNew.setObjectName(_fromUtf8("pbIntPartNew"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartNew)
        self.pbIntPartSave = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartSave.setEnabled(False)
        self.pbIntPartSave.setObjectName(_fromUtf8("pbIntPartSave"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartSave)
        self.pbIntPartCancel = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartCancel.setEnabled(False)
        self.pbIntPartCancel.setObjectName(_fromUtf8("pbIntPartCancel"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartCancel)
        self.pbIntPartDelete = QtGui.QPushButton(self.pgIntParticipants)
        self.pbIntPartDelete.setEnabled(False)
        self.pbIntPartDelete.setObjectName(_fromUtf8("pbIntPartDelete"))
        self.hlInterviewParticipants.addWidget(self.pbIntPartDelete)
        self.vlInterviewParticipants.addLayout(self.hlInterviewParticipants)
        self.gridLayout_4.addLayout(self.vlInterviewParticipants, 0, 0, 1, 1)
        self.glIntCont = QtGui.QGridLayout()
        self.glIntCont.setObjectName(_fromUtf8("glIntCont"))
        self.leIntPartFamily = QtGui.QLineEdit(self.pgIntParticipants)
        self.leIntPartFamily.setObjectName(_fromUtf8("leIntPartFamily"))
        self.glIntCont.addWidget(self.leIntPartFamily, 2, 2, 1, 1)
        self.lblIntPartCommunity = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartCommunity.setObjectName(_fromUtf8("lblIntPartCommunity"))
        self.glIntCont.addWidget(self.lblIntPartCommunity, 1, 0, 1, 1)
        self.lblIntPartFamily = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartFamily.setObjectName(_fromUtf8("lblIntPartFamily"))
        self.glIntCont.addWidget(self.lblIntPartFamily, 2, 0, 1, 1)
        self.lblIntPartName = QtGui.QLabel(self.pgIntParticipants)
        self.lblIntPartName.setObjectName(_fromUtf8("lblIntPartName"))
        self.glIntCont.addWidget(self.lblIntPartName, 0, 0, 1, 1)
        self.cbIntPartName = QtGui.QComboBox(self.pgIntParticipants)
        self.cbIntPartName.setObjectName(_fromUtf8("cbIntPartName"))
        self.glIntCont.addWidget(self.cbIntPartName, 0, 2, 1, 1)
        self.leIntPartCommunity = QtGui.QLineEdit(self.pgIntParticipants)
        self.leIntPartCommunity.setObjectName(_fromUtf8("leIntPartCommunity"))
        self.glIntCont.addWidget(self.leIntPartCommunity, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.glIntCont, 1, 0, 1, 1)
        self.tbxInterview.addItem(self.pgIntParticipants, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tbxInterview, 0, 1, 1, 1)
        self.twMapBioSettings.addTab(self.tbInterviews, _fromUtf8(""))
        self.tbAbout = QtGui.QWidget()
        self.tbAbout.setObjectName(_fromUtf8("tbAbout"))
        self.gridLayout = QtGui.QGridLayout(self.tbAbout)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.teAbout = QtGui.QTextEdit(self.tbAbout)
        self.teAbout.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teAbout.sizePolicy().hasHeightForWidth())
        self.teAbout.setSizePolicy(sizePolicy)
        self.teAbout.setAcceptDrops(False)
        self.teAbout.setUndoRedoEnabled(False)
        self.teAbout.setReadOnly(True)
        self.teAbout.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.teAbout.setObjectName(_fromUtf8("teAbout"))
        self.gridLayout.addWidget(self.teAbout, 0, 0, 1, 1)
        self.twMapBioSettings.addTab(self.tbAbout, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.twMapBioSettings, 0, 0, 1, 1)
        self.pbDialogClose = QtGui.QPushButton(mapbioManager)
        self.pbDialogClose.setObjectName(_fromUtf8("pbDialogClose"))
        self.gridLayout_14.addWidget(self.pbDialogClose, 1, 0, 1, 1)

        self.retranslateUi(mapbioManager)
        self.twMapBioSettings.setCurrentIndex(0)
        self.tbxParticipants.setCurrentIndex(0)
        self.tbxInterview.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioManager)
        mapbioManager.setTabOrder(self.twMapBioSettings, self.leProjectDir)
        mapbioManager.setTabOrder(self.leProjectDir, self.tbSelectProjectDir)
        mapbioManager.setTabOrder(self.tbSelectProjectDir, self.cbCurrentProject)
        mapbioManager.setTabOrder(self.cbCurrentProject, self.pbSaveSettings)
        mapbioManager.setTabOrder(self.pbSaveSettings, self.pbCancelSettings)
        mapbioManager.setTabOrder(self.pbCancelSettings, self.pbDeleteProject)
        mapbioManager.setTabOrder(self.pbDeleteProject, self.leQgsProject)
        mapbioManager.setTabOrder(self.leQgsProject, self.tbSelectQgsProject)
        mapbioManager.setTabOrder(self.tbSelectQgsProject, self.tblBaseGroups)
        mapbioManager.setTabOrder(self.tblBaseGroups, self.cbProjectGroups)
        mapbioManager.setTabOrder(self.cbProjectGroups, self.pbAddBaseGroup)
        mapbioManager.setTabOrder(self.pbAddBaseGroup, self.pbRemoveBaseGroup)
        mapbioManager.setTabOrder(self.pbRemoveBaseGroup, self.pbSaveProjectMapSettings)
        mapbioManager.setTabOrder(self.pbSaveProjectMapSettings, self.pbCancelProjectMapSettings)
        mapbioManager.setTabOrder(self.pbCancelProjectMapSettings, self.leProjectCode)
        mapbioManager.setTabOrder(self.leProjectCode, self.pteProjectDescription)
        mapbioManager.setTabOrder(self.pteProjectDescription, self.pteContentCodes)
        mapbioManager.setTabOrder(self.pteContentCodes, self.cbDefaultCode)
        mapbioManager.setTabOrder(self.cbDefaultCode, self.cbPointCode)
        mapbioManager.setTabOrder(self.cbPointCode, self.cbLineCode)
        mapbioManager.setTabOrder(self.cbLineCode, self.cbPolygonCode)
        mapbioManager.setTabOrder(self.cbPolygonCode, self.pbProjectDetailsSave)
        mapbioManager.setTabOrder(self.pbProjectDetailsSave, self.pbProjectDetailsCancel)
        mapbioManager.setTabOrder(self.pbProjectDetailsCancel, self.tblParticipants)
        mapbioManager.setTabOrder(self.tblParticipants, self.pbParticipantNew)
        mapbioManager.setTabOrder(self.pbParticipantNew, self.pbParticipantSave)
        mapbioManager.setTabOrder(self.pbParticipantSave, self.pbParticipantCancel)
        mapbioManager.setTabOrder(self.pbParticipantCancel, self.pbParticipantDelete)
        mapbioManager.setTabOrder(self.pbParticipantDelete, self.leParticipantCode)
        mapbioManager.setTabOrder(self.leParticipantCode, self.leFirstName)
        mapbioManager.setTabOrder(self.leFirstName, self.leLastName)
        mapbioManager.setTabOrder(self.leLastName, self.leEmail)
        mapbioManager.setTabOrder(self.leEmail, self.leCommunity)
        mapbioManager.setTabOrder(self.leCommunity, self.leFamily)
        mapbioManager.setTabOrder(self.leFamily, self.leMaidenName)
        mapbioManager.setTabOrder(self.leMaidenName, self.cbGender)
        mapbioManager.setTabOrder(self.cbGender, self.cbMaritalStatus)
        mapbioManager.setTabOrder(self.cbMaritalStatus, self.leBirthDate)
        mapbioManager.setTabOrder(self.leBirthDate, self.leParticipantTags)
        mapbioManager.setTabOrder(self.leParticipantTags, self.pteParticipantNote)
        mapbioManager.setTabOrder(self.pteParticipantNote, self.tblAddresses)
        mapbioManager.setTabOrder(self.tblAddresses, self.pbAddNew)
        mapbioManager.setTabOrder(self.pbAddNew, self.pbAddSave)
        mapbioManager.setTabOrder(self.pbAddSave, self.pbAddCancel)
        mapbioManager.setTabOrder(self.pbAddCancel, self.pbAddDelete)
        mapbioManager.setTabOrder(self.pbAddDelete, self.tblTelecoms)
        mapbioManager.setTabOrder(self.tblTelecoms, self.pbTelNew)
        mapbioManager.setTabOrder(self.pbTelNew, self.pbTelSave)
        mapbioManager.setTabOrder(self.pbTelSave, self.pbTelCancel)
        mapbioManager.setTabOrder(self.pbTelCancel, self.pbTelDelete)
        mapbioManager.setTabOrder(self.pbTelDelete, self.cbTelType)
        mapbioManager.setTabOrder(self.cbTelType, self.leTelNumber)
        mapbioManager.setTabOrder(self.leTelNumber, self.tblInterviews)
        mapbioManager.setTabOrder(self.tblInterviews, self.pbIntNew)
        mapbioManager.setTabOrder(self.pbIntNew, self.pbIntSave)
        mapbioManager.setTabOrder(self.pbIntSave, self.pbIntCancel)
        mapbioManager.setTabOrder(self.pbIntCancel, self.pbIntDelete)
        mapbioManager.setTabOrder(self.pbIntDelete, self.leInterviewCode)
        mapbioManager.setTabOrder(self.leInterviewCode, self.leInterviewTitle)
        mapbioManager.setTabOrder(self.leInterviewTitle, self.pteInterviewDescription)
        mapbioManager.setTabOrder(self.pteInterviewDescription, self.leInterviewLocation)
        mapbioManager.setTabOrder(self.leInterviewLocation, self.pteInterviewNote)
        mapbioManager.setTabOrder(self.pteInterviewNote, self.leInterviewTags)
        mapbioManager.setTabOrder(self.leInterviewTags, self.cbInterviewSecurity)
        mapbioManager.setTabOrder(self.cbInterviewSecurity, self.cbInterviewStatus)
        mapbioManager.setTabOrder(self.cbInterviewStatus, self.leSubject)
        mapbioManager.setTabOrder(self.leSubject, self.leLanguage)
        mapbioManager.setTabOrder(self.leLanguage, self.pteSource)
        mapbioManager.setTabOrder(self.pteSource, self.pteCitation)
        mapbioManager.setTabOrder(self.pteCitation, self.pteRightsStatement)
        mapbioManager.setTabOrder(self.pteRightsStatement, self.leRightsHolder)
        mapbioManager.setTabOrder(self.leRightsHolder, self.tblInterviewParticipants)
        mapbioManager.setTabOrder(self.tblInterviewParticipants, self.pbIntPartNew)
        mapbioManager.setTabOrder(self.pbIntPartNew, self.pbIntPartSave)
        mapbioManager.setTabOrder(self.pbIntPartSave, self.pbIntPartCancel)
        mapbioManager.setTabOrder(self.pbIntPartCancel, self.pbIntPartDelete)
        mapbioManager.setTabOrder(self.pbIntPartDelete, self.cbIntPartName)
        mapbioManager.setTabOrder(self.cbIntPartName, self.leIntPartCommunity)
        mapbioManager.setTabOrder(self.leIntPartCommunity, self.leIntPartFamily)
        mapbioManager.setTabOrder(self.leIntPartFamily, self.teAbout)
        mapbioManager.setTabOrder(self.teAbout, self.pbDialogClose)

    def retranslateUi(self, mapbioManager):
        mapbioManager.setWindowTitle(_translate("mapbioManager", "Dialog", None))
        self.tbSelectProjectDir.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Click here to set the LOUIS Map Biographer default projects directory.</p></body></html>", None))
        self.tbSelectProjectDir.setText(_translate("mapbioManager", "...", None))
        self.lblCurrentProject.setText(_translate("mapbioManager", "Select or Create Project", None))
        self.lblProjectsDir.setText(_translate("mapbioManager", "Projects Directory", None))
        self.lblOggEnc.setText(_translate("mapbioManager", "Location of oggenc program", None))
        self.tbOggEnc.setText(_translate("mapbioManager", "...", None))
        self.pbSaveSettings.setText(_translate("mapbioManager", "Save Settings", None))
        self.pbCancelSettings.setText(_translate("mapbioManager", "Cancel Settings", None))
        self.pbDeleteProject.setText(_translate("mapbioManager", "Delete Current Project", None))
        self.pbTransfer.setText(_translate("mapbioManager", "Transfer Data", None))
        self.pbSystemTest.setToolTip(_translate("mapbioManager", "Test if audio and other libraries are present and available", None))
        self.pbSystemTest.setText(_translate("mapbioManager", "Check System", None))
        self.lblProjectMapSettings.setText(_translate("mapbioManager", "Project Map Settings", None))
        self.lblQgsProject.setText(_translate("mapbioManager", "QGIS Project", None))
        self.tbSelectQgsProject.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Click here to select the QGIS project to use with LOUIS Map Biographer</p></body></html>", None))
        self.tbSelectQgsProject.setText(_translate("mapbioManager", "...", None))
        self.lblBaseLayerGroups.setText(_translate("mapbioManager", "Base Layer Groups           ", None))
        self.lblBaseGroupOptions.setText(_translate("mapbioManager", "Use project groups as base layers ", None))
        self.pbAddBaseGroup.setText(_translate("mapbioManager", "Add", None))
        self.pbRemoveBaseGroup.setText(_translate("mapbioManager", "Remove", None))
        self.lblMaxScale.setText(_translate("mapbioManager", "Maximum Map Scale", None))
        self.cbMaxScale.setItemText(0, _translate("mapbioManager", "1:1,100", None))
        self.cbMaxScale.setItemText(1, _translate("mapbioManager", "1:2,200", None))
        self.cbMaxScale.setItemText(2, _translate("mapbioManager", "1:4,500", None))
        self.cbMaxScale.setItemText(3, _translate("mapbioManager", "1:9,000", None))
        self.cbMaxScale.setItemText(4, _translate("mapbioManager", "1:18,000", None))
        self.cbMaxScale.setItemText(5, _translate("mapbioManager", "1:36,000", None))
        self.cbMaxScale.setItemText(6, _translate("mapbioManager", "1:72,000", None))
        self.cbMaxScale.setItemText(7, _translate("mapbioManager", "1:144,000", None))
        self.cbMaxScale.setItemText(8, _translate("mapbioManager", "1:288,000", None))
        self.cbMaxScale.setItemText(9, _translate("mapbioManager", "1:577,000", None))
        self.cbMaxScale.setItemText(10, _translate("mapbioManager", "1:1,150,000", None))
        self.cbMaxScale.setItemText(11, _translate("mapbioManager", "1:2,300,000", None))
        self.cbMaxScale.setItemText(12, _translate("mapbioManager", "1:4,600,000", None))
        self.lblMinScale.setText(_translate("mapbioManager", "Minimum Map Scale", None))
        self.cbMinScale.setItemText(0, _translate("mapbioManager", "1:2,200", None))
        self.cbMinScale.setItemText(1, _translate("mapbioManager", "1:4,500", None))
        self.cbMinScale.setItemText(2, _translate("mapbioManager", "1:9,000", None))
        self.cbMinScale.setItemText(3, _translate("mapbioManager", "1:18,000", None))
        self.cbMinScale.setItemText(4, _translate("mapbioManager", "1:36,000", None))
        self.cbMinScale.setItemText(5, _translate("mapbioManager", "1:72,000", None))
        self.cbMinScale.setItemText(6, _translate("mapbioManager", "1:144,000", None))
        self.cbMinScale.setItemText(7, _translate("mapbioManager", "1:288,000", None))
        self.cbMinScale.setItemText(8, _translate("mapbioManager", "1:576,000", None))
        self.cbMinScale.setItemText(9, _translate("mapbioManager", "1:1,150,000", None))
        self.cbMinScale.setItemText(10, _translate("mapbioManager", "1:2,300,000", None))
        self.cbMinScale.setItemText(11, _translate("mapbioManager", "1:4,600,000", None))
        self.cbMinScale.setItemText(12, _translate("mapbioManager", "1:9,200,000", None))
        self.lblZoomNotices.setText(_translate("mapbioManager", "Show Zoom Range Notices", None))
        self.cbZoomRangeNotices.setItemText(0, _translate("mapbioManager", "No", None))
        self.cbZoomRangeNotices.setItemText(1, _translate("mapbioManager", "Yes", None))
        self.lblProjectBoundary.setText(_translate("mapbioManager", "Project Boundary Layer ", None))
        self.lblEnableReference.setText(_translate("mapbioManager", "Enable Reference Layer", None))
        self.lblReferenceLayer.setText(_translate("mapbioManager", "Project Reference Layer", None))
        self.cbEnableReference.setItemText(0, _translate("mapbioManager", "No", None))
        self.cbEnableReference.setItemText(1, _translate("mapbioManager", "Yes", None))
        self.pbSaveProjectMapSettings.setText(_translate("mapbioManager", "Save Project Map Settings", None))
        self.pbCancelProjectMapSettings.setText(_translate("mapbioManager", "Cancel", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbSettings), _translate("mapbioManager", "Map Biographer Settings", None))
        self.lblProjCode.setText(_translate("mapbioManager", "Project Code", None))
        self.leProjectCode.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a code for this project.</p></body></html>", None))
        self.lblProjDescription.setText(_translate("mapbioManager", "Project Description", None))
        self.pteProjectDescription.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a brief description of the project here.</p></body></html>", None))
        self.cbUseHeritage.setText(_translate("mapbioManager", "Check if this project is used with LOUIS Heritage", None))
        self.lblProjOther.setText(_translate("mapbioManager", "LOUIS Heritage Other Information", None))
        self.pteProjectOther.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Additional information about the project recorded in LOUIS Heritage is shown here. It can not be edited.</p></body></html>", None))
        self.lblCustomFields.setText(_translate("mapbioManager", "LOUIS Heritage Custom Fields", None))
        self.pteCustomFields.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Custom fields defined in LOUIS Heritage are listed here. They can not be edited.</p></body></html>", None))
        self.lblDateAndTime.setText(_translate("mapbioManager", "Project Use Period Definitions", None))
        self.cbUsePeriod.setText(_translate("mapbioManager", "Enabled", None))
        self.pteDateAndTime.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter use period ranges using the following format:</p><p>1900-01-01 : 1967-12-31 = Before Bennett Dam<br/>1968-01-01 : 2014-08-31 = After Bennett Dam until today</p></body></html>", None))
        self.lblTimeOfYear.setText(_translate("mapbioManager", "Project Times of Year Definitions", None))
        self.cbTimeOfYear.setText(_translate("mapbioManager", "Enabled", None))
        self.pteTimeOfYear.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter time of year options (one per line) using as a list of months and a name as per the following example:</p><p>12,1,2 = Winter<br/>3,4,5 = Spring<br/>6,7,8 = Summer<br/>9,10,11 = Autumn</p></body></html>", None))
        self.lblContentCodes.setText(_translate("mapbioManager", "Project Content Code Definitions", None))
        self.tbSortCodes.setText(_translate("mapbioManager", "Sort Codes", None))
        self.pteContentCodes.setToolTip(_translate("mapbioManager", "<html><head/><body><p>Enter a list of codes (one per line) in the following format:</p><p>BP = Berry Picking<br/>CB = Cabin</p><p><br/></p></body></html>", None))
        self.lblDefaultCodes.setText(_translate("mapbioManager", "Project Default Feature Codes", None))
        self.lblDefaultCode.setText(_translate("mapbioManager", "Non-Spatial", None))
        self.lblDefaultPointCode.setText(_translate("mapbioManager", "Point", None))
        self.lblDefaultLineCode.setText(_translate("mapbioManager", "Line", None))
        self.lblDefaultPolygonCode.setText(_translate("mapbioManager", "Polygon", None))
        self.pbProjectDetailsSave.setText(_translate("mapbioManager", "Save", None))
        self.pbProjectDetailsCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbProjectDetails), _translate("mapbioManager", "Project Details", None))
        self.lblParticipants.setText(_translate("mapbioManager", "Participants", None))
        self.tblParticipants.setSortingEnabled(True)
        self.pbParticipantNew.setText(_translate("mapbioManager", "New", None))
        self.pbParticipantSave.setText(_translate("mapbioManager", "Save", None))
        self.pbParticipantCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbParticipantDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblEmail.setText(_translate("mapbioManager", "Email Address", None))
        self.lblFamilyGroup.setText(_translate("mapbioManager", "Family Group", None))
        self.lblFirstName.setText(_translate("mapbioManager", "First Name", None))
        self.lblLastName.setText(_translate("mapbioManager", "Last Name", None))
        self.lblParticipantCode.setText(_translate("mapbioManager", "Participant Code", None))
        self.lblCommunityName.setText(_translate("mapbioManager", "Community", None))
        self.lblMaidenName.setText(_translate("mapbioManager", "Maiden Name", None))
        self.lblGender.setText(_translate("mapbioManager", "Gender", None))
        self.cbGender.setItemText(0, _translate("mapbioManager", "Unknown", None))
        self.cbGender.setItemText(1, _translate("mapbioManager", "Male", None))
        self.cbGender.setItemText(2, _translate("mapbioManager", "Female", None))
        self.cbGender.setItemText(3, _translate("mapbioManager", "Refused", None))
        self.cbGender.setItemText(4, _translate("mapbioManager", "Other", None))
        self.lblMaritalStatus.setText(_translate("mapbioManager", "Marital Status", None))
        self.cbMaritalStatus.setItemText(0, _translate("mapbioManager", "Unknown", None))
        self.cbMaritalStatus.setItemText(1, _translate("mapbioManager", "Single", None))
        self.cbMaritalStatus.setItemText(2, _translate("mapbioManager", "Married", None))
        self.cbMaritalStatus.setItemText(3, _translate("mapbioManager", "Divorced", None))
        self.cbMaritalStatus.setItemText(4, _translate("mapbioManager", "Refused", None))
        self.cbMaritalStatus.setItemText(5, _translate("mapbioManager", "Other", None))
        self.lblParticipantNote.setText(_translate("mapbioManager", "Note", None))
        self.lblParticipantTags.setText(_translate("mapbioManager", "Tags", None))
        self.lblBirthDate.setText(_translate("mapbioManager", "Birth Date", None))
        self.leBirthDate.setInputMask(_translate("mapbioManager", "9999-99-99; ", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgBasicInfo), _translate("mapbioManager", "Basic Information", None))
        self.tblAddresses.setSortingEnabled(True)
        self.pbAddNew.setText(_translate("mapbioManager", "New", None))
        self.pbAddSave.setText(_translate("mapbioManager", "Save", None))
        self.pbAddCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbAddDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblAddress.setText(_translate("mapbioManager", "Address ", None))
        self.lblAddType.setText(_translate("mapbioManager", "Type", None))
        self.cbAddType.setItemText(0, _translate("mapbioManager", "Home", None))
        self.cbAddType.setItemText(1, _translate("mapbioManager", "Work", None))
        self.cbAddType.setItemText(2, _translate("mapbioManager", "PO Box", None))
        self.cbAddType.setItemText(3, _translate("mapbioManager", "Other", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgAddresses), _translate("mapbioManager", "Addresses", None))
        self.tblTelecoms.setSortingEnabled(True)
        self.pbTelNew.setText(_translate("mapbioManager", "New", None))
        self.pbTelSave.setText(_translate("mapbioManager", "Save", None))
        self.pbTelCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbTelDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblTelType.setText(_translate("mapbioManager", "Type", None))
        self.lblTelecom.setText(_translate("mapbioManager", "Number", None))
        self.cbTelType.setItemText(0, _translate("mapbioManager", "Home", None))
        self.cbTelType.setItemText(1, _translate("mapbioManager", "Work", None))
        self.cbTelType.setItemText(2, _translate("mapbioManager", "Mobile", None))
        self.cbTelType.setItemText(3, _translate("mapbioManager", "Pager", None))
        self.cbTelType.setItemText(4, _translate("mapbioManager", "Fax", None))
        self.cbTelType.setItemText(5, _translate("mapbioManager", "Other", None))
        self.tbxParticipants.setItemText(self.tbxParticipants.indexOf(self.pgTelecoms), _translate("mapbioManager", "Phones / Faxes", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbPeople), _translate("mapbioManager", "Participants", None))
        self.lblInterviews.setText(_translate("mapbioManager", "Interview List", None))
        self.tblInterviews.setSortingEnabled(False)
        self.pbIntNew.setText(_translate("mapbioManager", "New", None))
        self.pbIntCopy.setText(_translate("mapbioManager", "Copy", None))
        self.pbIntSave.setText(_translate("mapbioManager", "Save", None))
        self.pbIntCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbIntDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblStartDateTime.setText(_translate("mapbioManager", "Start Date / Time", None))
        self.dteStart.setDisplayFormat(_translate("mapbioManager", "yyyy-MM-dd HH:mm", None))
        self.tbUDStart.setToolTip(_translate("mapbioManager", "Update start from interview", None))
        self.tbUDStart.setText(_translate("mapbioManager", "S", None))
        self.cbInterviewSecurity.setItemText(0, _translate("mapbioManager", "Public", None))
        self.cbInterviewSecurity.setItemText(1, _translate("mapbioManager", "Community", None))
        self.cbInterviewSecurity.setItemText(2, _translate("mapbioManager", "Private", None))
        self.lblCode.setText(_translate("mapbioManager", "Interview Code", None))
        self.lblTitle.setText(_translate("mapbioManager", "Interview Title", None))
        self.lblLocation.setText(_translate("mapbioManager", "Interview Location", None))
        self.lblSecurity.setText(_translate("mapbioManager", "Default Security", None))
        self.lblNote.setText(_translate("mapbioManager", "Note", None))
        self.lblTags.setText(_translate("mapbioManager", "Tags", None))
        self.lblDescription.setText(_translate("mapbioManager", "Description", None))
        self.lbInterviewStatus.setText(_translate("mapbioManager", "Interview Status", None))
        self.cbInterviewStatus.setItemText(0, _translate("mapbioManager", "New", None))
        self.cbInterviewStatus.setItemText(1, _translate("mapbioManager", "Completed", None))
        self.cbInterviewStatus.setItemText(2, _translate("mapbioManager", "Transcribed", None))
        self.cbInterviewStatus.setItemText(3, _translate("mapbioManager", "Uploaded", None))
        self.lblEndDateTime.setText(_translate("mapbioManager", "End Date / Time", None))
        self.dteEnd.setDisplayFormat(_translate("mapbioManager", "yyyy-MM-dd HH:mm", None))
        self.tbUDEnd.setToolTip(_translate("mapbioManager", "Update end from interview", None))
        self.tbUDEnd.setText(_translate("mapbioManager", "E", None))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntBasic), _translate("mapbioManager", "Interview Basic Information", None))
        self.lblCitation.setText(_translate("mapbioManager", "Citation", None))
        self.lblRightsStatement.setText(_translate("mapbioManager", "Rights Statement", None))
        self.lblSource.setText(_translate("mapbioManager", "Source", None))
        self.lblSubject.setText(_translate("mapbioManager", "Subject", None))
        self.lblLanguage.setText(_translate("mapbioManager", "Language", None))
        self.lblRightsHolder.setText(_translate("mapbioManager", "Rights Holder", None))
        self.lblInterviewCreator.setText(_translate("mapbioManager", "Interview Creator", None))
        self.lblInterviewPublisher.setText(_translate("mapbioManager", "Interview Publisher", None))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntExtra), _translate("mapbioManager", "Interview Extra Information", None))
        self.lblInterviewParticipants.setText(_translate("mapbioManager", "Participants", None))
        self.tblInterviewParticipants.setSortingEnabled(True)
        self.pbIntPartNew.setText(_translate("mapbioManager", "New", None))
        self.pbIntPartSave.setText(_translate("mapbioManager", "Save", None))
        self.pbIntPartCancel.setText(_translate("mapbioManager", "Cancel", None))
        self.pbIntPartDelete.setText(_translate("mapbioManager", "Delete", None))
        self.lblIntPartCommunity.setText(_translate("mapbioManager", "Community", None))
        self.lblIntPartFamily.setText(_translate("mapbioManager", "Family Group", None))
        self.lblIntPartName.setText(_translate("mapbioManager", "Name", None))
        self.tbxInterview.setItemText(self.tbxInterview.indexOf(self.pgIntParticipants), _translate("mapbioManager", "Interview Participants", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbInterviews), _translate("mapbioManager", "Interviews", None))
        self.teAbout.setHtml(_translate("mapbioManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\">LOUIS Map Biographer Version 1.3.1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">For additional information about this tool please visit </span><a href=\"https://www.louistoolkit.ca/ourtools/map-biographer/\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">https://www.louistoolkit.ca/ourtools/map-biographer/</span></a><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">To post questions or provide suggestions see our contact page at </span><a href=\"https://www.louistoolkit.ca/contact-us/\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">https://www.louistoolkit.ca/contact-us/</span></a><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\">ABOUT LOUIS Map Biographer</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">LOUIS Map Biographer is a free / open source solution for direct to digital capture of land use information through in-person interviews. LOUIS Map Biographer is designed to support the best practice ideas for Use and Occupancy mapping studies outlined in </span><span style=\" font-family:\'Cantarell\'; font-size:11pt; font-style:italic;\">Living Proof</span><span style=\" font-family:\'Cantarell\'; font-size:11pt; vertical-align:super;\">1</span><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">LOUIS Map Biographer is part of the Land Occupancy and Use Information Systems (LOUIS) Toolkit. LOUIS Map Biographer can be used on its own or together with other parts of the LOUIS tool kit. For more information about LOUIS Toolkit visit: </span><a href=\"https://www.louistoolkit.ca/\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">https://www.louistoolkit.ca/</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:11pt;\"><br /></p>\n"
"<hr />\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">1 - Tobias, Terry N., 2009. </span><a href=\"http://ecotrust.ca/report/living-proof-use-and-occupancy-mapping/\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; text-decoration: underline; color:#0000ff;\">Living Proof: The essential data-collection guide for Indigenous Use-and-Occupancy map surveys</span></a><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">.  Ecostrust Canada and Union of BC Indian Chiefs, British Columbia, Canada.</span></p></body></html>", None))
        self.twMapBioSettings.setTabText(self.twMapBioSettings.indexOf(self.tbAbout), _translate("mapbioManager", "About", None))
        self.pbDialogClose.setText(_translate("mapbioManager", "Close", None))

