# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_interviewer.ui'
#
# Created: Fri Aug  8 11:19:19 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapbioInterviewer(object):
    def setupUi(self, mapbioInterviewer):
        mapbioInterviewer.setObjectName(_fromUtf8("mapbioInterviewer"))
        mapbioInterviewer.resize(405, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapbioInterviewer.sizePolicy().hasHeightForWidth())
        mapbioInterviewer.setSizePolicy(sizePolicy)
        mapbioInterviewer.setMinimumSize(QtCore.QSize(405, 700))
        mapbioInterviewer.setMaximumSize(QtCore.QSize(408, 524287))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("interview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapbioInterviewer.setWindowIcon(icon)
        mapbioInterviewer.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        mapbioInterviewer.setWindowTitle(_fromUtf8("LOUIS Map Biographer - Interview Tool"))
        self.dcwLMB = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcwLMB.sizePolicy().hasHeightForWidth())
        self.dcwLMB.setSizePolicy(sizePolicy)
        self.dcwLMB.setMinimumSize(QtCore.QSize(405, 0))
        self.dcwLMB.setObjectName(_fromUtf8("dcwLMB"))
        self.tbInterviewer = QtGui.QToolBox(self.dcwLMB)
        self.tbInterviewer.setGeometry(QtCore.QRect(0, 0, 405, 671))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tbInterviewer.sizePolicy().hasHeightForWidth())
        self.tbInterviewer.setSizePolicy(sizePolicy)
        self.tbInterviewer.setObjectName(_fromUtf8("tbInterviewer"))
        self.pgSelectInterview = QtGui.QWidget()
        self.pgSelectInterview.setGeometry(QtCore.QRect(0, 0, 405, 601))
        self.pgSelectInterview.setObjectName(_fromUtf8("pgSelectInterview"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.pgSelectInterview)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 390, 401, 121))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.flMapLayers = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.flMapLayers.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flMapLayers.setMargin(0)
        self.flMapLayers.setObjectName(_fromUtf8("flMapLayers"))
        self.lblBase = QtGui.QLabel(self.formLayoutWidget_2)
        self.lblBase.setObjectName(_fromUtf8("lblBase"))
        self.flMapLayers.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblBase)
        self.cbBase = QtGui.QComboBox(self.formLayoutWidget_2)
        self.cbBase.setObjectName(_fromUtf8("cbBase"))
        self.flMapLayers.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbBase)
        self.lblReferenceLayer = QtGui.QLabel(self.formLayoutWidget_2)
        self.lblReferenceLayer.setObjectName(_fromUtf8("lblReferenceLayer"))
        self.flMapLayers.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblReferenceLayer)
        self.cbBoundary = QtGui.QComboBox(self.formLayoutWidget_2)
        self.cbBoundary.setObjectName(_fromUtf8("cbBoundary"))
        self.cbBoundary.addItem(_fromUtf8(""))
        self.cbBoundary.addItem(_fromUtf8(""))
        self.flMapLayers.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbBoundary)
        self.lblBaseLayer = QtGui.QLabel(self.formLayoutWidget_2)
        self.lblBaseLayer.setObjectName(_fromUtf8("lblBaseLayer"))
        self.flMapLayers.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblBaseLayer)
        self.cbReference = QtGui.QComboBox(self.formLayoutWidget_2)
        self.cbReference.setObjectName(_fromUtf8("cbReference"))
        self.cbReference.addItem(_fromUtf8(""))
        self.cbReference.addItem(_fromUtf8(""))
        self.flMapLayers.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbReference)
        self.frmInterviewSetup = QtGui.QFrame(self.pgSelectInterview)
        self.frmInterviewSetup.setGeometry(QtCore.QRect(0, 0, 401, 361))
        self.frmInterviewSetup.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmInterviewSetup.setFrameShadow(QtGui.QFrame.Plain)
        self.frmInterviewSetup.setObjectName(_fromUtf8("frmInterviewSetup"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frmInterviewSetup)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 310, 401, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.hlInterviewButtons = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hlInterviewButtons.setMargin(0)
        self.hlInterviewButtons.setObjectName(_fromUtf8("hlInterviewButtons"))
        self.pbConductInterview = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pbConductInterview.setEnabled(False)
        self.pbConductInterview.setObjectName(_fromUtf8("pbConductInterview"))
        self.hlInterviewButtons.addWidget(self.pbConductInterview)
        self.pbClose = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlInterviewButtons.addWidget(self.pbClose)
        self.formLayoutWidget_3 = QtGui.QWidget(self.frmInterviewSetup)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 180, 401, 121))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.flAudio = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.flAudio.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flAudio.setMargin(0)
        self.flAudio.setObjectName(_fromUtf8("flAudio"))
        self.lblRecordAudio = QtGui.QLabel(self.formLayoutWidget_3)
        self.lblRecordAudio.setObjectName(_fromUtf8("lblRecordAudio"))
        self.flAudio.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblRecordAudio)
        self.cbRecordAudio = QtGui.QComboBox(self.formLayoutWidget_3)
        self.cbRecordAudio.setEnabled(False)
        self.cbRecordAudio.setObjectName(_fromUtf8("cbRecordAudio"))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.flAudio.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbRecordAudio)
        self.lblAudioInputDevice = QtGui.QLabel(self.formLayoutWidget_3)
        self.lblAudioInputDevice.setObjectName(_fromUtf8("lblAudioInputDevice"))
        self.flAudio.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblAudioInputDevice)
        self.cbAudioInputDevice = QtGui.QComboBox(self.formLayoutWidget_3)
        self.cbAudioInputDevice.setEnabled(False)
        self.cbAudioInputDevice.setObjectName(_fromUtf8("cbAudioInputDevice"))
        self.flAudio.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbAudioInputDevice)
        self.lblTestSound = QtGui.QLabel(self.formLayoutWidget_3)
        self.lblTestSound.setObjectName(_fromUtf8("lblTestSound"))
        self.flAudio.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblTestSound)
        self.pbSoundTest = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pbSoundTest.setEnabled(False)
        self.pbSoundTest.setObjectName(_fromUtf8("pbSoundTest"))
        self.flAudio.setWidget(2, QtGui.QFormLayout.FieldRole, self.pbSoundTest)
        self.hlBelowInterviewControls = QtGui.QFrame(self.frmInterviewSetup)
        self.hlBelowInterviewControls.setGeometry(QtCore.QRect(0, 150, 404, 40))
        self.hlBelowInterviewControls.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowInterviewControls.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowInterviewControls.setObjectName(_fromUtf8("hlBelowInterviewControls"))
        self.formLayoutWidget = QtGui.QWidget(self.frmInterviewSetup)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 151))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.flProjectInfo = QtGui.QFormLayout(self.formLayoutWidget)
        self.flProjectInfo.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flProjectInfo.setMargin(0)
        self.flProjectInfo.setObjectName(_fromUtf8("flProjectInfo"))
        self.lblProjectCode = QtGui.QLabel(self.formLayoutWidget)
        self.lblProjectCode.setObjectName(_fromUtf8("lblProjectCode"))
        self.flProjectInfo.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblProjectCode)
        self.leProjectCode = QtGui.QLineEdit(self.formLayoutWidget)
        self.leProjectCode.setEnabled(False)
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.flProjectInfo.setWidget(0, QtGui.QFormLayout.FieldRole, self.leProjectCode)
        self.lblInterview = QtGui.QLabel(self.formLayoutWidget)
        self.lblInterview.setObjectName(_fromUtf8("lblInterview"))
        self.flProjectInfo.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblInterview)
        self.cbInterviewSelection = QtGui.QComboBox(self.formLayoutWidget)
        self.cbInterviewSelection.setObjectName(_fromUtf8("cbInterviewSelection"))
        self.flProjectInfo.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbInterviewSelection)
        self.lblParticipants = QtGui.QLabel(self.formLayoutWidget)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.flProjectInfo.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblParticipants)
        self.pteParticipants = QtGui.QPlainTextEdit(self.formLayoutWidget)
        self.pteParticipants.setEnabled(False)
        self.pteParticipants.setMaximumSize(QtCore.QSize(16777215, 69))
        self.pteParticipants.setObjectName(_fromUtf8("pteParticipants"))
        self.flProjectInfo.setWidget(2, QtGui.QFormLayout.FieldRole, self.pteParticipants)
        self.hlBelowInterviewControls_3 = QtGui.QFrame(self.pgSelectInterview)
        self.hlBelowInterviewControls_3.setGeometry(QtCore.QRect(0, 360, 404, 31))
        self.hlBelowInterviewControls_3.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowInterviewControls_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowInterviewControls_3.setObjectName(_fromUtf8("hlBelowInterviewControls_3"))
        self.tbInterviewer.addItem(self.pgSelectInterview, _fromUtf8(""))
        self.pgInterview = QtGui.QWidget()
        self.pgInterview.setEnabled(False)
        self.pgInterview.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pgInterview.setObjectName(_fromUtf8("pgInterview"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.pgInterview)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 405, 597))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlConductInterview = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlConductInterview.setMargin(0)
        self.vlConductInterview.setObjectName(_fromUtf8("vlConductInterview"))
        self.hlInterviewActions = QtGui.QHBoxLayout()
        self.hlInterviewActions.setObjectName(_fromUtf8("hlInterviewActions"))
        self.pbStart = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        self.hlInterviewActions.addWidget(self.pbStart)
        self.pbPause = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbPause.setObjectName(_fromUtf8("pbPause"))
        self.hlInterviewActions.addWidget(self.pbPause)
        self.pbFinish = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbFinish.setEnabled(False)
        self.pbFinish.setObjectName(_fromUtf8("pbFinish"))
        self.hlInterviewActions.addWidget(self.pbFinish)
        self.pbCloseInterview = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbCloseInterview.setEnabled(False)
        self.pbCloseInterview.setObjectName(_fromUtf8("pbCloseInterview"))
        self.hlInterviewActions.addWidget(self.pbCloseInterview)
        self.vlConductInterview.addLayout(self.hlInterviewActions)
        self.hlInterviewTools = QtGui.QHBoxLayout()
        self.hlInterviewTools.setObjectName(_fromUtf8("hlInterviewTools"))
        self.tbPoint = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPoint.setEnabled(False)
        self.tbPoint.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPoint.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPoint.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tbPoint.setIcon(icon1)
        self.tbPoint.setCheckable(True)
        self.tbPoint.setChecked(False)
        self.tbPoint.setObjectName(_fromUtf8("tbPoint"))
        self.hlInterviewTools.addWidget(self.tbPoint)
        self.tbLine = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbLine.setMinimumSize(QtCore.QSize(28, 28))
        self.tbLine.setMaximumSize(QtCore.QSize(28, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLine.setIcon(icon2)
        self.tbLine.setCheckable(True)
        self.tbLine.setObjectName(_fromUtf8("tbLine"))
        self.hlInterviewTools.addWidget(self.tbLine)
        self.tbPolygon = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPolygon.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPolygon.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPolygon.setIcon(icon3)
        self.tbPolygon.setCheckable(True)
        self.tbPolygon.setObjectName(_fromUtf8("tbPolygon"))
        self.hlInterviewTools.addWidget(self.tbPolygon)
        self.tbEdit = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbEdit.setMinimumSize(QtCore.QSize(28, 28))
        self.tbEdit.setMaximumSize(QtCore.QSize(28, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("edit_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEdit.setIcon(icon4)
        self.tbEdit.setCheckable(True)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.hlInterviewTools.addWidget(self.tbEdit)
        self.tbMove = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbMove.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMove.setMaximumSize(QtCore.QSize(28, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("edit_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMove.setIcon(icon5)
        self.tbMove.setCheckable(True)
        self.tbMove.setObjectName(_fromUtf8("tbMove"))
        self.hlInterviewTools.addWidget(self.tbMove)
        self.tbPan = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPan.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPan.setMaximumSize(QtCore.QSize(28, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPan.setIcon(icon6)
        self.tbPan.setCheckable(True)
        self.tbPan.setObjectName(_fromUtf8("tbPan"))
        self.hlInterviewTools.addWidget(self.tbPan)
        self.vlLeftOfClock_2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.vlLeftOfClock_2.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock_2.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock_2.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock_2.setObjectName(_fromUtf8("vlLeftOfClock_2"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock_2)
        self.tbNonSpatial = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbNonSpatial.setMinimumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setMaximumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setCheckable(False)
        self.tbNonSpatial.setObjectName(_fromUtf8("tbNonSpatial"))
        self.hlInterviewTools.addWidget(self.tbNonSpatial)
        self.vlLeftOfClock = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.vlLeftOfClock.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock.setObjectName(_fromUtf8("vlLeftOfClock"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock)
        self.lblTimeOfDay = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblTimeOfDay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimeOfDay.setObjectName(_fromUtf8("lblTimeOfDay"))
        self.hlInterviewTools.addWidget(self.lblTimeOfDay)
        self.vlLeftOfTimer = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.vlLeftOfTimer.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfTimer.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfTimer.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfTimer.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfTimer.setObjectName(_fromUtf8("vlLeftOfTimer"))
        self.hlInterviewTools.addWidget(self.vlLeftOfTimer)
        self.lblTimer = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblTimer.setScaledContents(False)
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName(_fromUtf8("lblTimer"))
        self.hlInterviewTools.addWidget(self.lblTimer)
        self.vlConductInterview.addLayout(self.hlInterviewTools)
        self.hlBelowToolBar = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.hlBelowToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowToolBar.setObjectName(_fromUtf8("hlBelowToolBar"))
        self.vlConductInterview.addWidget(self.hlBelowToolBar)
        self.hlSectionInfo = QtGui.QHBoxLayout()
        self.hlSectionInfo.setObjectName(_fromUtf8("hlSectionInfo"))
        self.vlSectionList = QtGui.QVBoxLayout()
        self.vlSectionList.setObjectName(_fromUtf8("vlSectionList"))
        self.lblSectionList = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSectionList.setObjectName(_fromUtf8("lblSectionList"))
        self.vlSectionList.addWidget(self.lblSectionList)
        self.lwSectionList = QtGui.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSectionList.sizePolicy().hasHeightForWidth())
        self.lwSectionList.setSizePolicy(sizePolicy)
        self.lwSectionList.setMinimumSize(QtCore.QSize(100, 0))
        self.lwSectionList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lwSectionList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSectionList.setObjectName(_fromUtf8("lwSectionList"))
        self.vlSectionList.addWidget(self.lwSectionList)
        self.hlSectionInfo.addLayout(self.vlSectionList)
        self.grSectionEdit = QtGui.QGridLayout()
        self.grSectionEdit.setObjectName(_fromUtf8("grSectionEdit"))
        self.cbFeatureStatus = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbFeatureStatus.setObjectName(_fromUtf8("cbFeatureStatus"))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbFeatureStatus, 3, 2, 1, 1)
        self.lblTimePeriod = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblTimePeriod.setObjectName(_fromUtf8("lblTimePeriod"))
        self.grSectionEdit.addWidget(self.lblTimePeriod, 4, 1, 1, 1)
        self.lblTags = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.grSectionEdit.addWidget(self.lblTags, 2, 1, 1, 1)
        self.lblSpatialFeature = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSpatialFeature.setObjectName(_fromUtf8("lblSpatialFeature"))
        self.grSectionEdit.addWidget(self.lblSpatialFeature, 3, 1, 1, 1)
        self.cbSectionSecurity = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbSectionSecurity.setObjectName(_fromUtf8("cbSectionSecurity"))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbSectionSecurity, 1, 2, 1, 1)
        self.cbAnnualVariation = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbAnnualVariation.setObjectName(_fromUtf8("cbAnnualVariation"))
        self.cbAnnualVariation.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbAnnualVariation, 5, 2, 1, 1)
        self.leSectionNote = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.leSectionNote.setObjectName(_fromUtf8("leSectionNote"))
        self.grSectionEdit.addWidget(self.leSectionNote, 6, 2, 1, 1)
        self.lblAnnualVariation = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblAnnualVariation.setObjectName(_fromUtf8("lblAnnualVariation"))
        self.grSectionEdit.addWidget(self.lblAnnualVariation, 5, 1, 1, 1)
        self.leCode = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.leCode.setEnabled(False)
        self.leCode.setDragEnabled(False)
        self.leCode.setReadOnly(True)
        self.leCode.setObjectName(_fromUtf8("leCode"))
        self.grSectionEdit.addWidget(self.leCode, 0, 2, 1, 1)
        self.pteTags = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.pteTags.setEnabled(False)
        self.pteTags.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pteTags.setObjectName(_fromUtf8("pteTags"))
        self.grSectionEdit.addWidget(self.pteTags, 2, 2, 1, 1)
        self.lblSectionNote = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSectionNote.setObjectName(_fromUtf8("lblSectionNote"))
        self.grSectionEdit.addWidget(self.lblSectionNote, 6, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.grSectionEdit.addWidget(self.lblCode, 0, 1, 1, 1)
        self.cbTimePeriod = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbTimePeriod.setObjectName(_fromUtf8("cbTimePeriod"))
        self.cbTimePeriod.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbTimePeriod, 4, 2, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.grSectionEdit.addWidget(self.lblSecurity, 1, 1, 1, 1)
        self.hlSectionInfo.addLayout(self.grSectionEdit)
        self.vlConductInterview.addLayout(self.hlSectionInfo)
        self.hlSectionActions = QtGui.QHBoxLayout()
        self.hlSectionActions.setObjectName(_fromUtf8("hlSectionActions"))
        self.pbSaveSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbSaveSection.setObjectName(_fromUtf8("pbSaveSection"))
        self.hlSectionActions.addWidget(self.pbSaveSection)
        self.pbCancelSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbCancelSection.setEnabled(False)
        self.pbCancelSection.setObjectName(_fromUtf8("pbCancelSection"))
        self.hlSectionActions.addWidget(self.pbCancelSection)
        self.pbDeleteSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbDeleteSection.setObjectName(_fromUtf8("pbDeleteSection"))
        self.hlSectionActions.addWidget(self.pbDeleteSection)
        self.vlConductInterview.addLayout(self.hlSectionActions)
        self.hlBelowSectionEdit = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.hlBelowSectionEdit.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowSectionEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowSectionEdit.setObjectName(_fromUtf8("hlBelowSectionEdit"))
        self.vlConductInterview.addWidget(self.hlBelowSectionEdit)
        self.lblCodeList = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblCodeList.setObjectName(_fromUtf8("lblCodeList"))
        self.vlConductInterview.addWidget(self.lblCodeList)
        self.lwProjectCodes = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.lwProjectCodes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwProjectCodes.setProperty("showDropIndicator", False)
        self.lwProjectCodes.setDragEnabled(False)
        self.lwProjectCodes.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lwProjectCodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwProjectCodes.setViewMode(QtGui.QListView.IconMode)
        self.lwProjectCodes.setObjectName(_fromUtf8("lwProjectCodes"))
        self.vlConductInterview.addWidget(self.lwProjectCodes)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblAudioStatus = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblAudioStatus.setObjectName(_fromUtf8("lblAudioStatus"))
        self.horizontalLayout.addWidget(self.lblAudioStatus)
        self.vlConductInterview.addLayout(self.horizontalLayout)
        self.tbInterviewer.addItem(self.pgInterview, _fromUtf8(""))
        mapbioInterviewer.setWidget(self.dcwLMB)

        self.retranslateUi(mapbioInterviewer)
        self.tbInterviewer.setCurrentIndex(0)
        self.cbRecordAudio.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioInterviewer)
        mapbioInterviewer.setTabOrder(self.leProjectCode, self.cbInterviewSelection)
        mapbioInterviewer.setTabOrder(self.cbInterviewSelection, self.pteParticipants)
        mapbioInterviewer.setTabOrder(self.pteParticipants, self.cbRecordAudio)
        mapbioInterviewer.setTabOrder(self.cbRecordAudio, self.cbAudioInputDevice)
        mapbioInterviewer.setTabOrder(self.cbAudioInputDevice, self.pbSoundTest)
        mapbioInterviewer.setTabOrder(self.pbSoundTest, self.pbConductInterview)
        mapbioInterviewer.setTabOrder(self.pbConductInterview, self.pbClose)
        mapbioInterviewer.setTabOrder(self.pbClose, self.cbBase)
        mapbioInterviewer.setTabOrder(self.cbBase, self.cbBoundary)
        mapbioInterviewer.setTabOrder(self.cbBoundary, self.cbReference)
        mapbioInterviewer.setTabOrder(self.cbReference, self.pbStart)
        mapbioInterviewer.setTabOrder(self.pbStart, self.pbPause)
        mapbioInterviewer.setTabOrder(self.pbPause, self.pbFinish)
        mapbioInterviewer.setTabOrder(self.pbFinish, self.pbCloseInterview)
        mapbioInterviewer.setTabOrder(self.pbCloseInterview, self.tbPoint)
        mapbioInterviewer.setTabOrder(self.tbPoint, self.tbLine)
        mapbioInterviewer.setTabOrder(self.tbLine, self.tbPolygon)
        mapbioInterviewer.setTabOrder(self.tbPolygon, self.tbEdit)
        mapbioInterviewer.setTabOrder(self.tbEdit, self.tbMove)
        mapbioInterviewer.setTabOrder(self.tbMove, self.tbPan)
        mapbioInterviewer.setTabOrder(self.tbPan, self.tbNonSpatial)
        mapbioInterviewer.setTabOrder(self.tbNonSpatial, self.lwSectionList)
        mapbioInterviewer.setTabOrder(self.lwSectionList, self.leCode)
        mapbioInterviewer.setTabOrder(self.leCode, self.cbSectionSecurity)
        mapbioInterviewer.setTabOrder(self.cbSectionSecurity, self.pteTags)
        mapbioInterviewer.setTabOrder(self.pteTags, self.cbFeatureStatus)
        mapbioInterviewer.setTabOrder(self.cbFeatureStatus, self.cbTimePeriod)
        mapbioInterviewer.setTabOrder(self.cbTimePeriod, self.cbAnnualVariation)
        mapbioInterviewer.setTabOrder(self.cbAnnualVariation, self.leSectionNote)
        mapbioInterviewer.setTabOrder(self.leSectionNote, self.pbSaveSection)
        mapbioInterviewer.setTabOrder(self.pbSaveSection, self.pbCancelSection)
        mapbioInterviewer.setTabOrder(self.pbCancelSection, self.pbDeleteSection)
        mapbioInterviewer.setTabOrder(self.pbDeleteSection, self.lwProjectCodes)

    def retranslateUi(self, mapbioInterviewer):
        self.lblBase.setText(QtGui.QApplication.translate("mapbioInterviewer", "Base Map", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReferenceLayer.setText(QtGui.QApplication.translate("mapbioInterviewer", "Project Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.cbBoundary.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.cbBoundary.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBaseLayer.setText(QtGui.QApplication.translate("mapbioInterviewer", "Reference Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbReference.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.cbReference.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConductInterview.setText(QtGui.QApplication.translate("mapbioInterviewer", "Conduct Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("mapbioInterviewer", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRecordAudio.setText(QtGui.QApplication.translate("mapbioInterviewer", "Record Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAudioInputDevice.setText(QtGui.QApplication.translate("mapbioInterviewer", "Audio Input Device", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTestSound.setText(QtGui.QApplication.translate("mapbioInterviewer", "Test Sound System", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSoundTest.setText(QtGui.QApplication.translate("mapbioInterviewer", "No Sound Test Required", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectCode.setText(QtGui.QApplication.translate("mapbioInterviewer", "Project Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterview.setText(QtGui.QApplication.translate("mapbioInterviewer", "Select Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipants.setText(QtGui.QApplication.translate("mapbioInterviewer", "Participant(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tbInterviewer.setItemText(self.tbInterviewer.indexOf(self.pgSelectInterview), QtGui.QApplication.translate("mapbioInterviewer", "Select Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Start or continue recording the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setText(QtGui.QApplication.translate("mapbioInterviewer", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Pause the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setText(QtGui.QApplication.translate("mapbioInterviewer", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Finish the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setText(QtGui.QApplication.translate("mapbioInterviewer", "Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCloseInterview.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Stop Interview Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCloseInterview.setText(QtGui.QApplication.translate("mapbioInterviewer", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPan.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setText(QtGui.QApplication.translate("mapbioInterviewer", "NS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimeOfDay.setText(QtGui.QApplication.translate("mapbioInterviewer", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimer.setText(QtGui.QApplication.translate("mapbioInterviewer", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionList.setText(QtGui.QApplication.translate("mapbioInterviewer", "Sections", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Is Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "From Section #", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimePeriod.setText(QtGui.QApplication.translate("mapbioInterviewer", "Use Period", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTags.setText(QtGui.QApplication.translate("mapbioInterviewer", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpatialFeature.setText(QtGui.QApplication.translate("mapbioInterviewer", "Spatial Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(2, QtGui.QApplication.translate("mapbioInterviewer", "Restricted", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(3, QtGui.QApplication.translate("mapbioInterviewer", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAnnualVariation.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAnnualVariation.setText(QtGui.QApplication.translate("mapbioInterviewer", "Annual Var.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionNote.setText(QtGui.QApplication.translate("mapbioInterviewer", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("mapbioInterviewer", "Content Code", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimePeriod.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSecurity.setText(QtGui.QApplication.translate("mapbioInterviewer", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Save Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Cancel Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Delete Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodeList.setText(QtGui.QApplication.translate("mapbioInterviewer", "Project Code List", None, QtGui.QApplication.UnicodeUTF8))
        self.lwProjectCodes.setSortingEnabled(False)
        self.lblAudioStatus.setText(QtGui.QApplication.translate("mapbioInterviewer", "Audio recording not selected", None, QtGui.QApplication.UnicodeUTF8))
        self.tbInterviewer.setItemText(self.tbInterviewer.indexOf(self.pgInterview), QtGui.QApplication.translate("mapbioInterviewer", "Conduct Interview", None, QtGui.QApplication.UnicodeUTF8))

