# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_transcriber.ui'
#
# Created: Wed Mar  4 17:27:05 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapbioTranscriber(object):
    def setupUi(self, mapbioTranscriber):
        mapbioTranscriber.setObjectName(_fromUtf8("mapbioTranscriber"))
        mapbioTranscriber.setEnabled(True)
        mapbioTranscriber.resize(405, 670)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapbioTranscriber.sizePolicy().hasHeightForWidth())
        mapbioTranscriber.setSizePolicy(sizePolicy)
        mapbioTranscriber.setMinimumSize(QtCore.QSize(405, 670))
        mapbioTranscriber.setMaximumSize(QtCore.QSize(524287, 524287))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("interview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapbioTranscriber.setWindowIcon(icon)
        mapbioTranscriber.setStyleSheet(_fromUtf8(""))
        mapbioTranscriber.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        mapbioTranscriber.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        mapbioTranscriber.setWindowTitle(_fromUtf8("LOUIS Map Biographer"))
        self.dcwLMB = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcwLMB.sizePolicy().hasHeightForWidth())
        self.dcwLMB.setSizePolicy(sizePolicy)
        self.dcwLMB.setMinimumSize(QtCore.QSize(405, 0))
        self.dcwLMB.setObjectName(_fromUtf8("dcwLMB"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dcwLMB)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frInterviewSelection = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInterviewSelection.sizePolicy().hasHeightForWidth())
        self.frInterviewSelection.setSizePolicy(sizePolicy)
        self.frInterviewSelection.setMinimumSize(QtCore.QSize(0, 125))
        self.frInterviewSelection.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frInterviewSelection.setFrameShape(QtGui.QFrame.NoFrame)
        self.frInterviewSelection.setFrameShadow(QtGui.QFrame.Plain)
        self.frInterviewSelection.setLineWidth(0)
        self.frInterviewSelection.setObjectName(_fromUtf8("frInterviewSelection"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frInterviewSelection)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.hlInterviewMode = QtGui.QHBoxLayout()
        self.hlInterviewMode.setSpacing(2)
        self.hlInterviewMode.setObjectName(_fromUtf8("hlInterviewMode"))
        self.cbMode = QtGui.QComboBox(self.frInterviewSelection)
        self.cbMode.setObjectName(_fromUtf8("cbMode"))
        self.cbMode.addItem(_fromUtf8(""))
        self.cbMode.addItem(_fromUtf8(""))
        self.cbMode.addItem(_fromUtf8(""))
        self.hlInterviewMode.addWidget(self.cbMode)
        self.tbAudioSettings = QtGui.QToolButton(self.frInterviewSelection)
        self.tbAudioSettings.setMinimumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setMaximumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tbAudioSettings.setObjectName(_fromUtf8("tbAudioSettings"))
        self.hlInterviewMode.addWidget(self.tbAudioSettings)
        self.cbRecordAudio = QtGui.QComboBox(self.frInterviewSelection)
        self.cbRecordAudio.setEnabled(True)
        self.cbRecordAudio.setObjectName(_fromUtf8("cbRecordAudio"))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.hlInterviewMode.addWidget(self.cbRecordAudio)
        self.pbClose = QtGui.QPushButton(self.frInterviewSelection)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlInterviewMode.addWidget(self.pbClose)
        self.gridLayout_4.addLayout(self.hlInterviewMode, 0, 0, 1, 1)
        self.hlProjectInterview = QtGui.QHBoxLayout()
        self.hlProjectInterview.setSpacing(2)
        self.hlProjectInterview.setObjectName(_fromUtf8("hlProjectInterview"))
        self.lblProjectCode = QtGui.QLabel(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProjectCode.sizePolicy().hasHeightForWidth())
        self.lblProjectCode.setSizePolicy(sizePolicy)
        self.lblProjectCode.setMinimumSize(QtCore.QSize(0, 0))
        self.lblProjectCode.setObjectName(_fromUtf8("lblProjectCode"))
        self.hlProjectInterview.addWidget(self.lblProjectCode)
        self.leProjectCode = QtGui.QLineEdit(self.frInterviewSelection)
        self.leProjectCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectCode.sizePolicy().hasHeightForWidth())
        self.leProjectCode.setSizePolicy(sizePolicy)
        self.leProjectCode.setMinimumSize(QtCore.QSize(50, 0))
        self.leProjectCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.hlProjectInterview.addWidget(self.leProjectCode)
        self.lblInterview = QtGui.QLabel(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInterview.sizePolicy().hasHeightForWidth())
        self.lblInterview.setSizePolicy(sizePolicy)
        self.lblInterview.setMinimumSize(QtCore.QSize(0, 0))
        self.lblInterview.setObjectName(_fromUtf8("lblInterview"))
        self.hlProjectInterview.addWidget(self.lblInterview)
        self.cbInterviewSelection = QtGui.QComboBox(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInterviewSelection.sizePolicy().hasHeightForWidth())
        self.cbInterviewSelection.setSizePolicy(sizePolicy)
        self.cbInterviewSelection.setMinimumSize(QtCore.QSize(0, 0))
        self.cbInterviewSelection.setObjectName(_fromUtf8("cbInterviewSelection"))
        self.hlProjectInterview.addWidget(self.cbInterviewSelection)
        self.gridLayout_4.addLayout(self.hlProjectInterview, 1, 0, 1, 1)
        self.hlParticipants = QtGui.QHBoxLayout()
        self.hlParticipants.setSpacing(2)
        self.hlParticipants.setObjectName(_fromUtf8("hlParticipants"))
        self.lblParticipants = QtGui.QLabel(self.frInterviewSelection)
        self.lblParticipants.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.hlParticipants.addWidget(self.lblParticipants)
        self.pteParticipants = QtGui.QPlainTextEdit(self.frInterviewSelection)
        self.pteParticipants.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteParticipants.sizePolicy().hasHeightForWidth())
        self.pteParticipants.setSizePolicy(sizePolicy)
        self.pteParticipants.setMinimumSize(QtCore.QSize(0, 25))
        self.pteParticipants.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteParticipants.setObjectName(_fromUtf8("pteParticipants"))
        self.hlParticipants.addWidget(self.pteParticipants)
        self.gridLayout_4.addLayout(self.hlParticipants, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frInterviewSelection, 0, 0, 1, 1)
        self.frSectionControls = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frSectionControls.sizePolicy().hasHeightForWidth())
        self.frSectionControls.setSizePolicy(sizePolicy)
        self.frSectionControls.setMinimumSize(QtCore.QSize(0, 220))
        self.frSectionControls.setFrameShape(QtGui.QFrame.NoFrame)
        self.frSectionControls.setFrameShadow(QtGui.QFrame.Plain)
        self.frSectionControls.setLineWidth(0)
        self.frSectionControls.setObjectName(_fromUtf8("frSectionControls"))
        self.gridLayout = QtGui.QGridLayout(self.frSectionControls)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hlSectionControls = QtGui.QHBoxLayout()
        self.hlSectionControls.setObjectName(_fromUtf8("hlSectionControls"))
        self.vlSectionList = QtGui.QVBoxLayout()
        self.vlSectionList.setObjectName(_fromUtf8("vlSectionList"))
        self.lblSectionList = QtGui.QLabel(self.frSectionControls)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lblSectionList.setFont(font)
        self.lblSectionList.setObjectName(_fromUtf8("lblSectionList"))
        self.vlSectionList.addWidget(self.lblSectionList)
        self.lwSectionList = QtGui.QListWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSectionList.sizePolicy().hasHeightForWidth())
        self.lwSectionList.setSizePolicy(sizePolicy)
        self.lwSectionList.setMinimumSize(QtCore.QSize(100, 180))
        self.lwSectionList.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lwSectionList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSectionList.setObjectName(_fromUtf8("lwSectionList"))
        self.vlSectionList.addWidget(self.lwSectionList)
        self.hlSectionOrderButtons = QtGui.QHBoxLayout()
        self.hlSectionOrderButtons.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hlSectionOrderButtons.setObjectName(_fromUtf8("hlSectionOrderButtons"))
        self.tbMoveUp = QtGui.QToolButton(self.frSectionControls)
        self.tbMoveUp.setEnabled(False)
        self.tbMoveUp.setArrowType(QtCore.Qt.UpArrow)
        self.tbMoveUp.setObjectName(_fromUtf8("tbMoveUp"))
        self.hlSectionOrderButtons.addWidget(self.tbMoveUp)
        self.tbMoveDown = QtGui.QToolButton(self.frSectionControls)
        self.tbMoveDown.setEnabled(False)
        self.tbMoveDown.setArrowType(QtCore.Qt.DownArrow)
        self.tbMoveDown.setObjectName(_fromUtf8("tbMoveDown"))
        self.hlSectionOrderButtons.addWidget(self.tbMoveDown)
        self.vlSectionList.addLayout(self.hlSectionOrderButtons)
        self.lblCodeList = QtGui.QLabel(self.frSectionControls)
        self.lblCodeList.setMinimumSize(QtCore.QSize(100, 0))
        self.lblCodeList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCodeList.setObjectName(_fromUtf8("lblCodeList"))
        self.vlSectionList.addWidget(self.lblCodeList)
        self.lwProjectCodes = QtGui.QListWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwProjectCodes.sizePolicy().hasHeightForWidth())
        self.lwProjectCodes.setSizePolicy(sizePolicy)
        self.lwProjectCodes.setMinimumSize(QtCore.QSize(100, 100))
        self.lwProjectCodes.setMaximumSize(QtCore.QSize(100, 200))
        self.lwProjectCodes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lwProjectCodes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwProjectCodes.setProperty("showDropIndicator", False)
        self.lwProjectCodes.setDragEnabled(False)
        self.lwProjectCodes.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lwProjectCodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwProjectCodes.setProperty("isWrapping", True)
        self.lwProjectCodes.setSpacing(2)
        self.lwProjectCodes.setViewMode(QtGui.QListView.IconMode)
        self.lwProjectCodes.setUniformItemSizes(False)
        self.lwProjectCodes.setObjectName(_fromUtf8("lwProjectCodes"))
        self.vlSectionList.addWidget(self.lwProjectCodes)
        self.hlSectionControls.addLayout(self.vlSectionList)
        self.vlSectionTabAndButtons = QtGui.QVBoxLayout()
        self.vlSectionTabAndButtons.setObjectName(_fromUtf8("vlSectionTabAndButtons"))
        self.twSectionContent = QtGui.QTabWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twSectionContent.sizePolicy().hasHeightForWidth())
        self.twSectionContent.setSizePolicy(sizePolicy)
        self.twSectionContent.setMinimumSize(QtCore.QSize(200, 350))
        self.twSectionContent.setToolTip(_fromUtf8(""))
        self.twSectionContent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twSectionContent.setTabPosition(QtGui.QTabWidget.North)
        self.twSectionContent.setTabShape(QtGui.QTabWidget.Rounded)
        self.twSectionContent.setObjectName(_fromUtf8("twSectionContent"))
        self.tpDetails = QtGui.QWidget()
        self.tpDetails.setObjectName(_fromUtf8("tpDetails"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tpDetails)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grSectionEdit = QtGui.QGridLayout()
        self.grSectionEdit.setVerticalSpacing(6)
        self.grSectionEdit.setObjectName(_fromUtf8("grSectionEdit"))
        self.lblMediaEnd = QtGui.QLabel(self.tpDetails)
        self.lblMediaEnd.setObjectName(_fromUtf8("lblMediaEnd"))
        self.grSectionEdit.addWidget(self.lblMediaEnd, 1, 0, 1, 1)
        self.spMediaStart = QtGui.QSpinBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMediaStart.sizePolicy().hasHeightForWidth())
        self.spMediaStart.setSizePolicy(sizePolicy)
        self.spMediaStart.setMinimumSize(QtCore.QSize(100, 0))
        self.spMediaStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spMediaStart.setMaximum(1000000000)
        self.spMediaStart.setObjectName(_fromUtf8("spMediaStart"))
        self.grSectionEdit.addWidget(self.spMediaStart, 0, 1, 1, 1)
        self.spMediaEnd = QtGui.QSpinBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMediaEnd.sizePolicy().hasHeightForWidth())
        self.spMediaEnd.setSizePolicy(sizePolicy)
        self.spMediaEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.spMediaEnd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spMediaEnd.setMaximum(1000000000)
        self.spMediaEnd.setObjectName(_fromUtf8("spMediaEnd"))
        self.grSectionEdit.addWidget(self.spMediaEnd, 1, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.tpDetails)
        self.lblCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.grSectionEdit.addWidget(self.lblCode, 3, 0, 1, 1)
        self.leCode = QtGui.QLineEdit(self.tpDetails)
        self.leCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCode.sizePolicy().hasHeightForWidth())
        self.leCode.setSizePolicy(sizePolicy)
        self.leCode.setMinimumSize(QtCore.QSize(100, 0))
        self.leCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leCode.setDragEnabled(False)
        self.leCode.setReadOnly(True)
        self.leCode.setObjectName(_fromUtf8("leCode"))
        self.grSectionEdit.addWidget(self.leCode, 3, 1, 1, 1)
        self.lblMediaStart = QtGui.QLabel(self.tpDetails)
        self.lblMediaStart.setObjectName(_fromUtf8("lblMediaStart"))
        self.grSectionEdit.addWidget(self.lblMediaStart, 0, 0, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.tpDetails)
        self.lblSecurity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.grSectionEdit.addWidget(self.lblSecurity, 2, 0, 1, 1)
        self.cbSectionSecurity = QtGui.QComboBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSectionSecurity.sizePolicy().hasHeightForWidth())
        self.cbSectionSecurity.setSizePolicy(sizePolicy)
        self.cbSectionSecurity.setMinimumSize(QtCore.QSize(100, 0))
        self.cbSectionSecurity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbSectionSecurity.setObjectName(_fromUtf8("cbSectionSecurity"))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbSectionSecurity, 2, 1, 1, 1)
        self.lblContentCodes = QtGui.QLabel(self.tpDetails)
        self.lblContentCodes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblContentCodes.setObjectName(_fromUtf8("lblContentCodes"))
        self.grSectionEdit.addWidget(self.lblContentCodes, 4, 0, 1, 1)
        self.pteContentCodes = QtGui.QPlainTextEdit(self.tpDetails)
        self.pteContentCodes.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteContentCodes.sizePolicy().hasHeightForWidth())
        self.pteContentCodes.setSizePolicy(sizePolicy)
        self.pteContentCodes.setMinimumSize(QtCore.QSize(100, 35))
        self.pteContentCodes.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteContentCodes.setObjectName(_fromUtf8("pteContentCodes"))
        self.grSectionEdit.addWidget(self.pteContentCodes, 4, 1, 1, 1)
        self.lblFeatureSource = QtGui.QLabel(self.tpDetails)
        self.lblFeatureSource.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblFeatureSource.setObjectName(_fromUtf8("lblFeatureSource"))
        self.grSectionEdit.addWidget(self.lblFeatureSource, 5, 0, 1, 1)
        self.cbFeatureSource = QtGui.QComboBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFeatureSource.sizePolicy().hasHeightForWidth())
        self.cbFeatureSource.setSizePolicy(sizePolicy)
        self.cbFeatureSource.setMinimumSize(QtCore.QSize(100, 0))
        self.cbFeatureSource.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbFeatureSource.setObjectName(_fromUtf8("cbFeatureSource"))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbFeatureSource, 5, 1, 1, 1)
        self.lblDateTime = QtGui.QLabel(self.tpDetails)
        self.lblDateTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblDateTime.setObjectName(_fromUtf8("lblDateTime"))
        self.grSectionEdit.addWidget(self.lblDateTime, 6, 0, 1, 1)
        self.cbDateTime = QtGui.QComboBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDateTime.sizePolicy().hasHeightForWidth())
        self.cbDateTime.setSizePolicy(sizePolicy)
        self.cbDateTime.setMinimumSize(QtCore.QSize(100, 0))
        self.cbDateTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbDateTime.setObjectName(_fromUtf8("cbDateTime"))
        self.cbDateTime.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbDateTime, 6, 1, 1, 1)
        self.lblTimeOfYear = QtGui.QLabel(self.tpDetails)
        self.lblTimeOfYear.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTimeOfYear.setObjectName(_fromUtf8("lblTimeOfYear"))
        self.grSectionEdit.addWidget(self.lblTimeOfYear, 7, 0, 1, 1)
        self.cbTimeOfYear = QtGui.QComboBox(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTimeOfYear.sizePolicy().hasHeightForWidth())
        self.cbTimeOfYear.setSizePolicy(sizePolicy)
        self.cbTimeOfYear.setMinimumSize(QtCore.QSize(100, 0))
        self.cbTimeOfYear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbTimeOfYear.setObjectName(_fromUtf8("cbTimeOfYear"))
        self.cbTimeOfYear.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbTimeOfYear, 7, 1, 1, 1)
        self.lblSectionTags = QtGui.QLabel(self.tpDetails)
        self.lblSectionTags.setObjectName(_fromUtf8("lblSectionTags"))
        self.grSectionEdit.addWidget(self.lblSectionTags, 8, 0, 1, 1)
        self.pteSectionTags = QtGui.QPlainTextEdit(self.tpDetails)
        self.pteSectionTags.setMinimumSize(QtCore.QSize(100, 35))
        self.pteSectionTags.setObjectName(_fromUtf8("pteSectionTags"))
        self.grSectionEdit.addWidget(self.pteSectionTags, 8, 1, 1, 1)
        self.lblSectionNote = QtGui.QLabel(self.tpDetails)
        self.lblSectionNote.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSectionNote.setObjectName(_fromUtf8("lblSectionNote"))
        self.grSectionEdit.addWidget(self.lblSectionNote, 9, 0, 1, 1)
        self.pteSectionNote = QtGui.QPlainTextEdit(self.tpDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteSectionNote.sizePolicy().hasHeightForWidth())
        self.pteSectionNote.setSizePolicy(sizePolicy)
        self.pteSectionNote.setMinimumSize(QtCore.QSize(100, 35))
        self.pteSectionNote.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pteSectionNote.setObjectName(_fromUtf8("pteSectionNote"))
        self.grSectionEdit.addWidget(self.pteSectionNote, 9, 1, 1, 1)
        self.gridLayout_3.addLayout(self.grSectionEdit, 0, 0, 1, 1)
        self.twSectionContent.addTab(self.tpDetails, _fromUtf8(""))
        self.tpSectionText = QtGui.QWidget()
        self.tpSectionText.setObjectName(_fromUtf8("tpSectionText"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tpSectionText)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pteSectionText = QtGui.QPlainTextEdit(self.tpSectionText)
        self.pteSectionText.setMinimumSize(QtCore.QSize(150, 0))
        self.pteSectionText.setObjectName(_fromUtf8("pteSectionText"))
        self.gridLayout_2.addWidget(self.pteSectionText, 0, 0, 1, 1)
        self.twSectionContent.addTab(self.tpSectionText, _fromUtf8(""))
        self.tpPhotos = QtGui.QWidget()
        self.tpPhotos.setObjectName(_fromUtf8("tpPhotos"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tpPhotos)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbAddPhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbAddPhoto.setObjectName(_fromUtf8("pbAddPhoto"))
        self.horizontalLayout.addWidget(self.pbAddPhoto)
        self.pbEditPhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbEditPhoto.setEnabled(False)
        self.pbEditPhoto.setObjectName(_fromUtf8("pbEditPhoto"))
        self.horizontalLayout.addWidget(self.pbEditPhoto)
        self.pbRemovePhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbRemovePhoto.setEnabled(False)
        self.pbRemovePhoto.setObjectName(_fromUtf8("pbRemovePhoto"))
        self.horizontalLayout.addWidget(self.pbRemovePhoto)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.twPhotos = QtGui.QTableWidget(self.tpPhotos)
        self.twPhotos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twPhotos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twPhotos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twPhotos.setObjectName(_fromUtf8("twPhotos"))
        self.twPhotos.setColumnCount(0)
        self.twPhotos.setRowCount(0)
        self.gridLayout_6.addWidget(self.twPhotos, 0, 0, 1, 1)
        self.twSectionContent.addTab(self.tpPhotos, _fromUtf8(""))
        self.vlSectionTabAndButtons.addWidget(self.twSectionContent)
        self.hlSectionButtons = QtGui.QHBoxLayout()
        self.hlSectionButtons.setObjectName(_fromUtf8("hlSectionButtons"))
        self.pbSaveSection = QtGui.QPushButton(self.frSectionControls)
        self.pbSaveSection.setEnabled(False)
        self.pbSaveSection.setObjectName(_fromUtf8("pbSaveSection"))
        self.hlSectionButtons.addWidget(self.pbSaveSection)
        self.pbCancelSection = QtGui.QPushButton(self.frSectionControls)
        self.pbCancelSection.setEnabled(False)
        self.pbCancelSection.setObjectName(_fromUtf8("pbCancelSection"))
        self.hlSectionButtons.addWidget(self.pbCancelSection)
        self.pbDeleteSection = QtGui.QPushButton(self.frSectionControls)
        self.pbDeleteSection.setEnabled(False)
        self.pbDeleteSection.setObjectName(_fromUtf8("pbDeleteSection"))
        self.hlSectionButtons.addWidget(self.pbDeleteSection)
        self.vlSectionTabAndButtons.addLayout(self.hlSectionButtons)
        self.hlSectionControls.addLayout(self.vlSectionTabAndButtons)
        self.gridLayout.addLayout(self.hlSectionControls, 1, 0, 1, 1)
        self.vlToolBar = QtGui.QVBoxLayout()
        self.vlToolBar.setSpacing(0)
        self.vlToolBar.setObjectName(_fromUtf8("vlToolBar"))
        self.lnAboveToolBar = QtGui.QFrame(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnAboveToolBar.sizePolicy().hasHeightForWidth())
        self.lnAboveToolBar.setSizePolicy(sizePolicy)
        self.lnAboveToolBar.setMinimumSize(QtCore.QSize(0, 10))
        self.lnAboveToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.lnAboveToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnAboveToolBar.setObjectName(_fromUtf8("lnAboveToolBar"))
        self.vlToolBar.addWidget(self.lnAboveToolBar)
        self.hlInterviewTools = QtGui.QHBoxLayout()
        self.hlInterviewTools.setSpacing(2)
        self.hlInterviewTools.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hlInterviewTools.setObjectName(_fromUtf8("hlInterviewTools"))
        self.tbPan = QtGui.QToolButton(self.frSectionControls)
        self.tbPan.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPan.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPan.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPan.setIcon(icon1)
        self.tbPan.setCheckable(True)
        self.tbPan.setAutoRaise(False)
        self.tbPan.setObjectName(_fromUtf8("tbPan"))
        self.hlInterviewTools.addWidget(self.tbPan)
        self.tbPoint = QtGui.QToolButton(self.frSectionControls)
        self.tbPoint.setEnabled(False)
        self.tbPoint.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPoint.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPoint.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tbPoint.setIcon(icon2)
        self.tbPoint.setCheckable(True)
        self.tbPoint.setChecked(False)
        self.tbPoint.setAutoRaise(False)
        self.tbPoint.setArrowType(QtCore.Qt.NoArrow)
        self.tbPoint.setObjectName(_fromUtf8("tbPoint"))
        self.hlInterviewTools.addWidget(self.tbPoint)
        self.tbLine = QtGui.QToolButton(self.frSectionControls)
        self.tbLine.setEnabled(False)
        self.tbLine.setMinimumSize(QtCore.QSize(28, 28))
        self.tbLine.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLine.setIcon(icon3)
        self.tbLine.setCheckable(True)
        self.tbLine.setObjectName(_fromUtf8("tbLine"))
        self.hlInterviewTools.addWidget(self.tbLine)
        self.tbPolygon = QtGui.QToolButton(self.frSectionControls)
        self.tbPolygon.setEnabled(False)
        self.tbPolygon.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPolygon.setMaximumSize(QtCore.QSize(28, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPolygon.setIcon(icon4)
        self.tbPolygon.setCheckable(True)
        self.tbPolygon.setObjectName(_fromUtf8("tbPolygon"))
        self.hlInterviewTools.addWidget(self.tbPolygon)
        self.tbEdit = QtGui.QToolButton(self.frSectionControls)
        self.tbEdit.setEnabled(False)
        self.tbEdit.setMinimumSize(QtCore.QSize(28, 28))
        self.tbEdit.setMaximumSize(QtCore.QSize(28, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("edit_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEdit.setIcon(icon5)
        self.tbEdit.setCheckable(True)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.hlInterviewTools.addWidget(self.tbEdit)
        self.tbMove = QtGui.QToolButton(self.frSectionControls)
        self.tbMove.setEnabled(False)
        self.tbMove.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMove.setMaximumSize(QtCore.QSize(28, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("edit_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMove.setIcon(icon6)
        self.tbMove.setCheckable(True)
        self.tbMove.setObjectName(_fromUtf8("tbMove"))
        self.hlInterviewTools.addWidget(self.tbMove)
        self.vlLeftOfNS = QtGui.QFrame(self.frSectionControls)
        self.vlLeftOfNS.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfNS.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfNS.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfNS.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfNS.setObjectName(_fromUtf8("vlLeftOfNS"))
        self.hlInterviewTools.addWidget(self.vlLeftOfNS)
        self.tbNonSpatial = QtGui.QToolButton(self.frSectionControls)
        self.tbNonSpatial.setEnabled(False)
        self.tbNonSpatial.setMinimumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setMaximumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setCheckable(False)
        self.tbNonSpatial.setObjectName(_fromUtf8("tbNonSpatial"))
        self.hlInterviewTools.addWidget(self.tbNonSpatial)
        self.vlLeftOfClock = QtGui.QFrame(self.frSectionControls)
        self.vlLeftOfClock.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock.setObjectName(_fromUtf8("vlLeftOfClock"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock)
        self.tbMediaPlay = QtGui.QToolButton(self.frSectionControls)
        self.tbMediaPlay.setEnabled(False)
        self.tbMediaPlay.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setMaximumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("media_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMediaPlay.setIcon(icon7)
        self.tbMediaPlay.setCheckable(False)
        self.tbMediaPlay.setObjectName(_fromUtf8("tbMediaPlay"))
        self.hlInterviewTools.addWidget(self.tbMediaPlay)
        self.lblTimeOfDay = QtGui.QLabel(self.frSectionControls)
        self.lblTimeOfDay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimeOfDay.setObjectName(_fromUtf8("lblTimeOfDay"))
        self.hlInterviewTools.addWidget(self.lblTimeOfDay)
        self.vlLeftOfTimer = QtGui.QFrame(self.frSectionControls)
        self.vlLeftOfTimer.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfTimer.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfTimer.setObjectName(_fromUtf8("vlLeftOfTimer"))
        self.hlInterviewTools.addWidget(self.vlLeftOfTimer)
        self.lblTimer = QtGui.QLabel(self.frSectionControls)
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName(_fromUtf8("lblTimer"))
        self.hlInterviewTools.addWidget(self.lblTimer)
        self.vlToolBar.addLayout(self.hlInterviewTools)
        self.hsSectionMedia = QtGui.QSlider(self.frSectionControls)
        self.hsSectionMedia.setEnabled(False)
        self.hsSectionMedia.setMaximumSize(QtCore.QSize(800, 16777215))
        self.hsSectionMedia.setSingleStep(1)
        self.hsSectionMedia.setOrientation(QtCore.Qt.Horizontal)
        self.hsSectionMedia.setObjectName(_fromUtf8("hsSectionMedia"))
        self.vlToolBar.addWidget(self.hsSectionMedia)
        self.lnBelowToolBar = QtGui.QFrame(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnBelowToolBar.sizePolicy().hasHeightForWidth())
        self.lnBelowToolBar.setSizePolicy(sizePolicy)
        self.lnBelowToolBar.setMinimumSize(QtCore.QSize(0, 10))
        self.lnBelowToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.lnBelowToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnBelowToolBar.setObjectName(_fromUtf8("lnBelowToolBar"))
        self.vlToolBar.addWidget(self.lnBelowToolBar)
        self.gridLayout.addLayout(self.vlToolBar, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frSectionControls, 2, 0, 1, 1)
        self.frInterviewActions = QtGui.QFrame(self.dcwLMB)
        self.frInterviewActions.setObjectName(_fromUtf8("frInterviewActions"))
        self.hlInterviewActions = QtGui.QHBoxLayout(self.frInterviewActions)
        self.hlInterviewActions.setSpacing(1)
        self.hlInterviewActions.setObjectName(_fromUtf8("hlInterviewActions"))
        self.pbStart = QtGui.QPushButton(self.frInterviewActions)
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        self.hlInterviewActions.addWidget(self.pbStart)
        self.pbImportFeatures = QtGui.QPushButton(self.frInterviewActions)
        self.pbImportFeatures.setEnabled(False)
        self.pbImportFeatures.setObjectName(_fromUtf8("pbImportFeatures"))
        self.hlInterviewActions.addWidget(self.pbImportFeatures)
        self.pbImportAudio = QtGui.QPushButton(self.frInterviewActions)
        self.pbImportAudio.setEnabled(False)
        self.pbImportAudio.setObjectName(_fromUtf8("pbImportAudio"))
        self.hlInterviewActions.addWidget(self.pbImportAudio)
        self.pbRenumberSections = QtGui.QPushButton(self.frInterviewActions)
        self.pbRenumberSections.setEnabled(False)
        self.pbRenumberSections.setText(_fromUtf8("Renumber"))
        self.pbRenumberSections.setObjectName(_fromUtf8("pbRenumberSections"))
        self.hlInterviewActions.addWidget(self.pbRenumberSections)
        self.pbPause = QtGui.QPushButton(self.frInterviewActions)
        self.pbPause.setEnabled(False)
        self.pbPause.setObjectName(_fromUtf8("pbPause"))
        self.hlInterviewActions.addWidget(self.pbPause)
        self.pbFinish = QtGui.QPushButton(self.frInterviewActions)
        self.pbFinish.setEnabled(False)
        self.pbFinish.setObjectName(_fromUtf8("pbFinish"))
        self.hlInterviewActions.addWidget(self.pbFinish)
        self.gridLayout_5.addWidget(self.frInterviewActions, 1, 0, 1, 1)
        mapbioTranscriber.setWidget(self.dcwLMB)

        self.retranslateUi(mapbioTranscriber)
        self.twSectionContent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioTranscriber)
        mapbioTranscriber.setTabOrder(self.cbMode, self.tbAudioSettings)
        mapbioTranscriber.setTabOrder(self.tbAudioSettings, self.cbRecordAudio)
        mapbioTranscriber.setTabOrder(self.cbRecordAudio, self.pbClose)
        mapbioTranscriber.setTabOrder(self.pbClose, self.leProjectCode)
        mapbioTranscriber.setTabOrder(self.leProjectCode, self.cbInterviewSelection)
        mapbioTranscriber.setTabOrder(self.cbInterviewSelection, self.pteParticipants)
        mapbioTranscriber.setTabOrder(self.pteParticipants, self.pbStart)
        mapbioTranscriber.setTabOrder(self.pbStart, self.pbImportFeatures)
        mapbioTranscriber.setTabOrder(self.pbImportFeatures, self.pbImportAudio)
        mapbioTranscriber.setTabOrder(self.pbImportAudio, self.pbRenumberSections)
        mapbioTranscriber.setTabOrder(self.pbRenumberSections, self.pbPause)
        mapbioTranscriber.setTabOrder(self.pbPause, self.pbFinish)
        mapbioTranscriber.setTabOrder(self.pbFinish, self.tbPan)
        mapbioTranscriber.setTabOrder(self.tbPan, self.tbPoint)
        mapbioTranscriber.setTabOrder(self.tbPoint, self.tbLine)
        mapbioTranscriber.setTabOrder(self.tbLine, self.tbPolygon)
        mapbioTranscriber.setTabOrder(self.tbPolygon, self.tbEdit)
        mapbioTranscriber.setTabOrder(self.tbEdit, self.tbMove)
        mapbioTranscriber.setTabOrder(self.tbMove, self.tbNonSpatial)
        mapbioTranscriber.setTabOrder(self.tbNonSpatial, self.tbMediaPlay)
        mapbioTranscriber.setTabOrder(self.tbMediaPlay, self.lwSectionList)
        mapbioTranscriber.setTabOrder(self.lwSectionList, self.tbMoveUp)
        mapbioTranscriber.setTabOrder(self.tbMoveUp, self.tbMoveDown)
        mapbioTranscriber.setTabOrder(self.tbMoveDown, self.lwProjectCodes)
        mapbioTranscriber.setTabOrder(self.lwProjectCodes, self.twSectionContent)
        mapbioTranscriber.setTabOrder(self.twSectionContent, self.spMediaStart)
        mapbioTranscriber.setTabOrder(self.spMediaStart, self.spMediaEnd)
        mapbioTranscriber.setTabOrder(self.spMediaEnd, self.cbSectionSecurity)
        mapbioTranscriber.setTabOrder(self.cbSectionSecurity, self.leCode)
        mapbioTranscriber.setTabOrder(self.leCode, self.pteContentCodes)
        mapbioTranscriber.setTabOrder(self.pteContentCodes, self.cbFeatureSource)
        mapbioTranscriber.setTabOrder(self.cbFeatureSource, self.cbDateTime)
        mapbioTranscriber.setTabOrder(self.cbDateTime, self.cbTimeOfYear)
        mapbioTranscriber.setTabOrder(self.cbTimeOfYear, self.pteSectionTags)
        mapbioTranscriber.setTabOrder(self.pteSectionTags, self.pteSectionNote)
        mapbioTranscriber.setTabOrder(self.pteSectionNote, self.pteSectionText)
        mapbioTranscriber.setTabOrder(self.pteSectionText, self.twPhotos)
        mapbioTranscriber.setTabOrder(self.twPhotos, self.pbAddPhoto)
        mapbioTranscriber.setTabOrder(self.pbAddPhoto, self.pbEditPhoto)
        mapbioTranscriber.setTabOrder(self.pbEditPhoto, self.pbRemovePhoto)
        mapbioTranscriber.setTabOrder(self.pbRemovePhoto, self.pbSaveSection)
        mapbioTranscriber.setTabOrder(self.pbSaveSection, self.pbCancelSection)
        mapbioTranscriber.setTabOrder(self.pbCancelSection, self.pbDeleteSection)

    def retranslateUi(self, mapbioTranscriber):
        self.cbMode.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Set LMB Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMode.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Conduct Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMode.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Import Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMode.setItemText(2, QtGui.QApplication.translate("mapbioTranscriber", "Transcribe", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Select Audio Device", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Set recording", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "No Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Record Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Close LOUIS Map Biographer", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("mapbioTranscriber", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectCode.setText(QtGui.QApplication.translate("mapbioTranscriber", "Project Code", None, QtGui.QApplication.UnicodeUTF8))
        self.leProjectCode.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Project Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterview.setText(QtGui.QApplication.translate("mapbioTranscriber", "Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInterviewSelection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Selected Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipants.setText(QtGui.QApplication.translate("mapbioTranscriber", "Participant(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.pteParticipants.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "List of interview participants", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionList.setText(QtGui.QApplication.translate("mapbioTranscriber", "Sections", None, QtGui.QApplication.UnicodeUTF8))
        self.lwSectionList.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Time ordered list of sections in interview", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMoveUp.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Move section up", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMoveUp.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMoveDown.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Move section down", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMoveDown.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodeList.setText(QtGui.QApplication.translate("mapbioTranscriber", "Code List", None, QtGui.QApplication.UnicodeUTF8))
        self.lwProjectCodes.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "List of content codes. Click to select and hold Ctrl + click to set content code", None, QtGui.QApplication.UnicodeUTF8))
        self.lwProjectCodes.setSortingEnabled(False)
        self.lblMediaEnd.setText(QtGui.QApplication.translate("mapbioTranscriber", "Media End", None, QtGui.QApplication.UnicodeUTF8))
        self.spMediaStart.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Media index start value", None, QtGui.QApplication.UnicodeUTF8))
        self.spMediaEnd.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Media index end value", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("mapbioTranscriber", "Primary Code", None, QtGui.QApplication.UnicodeUTF8))
        self.leCode.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Main content code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMediaStart.setText(QtGui.QApplication.translate("mapbioTranscriber", "Media Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSecurity.setText(QtGui.QApplication.translate("mapbioTranscriber", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Set security setting for this section", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(2, QtGui.QApplication.translate("mapbioTranscriber", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.lblContentCodes.setText(QtGui.QApplication.translate("mapbioTranscriber", "Content Codes", None, QtGui.QApplication.UnicodeUTF8))
        self.pteContentCodes.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "List of content codes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFeatureSource.setText(QtGui.QApplication.translate("mapbioTranscriber", "Spatial Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureSource.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Spatial feature type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureSource.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureSource.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Is Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureSource.setItemText(2, QtGui.QApplication.translate("mapbioTranscriber", "From Section #", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDateTime.setText(QtGui.QApplication.translate("mapbioTranscriber", "Date / Time", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDateTime.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Set time of use", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDateTime.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimeOfYear.setText(QtGui.QApplication.translate("mapbioTranscriber", "Time of Year", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimeOfYear.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Set time of year this area is used", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimeOfYear.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionTags.setText(QtGui.QApplication.translate("mapbioTranscriber", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionNote.setText(QtGui.QApplication.translate("mapbioTranscriber", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.pteSectionNote.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Enter note about this section", None, QtGui.QApplication.UnicodeUTF8))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpDetails), QtGui.QApplication.translate("mapbioTranscriber", "Section Details", None, QtGui.QApplication.UnicodeUTF8))
        self.pteSectionText.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Enter transcript here", None, QtGui.QApplication.UnicodeUTF8))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpSectionText), QtGui.QApplication.translate("mapbioTranscriber", "Section Text", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddPhoto.setText(QtGui.QApplication.translate("mapbioTranscriber", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEditPhoto.setText(QtGui.QApplication.translate("mapbioTranscriber", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemovePhoto.setText(QtGui.QApplication.translate("mapbioTranscriber", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpPhotos), QtGui.QApplication.translate("mapbioTranscriber", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Save edits section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Cancel edits to section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Delete section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPan.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Navigate the Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPoint.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a point", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a line", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Edit the selected feature", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Move the selected feature", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Insert a non-spatial section", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setText(QtGui.QApplication.translate("mapbioTranscriber", "NS", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMediaPlay.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Play / Pause Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimeOfDay.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Time of day", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimeOfDay.setText(QtGui.QApplication.translate("mapbioTranscriber", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimer.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Time elapsed in interview", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimer.setText(QtGui.QApplication.translate("mapbioTranscriber", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.hsSectionMedia.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Adjust playback position", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Start recording an interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setText(QtGui.QApplication.translate("mapbioTranscriber", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportFeatures.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Import map features and add to end of interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportFeatures.setText(QtGui.QApplication.translate("mapbioTranscriber", "Feature Import", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportAudio.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Import audio file and replace existing file", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportAudio.setText(QtGui.QApplication.translate("mapbioTranscriber", "Audio Import", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRenumberSections.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Renumber sections based on sequence order", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Pause or continue an interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setText(QtGui.QApplication.translate("mapbioTranscriber", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Finish an interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setText(QtGui.QApplication.translate("mapbioTranscriber", "Finish", None, QtGui.QApplication.UnicodeUTF8))

