# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_transcriber.ui'
#
# Created: Wed Sep 24 13:08:21 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapbioTranscriber(object):
    def setupUi(self, mapbioTranscriber):
        mapbioTranscriber.setObjectName(_fromUtf8("mapbioTranscriber"))
        mapbioTranscriber.resize(600, 706)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapbioTranscriber.sizePolicy().hasHeightForWidth())
        mapbioTranscriber.setSizePolicy(sizePolicy)
        mapbioTranscriber.setMinimumSize(QtCore.QSize(600, 705))
        mapbioTranscriber.setMaximumSize(QtCore.QSize(600, 715))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("transcribe.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapbioTranscriber.setWindowIcon(icon)
        mapbioTranscriber.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        mapbioTranscriber.setWindowTitle(_fromUtf8("LOUIS Map Biographer -Transcription Tool"))
        self.dcwLMB = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcwLMB.sizePolicy().hasHeightForWidth())
        self.dcwLMB.setSizePolicy(sizePolicy)
        self.dcwLMB.setMinimumSize(QtCore.QSize(405, 0))
        self.dcwLMB.setObjectName(_fromUtf8("dcwLMB"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.dcwLMB)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 150, 593, 526))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlConductInterview = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlConductInterview.setMargin(0)
        self.vlConductInterview.setObjectName(_fromUtf8("vlConductInterview"))
        self.hlInterviewTools = QtGui.QHBoxLayout()
        self.hlInterviewTools.setObjectName(_fromUtf8("hlInterviewTools"))
        self.tbPan = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPan.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPan.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPan.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPan.setIcon(icon1)
        self.tbPan.setCheckable(True)
        self.tbPan.setAutoRaise(False)
        self.tbPan.setObjectName(_fromUtf8("tbPan"))
        self.hlInterviewTools.addWidget(self.tbPan)
        self.tbPoint = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPoint.setEnabled(False)
        self.tbPoint.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPoint.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPoint.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tbPoint.setIcon(icon2)
        self.tbPoint.setCheckable(True)
        self.tbPoint.setChecked(False)
        self.tbPoint.setAutoRaise(False)
        self.tbPoint.setArrowType(QtCore.Qt.NoArrow)
        self.tbPoint.setObjectName(_fromUtf8("tbPoint"))
        self.hlInterviewTools.addWidget(self.tbPoint)
        self.tbLine = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbLine.setEnabled(False)
        self.tbLine.setMinimumSize(QtCore.QSize(28, 28))
        self.tbLine.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLine.setIcon(icon3)
        self.tbLine.setCheckable(True)
        self.tbLine.setObjectName(_fromUtf8("tbLine"))
        self.hlInterviewTools.addWidget(self.tbLine)
        self.tbPolygon = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbPolygon.setEnabled(False)
        self.tbPolygon.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPolygon.setMaximumSize(QtCore.QSize(28, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPolygon.setIcon(icon4)
        self.tbPolygon.setCheckable(True)
        self.tbPolygon.setObjectName(_fromUtf8("tbPolygon"))
        self.hlInterviewTools.addWidget(self.tbPolygon)
        self.tbEdit = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbEdit.setEnabled(False)
        self.tbEdit.setMinimumSize(QtCore.QSize(28, 28))
        self.tbEdit.setMaximumSize(QtCore.QSize(28, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("edit_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEdit.setIcon(icon5)
        self.tbEdit.setCheckable(True)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.hlInterviewTools.addWidget(self.tbEdit)
        self.tbMove = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbMove.setEnabled(False)
        self.tbMove.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMove.setMaximumSize(QtCore.QSize(28, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("edit_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMove.setIcon(icon6)
        self.tbMove.setCheckable(True)
        self.tbMove.setObjectName(_fromUtf8("tbMove"))
        self.hlInterviewTools.addWidget(self.tbMove)
        self.vlLeftOfClock_2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.vlLeftOfClock_2.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock_2.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock_2.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock_2.setObjectName(_fromUtf8("vlLeftOfClock_2"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock_2)
        self.tbNonSpatial = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbNonSpatial.setEnabled(False)
        self.tbNonSpatial.setMinimumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setMaximumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setCheckable(False)
        self.tbNonSpatial.setObjectName(_fromUtf8("tbNonSpatial"))
        self.hlInterviewTools.addWidget(self.tbNonSpatial)
        self.vlLeftOfClock = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.vlLeftOfClock.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock.setObjectName(_fromUtf8("vlLeftOfClock"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock)
        self.tbMediaPlay = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbMediaPlay.setEnabled(False)
        self.tbMediaPlay.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setMaximumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("media_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMediaPlay.setIcon(icon7)
        self.tbMediaPlay.setCheckable(False)
        self.tbMediaPlay.setObjectName(_fromUtf8("tbMediaPlay"))
        self.hlInterviewTools.addWidget(self.tbMediaPlay)
        self.hsSectionMedia = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.hsSectionMedia.setEnabled(False)
        self.hsSectionMedia.setMaximumSize(QtCore.QSize(220, 16777215))
        self.hsSectionMedia.setOrientation(QtCore.Qt.Horizontal)
        self.hsSectionMedia.setObjectName(_fromUtf8("hsSectionMedia"))
        self.hlInterviewTools.addWidget(self.hsSectionMedia)
        self.tbAudioSettings = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.tbAudioSettings.setMinimumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setMaximumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tbAudioSettings.setObjectName(_fromUtf8("tbAudioSettings"))
        self.hlInterviewTools.addWidget(self.tbAudioSettings)
        self.vlConductInterview.addLayout(self.hlInterviewTools)
        self.hlBelowToolBar = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.hlBelowToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowToolBar.setObjectName(_fromUtf8("hlBelowToolBar"))
        self.vlConductInterview.addWidget(self.hlBelowToolBar)
        self.hlSectionInfo = QtGui.QHBoxLayout()
        self.hlSectionInfo.setObjectName(_fromUtf8("hlSectionInfo"))
        self.vlSectionList = QtGui.QVBoxLayout()
        self.vlSectionList.setObjectName(_fromUtf8("vlSectionList"))
        self.lblSectionList = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSectionList.setObjectName(_fromUtf8("lblSectionList"))
        self.vlSectionList.addWidget(self.lblSectionList)
        self.lwSectionList = QtGui.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSectionList.sizePolicy().hasHeightForWidth())
        self.lwSectionList.setSizePolicy(sizePolicy)
        self.lwSectionList.setMinimumSize(QtCore.QSize(100, 0))
        self.lwSectionList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lwSectionList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSectionList.setObjectName(_fromUtf8("lwSectionList"))
        self.vlSectionList.addWidget(self.lwSectionList)
        self.line = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.vlSectionList.addWidget(self.line)
        self.lblCodeList = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblCodeList.setMinimumSize(QtCore.QSize(100, 0))
        self.lblCodeList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCodeList.setObjectName(_fromUtf8("lblCodeList"))
        self.vlSectionList.addWidget(self.lblCodeList)
        self.lwProjectCodes = QtGui.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwProjectCodes.sizePolicy().hasHeightForWidth())
        self.lwProjectCodes.setSizePolicy(sizePolicy)
        self.lwProjectCodes.setMinimumSize(QtCore.QSize(100, 0))
        self.lwProjectCodes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lwProjectCodes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwProjectCodes.setProperty("showDropIndicator", False)
        self.lwProjectCodes.setDragEnabled(False)
        self.lwProjectCodes.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lwProjectCodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwProjectCodes.setViewMode(QtGui.QListView.IconMode)
        self.lwProjectCodes.setObjectName(_fromUtf8("lwProjectCodes"))
        self.vlSectionList.addWidget(self.lwProjectCodes)
        self.hlSectionInfo.addLayout(self.vlSectionList)
        self.tabSectionContent = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabSectionContent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabSectionContent.setTabPosition(QtGui.QTabWidget.North)
        self.tabSectionContent.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabSectionContent.setObjectName(_fromUtf8("tabSectionContent"))
        self.tpDetails = QtGui.QWidget()
        self.tpDetails.setObjectName(_fromUtf8("tpDetails"))
        self.layoutWidget = QtGui.QWidget(self.tpDetails)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 471, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.grSectionEdit = QtGui.QGridLayout(self.layoutWidget)
        self.grSectionEdit.setMargin(0)
        self.grSectionEdit.setObjectName(_fromUtf8("grSectionEdit"))
        self.cbTimePeriod = QtGui.QComboBox(self.layoutWidget)
        self.cbTimePeriod.setMinimumSize(QtCore.QSize(350, 0))
        self.cbTimePeriod.setMaximumSize(QtCore.QSize(350, 16777215))
        self.cbTimePeriod.setObjectName(_fromUtf8("cbTimePeriod"))
        self.cbTimePeriod.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbTimePeriod, 6, 1, 1, 1)
        self.cbFeatureStatus = QtGui.QComboBox(self.layoutWidget)
        self.cbFeatureStatus.setMinimumSize(QtCore.QSize(350, 0))
        self.cbFeatureStatus.setMaximumSize(QtCore.QSize(350, 16777215))
        self.cbFeatureStatus.setObjectName(_fromUtf8("cbFeatureStatus"))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbFeatureStatus, 5, 1, 1, 1)
        self.cbAnnualVariation = QtGui.QComboBox(self.layoutWidget)
        self.cbAnnualVariation.setMinimumSize(QtCore.QSize(350, 0))
        self.cbAnnualVariation.setMaximumSize(QtCore.QSize(350, 16777215))
        self.cbAnnualVariation.setObjectName(_fromUtf8("cbAnnualVariation"))
        self.cbAnnualVariation.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbAnnualVariation, 7, 1, 1, 1)
        self.cbSectionSecurity = QtGui.QComboBox(self.layoutWidget)
        self.cbSectionSecurity.setMinimumSize(QtCore.QSize(350, 0))
        self.cbSectionSecurity.setMaximumSize(QtCore.QSize(350, 16777215))
        self.cbSectionSecurity.setObjectName(_fromUtf8("cbSectionSecurity"))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbSectionSecurity, 3, 1, 1, 1)
        self.lblSpatialFeature = QtGui.QLabel(self.layoutWidget)
        self.lblSpatialFeature.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSpatialFeature.setObjectName(_fromUtf8("lblSpatialFeature"))
        self.grSectionEdit.addWidget(self.lblSpatialFeature, 5, 0, 1, 1)
        self.lblTags = QtGui.QLabel(self.layoutWidget)
        self.lblTags.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.grSectionEdit.addWidget(self.lblTags, 4, 0, 1, 1)
        self.lblSectionNote = QtGui.QLabel(self.layoutWidget)
        self.lblSectionNote.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSectionNote.setObjectName(_fromUtf8("lblSectionNote"))
        self.grSectionEdit.addWidget(self.lblSectionNote, 8, 0, 1, 1)
        self.pteTags = QtGui.QPlainTextEdit(self.layoutWidget)
        self.pteTags.setEnabled(False)
        self.pteTags.setMinimumSize(QtCore.QSize(350, 0))
        self.pteTags.setMaximumSize(QtCore.QSize(350, 40))
        self.pteTags.setObjectName(_fromUtf8("pteTags"))
        self.grSectionEdit.addWidget(self.pteTags, 4, 1, 1, 1)
        self.lblAnnualVariation = QtGui.QLabel(self.layoutWidget)
        self.lblAnnualVariation.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblAnnualVariation.setObjectName(_fromUtf8("lblAnnualVariation"))
        self.grSectionEdit.addWidget(self.lblAnnualVariation, 7, 0, 1, 1)
        self.lblTimePeriod = QtGui.QLabel(self.layoutWidget)
        self.lblTimePeriod.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTimePeriod.setObjectName(_fromUtf8("lblTimePeriod"))
        self.grSectionEdit.addWidget(self.lblTimePeriod, 6, 0, 1, 1)
        self.spMediaStart = QtGui.QSpinBox(self.layoutWidget)
        self.spMediaStart.setMinimumSize(QtCore.QSize(350, 0))
        self.spMediaStart.setMaximumSize(QtCore.QSize(350, 16777215))
        self.spMediaStart.setMaximum(1000000000)
        self.spMediaStart.setObjectName(_fromUtf8("spMediaStart"))
        self.grSectionEdit.addWidget(self.spMediaStart, 0, 1, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.layoutWidget)
        self.lblSecurity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.grSectionEdit.addWidget(self.lblSecurity, 3, 0, 1, 1)
        self.lblMediaEnd = QtGui.QLabel(self.layoutWidget)
        self.lblMediaEnd.setObjectName(_fromUtf8("lblMediaEnd"))
        self.grSectionEdit.addWidget(self.lblMediaEnd, 1, 0, 1, 1)
        self.leCode = QtGui.QLineEdit(self.layoutWidget)
        self.leCode.setEnabled(False)
        self.leCode.setMinimumSize(QtCore.QSize(350, 0))
        self.leCode.setMaximumSize(QtCore.QSize(350, 16777215))
        self.leCode.setDragEnabled(False)
        self.leCode.setReadOnly(True)
        self.leCode.setObjectName(_fromUtf8("leCode"))
        self.grSectionEdit.addWidget(self.leCode, 2, 1, 1, 1)
        self.spMediaEnd = QtGui.QSpinBox(self.layoutWidget)
        self.spMediaEnd.setMinimumSize(QtCore.QSize(350, 0))
        self.spMediaEnd.setMaximumSize(QtCore.QSize(350, 16777215))
        self.spMediaEnd.setMaximum(1000000000)
        self.spMediaEnd.setObjectName(_fromUtf8("spMediaEnd"))
        self.grSectionEdit.addWidget(self.spMediaEnd, 1, 1, 1, 1)
        self.lblMediaStart = QtGui.QLabel(self.layoutWidget)
        self.lblMediaStart.setObjectName(_fromUtf8("lblMediaStart"))
        self.grSectionEdit.addWidget(self.lblMediaStart, 0, 0, 1, 1)
        self.pteSectionNote = QtGui.QPlainTextEdit(self.layoutWidget)
        self.pteSectionNote.setMinimumSize(QtCore.QSize(350, 80))
        self.pteSectionNote.setMaximumSize(QtCore.QSize(350, 80))
        self.pteSectionNote.setObjectName(_fromUtf8("pteSectionNote"))
        self.grSectionEdit.addWidget(self.pteSectionNote, 8, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.layoutWidget)
        self.lblCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.grSectionEdit.addWidget(self.lblCode, 2, 0, 1, 1)
        self.tabSectionContent.addTab(self.tpDetails, _fromUtf8(""))
        self.tpSectionText = QtGui.QWidget()
        self.tpSectionText.setObjectName(_fromUtf8("tpSectionText"))
        self.pteSectionText = QtGui.QPlainTextEdit(self.tpSectionText)
        self.pteSectionText.setGeometry(QtCore.QRect(3, 4, 471, 393))
        self.pteSectionText.setMinimumSize(QtCore.QSize(265, 0))
        self.pteSectionText.setObjectName(_fromUtf8("pteSectionText"))
        self.tabSectionContent.addTab(self.tpSectionText, _fromUtf8(""))
        self.hlSectionInfo.addWidget(self.tabSectionContent)
        self.vlConductInterview.addLayout(self.hlSectionInfo)
        self.hlSectionActions = QtGui.QHBoxLayout()
        self.hlSectionActions.setObjectName(_fromUtf8("hlSectionActions"))
        self.pbSaveSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbSaveSection.setEnabled(False)
        self.pbSaveSection.setObjectName(_fromUtf8("pbSaveSection"))
        self.hlSectionActions.addWidget(self.pbSaveSection)
        self.pbCancelSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbCancelSection.setEnabled(False)
        self.pbCancelSection.setObjectName(_fromUtf8("pbCancelSection"))
        self.hlSectionActions.addWidget(self.pbCancelSection)
        self.pbDeleteSection = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbDeleteSection.setEnabled(False)
        self.pbDeleteSection.setObjectName(_fromUtf8("pbDeleteSection"))
        self.hlSectionActions.addWidget(self.pbDeleteSection)
        self.pbClose = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlSectionActions.addWidget(self.pbClose)
        self.vlConductInterview.addLayout(self.hlSectionActions)
        self.hlBelowToolBar_2 = QtGui.QFrame(self.dcwLMB)
        self.hlBelowToolBar_2.setGeometry(QtCore.QRect(0, 130, 589, 16))
        self.hlBelowToolBar_2.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowToolBar_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowToolBar_2.setObjectName(_fromUtf8("hlBelowToolBar_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.dcwLMB)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 131))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.flProjectInfo = QtGui.QFormLayout()
        self.flProjectInfo.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flProjectInfo.setObjectName(_fromUtf8("flProjectInfo"))
        self.leProjectCode = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.leProjectCode.setEnabled(False)
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.flProjectInfo.setWidget(0, QtGui.QFormLayout.FieldRole, self.leProjectCode)
        self.lblInterview = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblInterview.setObjectName(_fromUtf8("lblInterview"))
        self.flProjectInfo.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblInterview)
        self.cbInterviewSelection = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbInterviewSelection.setObjectName(_fromUtf8("cbInterviewSelection"))
        self.flProjectInfo.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbInterviewSelection)
        self.lblParticipants = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.flProjectInfo.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblParticipants)
        self.pteParticipants = QtGui.QPlainTextEdit(self.horizontalLayoutWidget)
        self.pteParticipants.setEnabled(False)
        self.pteParticipants.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pteParticipants.setObjectName(_fromUtf8("pteParticipants"))
        self.flProjectInfo.setWidget(2, QtGui.QFormLayout.FieldRole, self.pteParticipants)
        self.lblProjectCode = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblProjectCode.setObjectName(_fromUtf8("lblProjectCode"))
        self.flProjectInfo.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblProjectCode)
        self.horizontalLayout.addLayout(self.flProjectInfo)
        self.flMapLayers = QtGui.QFormLayout()
        self.flMapLayers.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flMapLayers.setObjectName(_fromUtf8("flMapLayers"))
        self.lblBase = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblBase.setObjectName(_fromUtf8("lblBase"))
        self.flMapLayers.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblBase)
        self.cbBase = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbBase.setMinimumSize(QtCore.QSize(135, 0))
        self.cbBase.setObjectName(_fromUtf8("cbBase"))
        self.flMapLayers.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbBase)
        self.lblReferenceLayer = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblReferenceLayer.setObjectName(_fromUtf8("lblReferenceLayer"))
        self.flMapLayers.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblReferenceLayer)
        self.cbBoundary = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbBoundary.setObjectName(_fromUtf8("cbBoundary"))
        self.cbBoundary.addItem(_fromUtf8(""))
        self.cbBoundary.addItem(_fromUtf8(""))
        self.flMapLayers.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbBoundary)
        self.lblBaseLayer = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblBaseLayer.setObjectName(_fromUtf8("lblBaseLayer"))
        self.flMapLayers.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblBaseLayer)
        self.cbReference = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbReference.setObjectName(_fromUtf8("cbReference"))
        self.cbReference.addItem(_fromUtf8(""))
        self.cbReference.addItem(_fromUtf8(""))
        self.flMapLayers.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbReference)
        self.horizontalLayout.addLayout(self.flMapLayers)
        mapbioTranscriber.setWidget(self.dcwLMB)

        self.retranslateUi(mapbioTranscriber)
        self.tabSectionContent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioTranscriber)
        mapbioTranscriber.setTabOrder(self.leProjectCode, self.cbInterviewSelection)
        mapbioTranscriber.setTabOrder(self.cbInterviewSelection, self.pteParticipants)
        mapbioTranscriber.setTabOrder(self.pteParticipants, self.cbBase)
        mapbioTranscriber.setTabOrder(self.cbBase, self.cbBoundary)
        mapbioTranscriber.setTabOrder(self.cbBoundary, self.cbReference)
        mapbioTranscriber.setTabOrder(self.cbReference, self.tbPan)
        mapbioTranscriber.setTabOrder(self.tbPan, self.tbPoint)
        mapbioTranscriber.setTabOrder(self.tbPoint, self.tbLine)
        mapbioTranscriber.setTabOrder(self.tbLine, self.tbPolygon)
        mapbioTranscriber.setTabOrder(self.tbPolygon, self.tbEdit)
        mapbioTranscriber.setTabOrder(self.tbEdit, self.tbMove)
        mapbioTranscriber.setTabOrder(self.tbMove, self.tbNonSpatial)
        mapbioTranscriber.setTabOrder(self.tbNonSpatial, self.tbMediaPlay)
        mapbioTranscriber.setTabOrder(self.tbMediaPlay, self.hsSectionMedia)
        mapbioTranscriber.setTabOrder(self.hsSectionMedia, self.tbAudioSettings)
        mapbioTranscriber.setTabOrder(self.tbAudioSettings, self.lwSectionList)
        mapbioTranscriber.setTabOrder(self.lwSectionList, self.lwProjectCodes)
        mapbioTranscriber.setTabOrder(self.lwProjectCodes, self.tabSectionContent)
        mapbioTranscriber.setTabOrder(self.tabSectionContent, self.spMediaStart)
        mapbioTranscriber.setTabOrder(self.spMediaStart, self.spMediaEnd)
        mapbioTranscriber.setTabOrder(self.spMediaEnd, self.leCode)
        mapbioTranscriber.setTabOrder(self.leCode, self.cbSectionSecurity)
        mapbioTranscriber.setTabOrder(self.cbSectionSecurity, self.pteTags)
        mapbioTranscriber.setTabOrder(self.pteTags, self.cbFeatureStatus)
        mapbioTranscriber.setTabOrder(self.cbFeatureStatus, self.cbTimePeriod)
        mapbioTranscriber.setTabOrder(self.cbTimePeriod, self.cbAnnualVariation)
        mapbioTranscriber.setTabOrder(self.cbAnnualVariation, self.pteSectionNote)
        mapbioTranscriber.setTabOrder(self.pteSectionNote, self.pteSectionText)
        mapbioTranscriber.setTabOrder(self.pteSectionText, self.pbSaveSection)
        mapbioTranscriber.setTabOrder(self.pbSaveSection, self.pbCancelSection)
        mapbioTranscriber.setTabOrder(self.pbCancelSection, self.pbDeleteSection)
        mapbioTranscriber.setTabOrder(self.pbDeleteSection, self.pbClose)

    def retranslateUi(self, mapbioTranscriber):
        self.tbPan.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Navigate the Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPoint.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a point for the selected section", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a line for the selection section", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Place a polygon for the selected section", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Edit the selected feature", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Move the selected feature", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Insert a new section after the selected section", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setText(QtGui.QApplication.translate("mapbioTranscriber", "NS", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMediaPlay.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Play / Pause Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Select Playback Device", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setText(QtGui.QApplication.translate("mapbioTranscriber", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionList.setText(QtGui.QApplication.translate("mapbioTranscriber", "Sections", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodeList.setText(QtGui.QApplication.translate("mapbioTranscriber", "Code List", None, QtGui.QApplication.UnicodeUTF8))
        self.lwProjectCodes.setSortingEnabled(False)
        self.cbTimePeriod.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Is Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(2, QtGui.QApplication.translate("mapbioTranscriber", "From Section #", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAnnualVariation.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(2, QtGui.QApplication.translate("mapbioTranscriber", "Restricted", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(3, QtGui.QApplication.translate("mapbioTranscriber", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpatialFeature.setText(QtGui.QApplication.translate("mapbioTranscriber", "Spatial Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTags.setText(QtGui.QApplication.translate("mapbioTranscriber", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionNote.setText(QtGui.QApplication.translate("mapbioTranscriber", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAnnualVariation.setText(QtGui.QApplication.translate("mapbioTranscriber", "Annual Var.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimePeriod.setText(QtGui.QApplication.translate("mapbioTranscriber", "Use Period", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSecurity.setText(QtGui.QApplication.translate("mapbioTranscriber", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMediaEnd.setText(QtGui.QApplication.translate("mapbioTranscriber", "Media End", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMediaStart.setText(QtGui.QApplication.translate("mapbioTranscriber", "Media Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("mapbioTranscriber", "Content Code", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSectionContent.setTabText(self.tabSectionContent.indexOf(self.tpDetails), QtGui.QApplication.translate("mapbioTranscriber", "Section Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSectionContent.setTabText(self.tabSectionContent.indexOf(self.tpSectionText), QtGui.QApplication.translate("mapbioTranscriber", "Section Text", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Save Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Cancel Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setToolTip(QtGui.QApplication.translate("mapbioTranscriber", "Delete Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setText(QtGui.QApplication.translate("mapbioTranscriber", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("mapbioTranscriber", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterview.setText(QtGui.QApplication.translate("mapbioTranscriber", "Select Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipants.setText(QtGui.QApplication.translate("mapbioTranscriber", "Participant(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectCode.setText(QtGui.QApplication.translate("mapbioTranscriber", "Project Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBase.setText(QtGui.QApplication.translate("mapbioTranscriber", "Base Map", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReferenceLayer.setText(QtGui.QApplication.translate("mapbioTranscriber", "Project Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.cbBoundary.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.cbBoundary.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBaseLayer.setText(QtGui.QApplication.translate("mapbioTranscriber", "Reference Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbReference.setItemText(0, QtGui.QApplication.translate("mapbioTranscriber", "Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.cbReference.setItemText(1, QtGui.QApplication.translate("mapbioTranscriber", "Visible", None, QtGui.QApplication.UnicodeUTF8))

