# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_collector.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapbioCollector(object):
    def setupUi(self, mapbioCollector):
        mapbioCollector.setObjectName(_fromUtf8("mapbioCollector"))
        mapbioCollector.setEnabled(True)
        mapbioCollector.resize(405, 620)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapbioCollector.sizePolicy().hasHeightForWidth())
        mapbioCollector.setSizePolicy(sizePolicy)
        mapbioCollector.setMinimumSize(QtCore.QSize(405, 620))
        mapbioCollector.setMaximumSize(QtCore.QSize(524287, 524287))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("interview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapbioCollector.setWindowIcon(icon)
        mapbioCollector.setStyleSheet(_fromUtf8(""))
        mapbioCollector.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        mapbioCollector.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        mapbioCollector.setWindowTitle(_fromUtf8("LOUIS Map Biographer"))
        self.dcwLMB = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcwLMB.sizePolicy().hasHeightForWidth())
        self.dcwLMB.setSizePolicy(sizePolicy)
        self.dcwLMB.setMinimumSize(QtCore.QSize(405, 0))
        self.dcwLMB.setObjectName(_fromUtf8("dcwLMB"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dcwLMB)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frInterviewActions = QtGui.QFrame(self.dcwLMB)
        self.frInterviewActions.setObjectName(_fromUtf8("frInterviewActions"))
        self.hlInterviewActions = QtGui.QHBoxLayout(self.frInterviewActions)
        self.hlInterviewActions.setMargin(0)
        self.hlInterviewActions.setSpacing(1)
        self.hlInterviewActions.setObjectName(_fromUtf8("hlInterviewActions"))
        self.pbStart = QtGui.QPushButton(self.frInterviewActions)
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        self.hlInterviewActions.addWidget(self.pbStart)
        self.pbImportFeatures = QtGui.QPushButton(self.frInterviewActions)
        self.pbImportFeatures.setEnabled(False)
        self.pbImportFeatures.setObjectName(_fromUtf8("pbImportFeatures"))
        self.hlInterviewActions.addWidget(self.pbImportFeatures)
        self.pbImportTranscript = QtGui.QPushButton(self.frInterviewActions)
        self.pbImportTranscript.setEnabled(False)
        self.pbImportTranscript.setObjectName(_fromUtf8("pbImportTranscript"))
        self.hlInterviewActions.addWidget(self.pbImportTranscript)
        self.pbImportAudio = QtGui.QPushButton(self.frInterviewActions)
        self.pbImportAudio.setEnabled(False)
        self.pbImportAudio.setObjectName(_fromUtf8("pbImportAudio"))
        self.hlInterviewActions.addWidget(self.pbImportAudio)
        self.pbRenumberSections = QtGui.QPushButton(self.frInterviewActions)
        self.pbRenumberSections.setEnabled(False)
        self.pbRenumberSections.setText(_fromUtf8("Renumber"))
        self.pbRenumberSections.setObjectName(_fromUtf8("pbRenumberSections"))
        self.hlInterviewActions.addWidget(self.pbRenumberSections)
        self.pbPause = QtGui.QPushButton(self.frInterviewActions)
        self.pbPause.setEnabled(False)
        self.pbPause.setObjectName(_fromUtf8("pbPause"))
        self.hlInterviewActions.addWidget(self.pbPause)
        self.pbFinish = QtGui.QPushButton(self.frInterviewActions)
        self.pbFinish.setEnabled(False)
        self.pbFinish.setObjectName(_fromUtf8("pbFinish"))
        self.hlInterviewActions.addWidget(self.pbFinish)
        self.gridLayout_5.addWidget(self.frInterviewActions, 1, 0, 1, 1)
        self.frSectionControls = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frSectionControls.sizePolicy().hasHeightForWidth())
        self.frSectionControls.setSizePolicy(sizePolicy)
        self.frSectionControls.setMinimumSize(QtCore.QSize(0, 220))
        self.frSectionControls.setFrameShape(QtGui.QFrame.NoFrame)
        self.frSectionControls.setFrameShadow(QtGui.QFrame.Plain)
        self.frSectionControls.setLineWidth(0)
        self.frSectionControls.setObjectName(_fromUtf8("frSectionControls"))
        self.gridLayout = QtGui.QGridLayout(self.frSectionControls)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hlSectionControls = QtGui.QHBoxLayout()
        self.hlSectionControls.setObjectName(_fromUtf8("hlSectionControls"))
        self.vlSectionList = QtGui.QVBoxLayout()
        self.vlSectionList.setObjectName(_fromUtf8("vlSectionList"))
        self.lblSectionList = QtGui.QLabel(self.frSectionControls)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lblSectionList.setFont(font)
        self.lblSectionList.setObjectName(_fromUtf8("lblSectionList"))
        self.vlSectionList.addWidget(self.lblSectionList)
        self.lwSectionList = QtGui.QListWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSectionList.sizePolicy().hasHeightForWidth())
        self.lwSectionList.setSizePolicy(sizePolicy)
        self.lwSectionList.setMinimumSize(QtCore.QSize(100, 180))
        self.lwSectionList.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lwSectionList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSectionList.setObjectName(_fromUtf8("lwSectionList"))
        self.vlSectionList.addWidget(self.lwSectionList)
        self.hlSectionOrderButtons = QtGui.QHBoxLayout()
        self.hlSectionOrderButtons.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hlSectionOrderButtons.setSpacing(2)
        self.hlSectionOrderButtons.setObjectName(_fromUtf8("hlSectionOrderButtons"))
        self.tbMoveUp = QtGui.QToolButton(self.frSectionControls)
        self.tbMoveUp.setEnabled(False)
        self.tbMoveUp.setArrowType(QtCore.Qt.UpArrow)
        self.tbMoveUp.setObjectName(_fromUtf8("tbMoveUp"))
        self.hlSectionOrderButtons.addWidget(self.tbMoveUp)
        self.tbMoveDown = QtGui.QToolButton(self.frSectionControls)
        self.tbMoveDown.setEnabled(False)
        self.tbMoveDown.setArrowType(QtCore.Qt.DownArrow)
        self.tbMoveDown.setObjectName(_fromUtf8("tbMoveDown"))
        self.hlSectionOrderButtons.addWidget(self.tbMoveDown)
        self.tbSort = QtGui.QToolButton(self.frSectionControls)
        self.tbSort.setEnabled(False)
        self.tbSort.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbSort.setArrowType(QtCore.Qt.NoArrow)
        self.tbSort.setObjectName(_fromUtf8("tbSort"))
        self.hlSectionOrderButtons.addWidget(self.tbSort)
        self.vlSectionList.addLayout(self.hlSectionOrderButtons)
        self.lblCodeList = QtGui.QLabel(self.frSectionControls)
        self.lblCodeList.setMinimumSize(QtCore.QSize(100, 0))
        self.lblCodeList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCodeList.setObjectName(_fromUtf8("lblCodeList"))
        self.vlSectionList.addWidget(self.lblCodeList)
        self.lwProjectCodes = QtGui.QListWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwProjectCodes.sizePolicy().hasHeightForWidth())
        self.lwProjectCodes.setSizePolicy(sizePolicy)
        self.lwProjectCodes.setMinimumSize(QtCore.QSize(100, 100))
        self.lwProjectCodes.setMaximumSize(QtCore.QSize(100, 200))
        self.lwProjectCodes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lwProjectCodes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwProjectCodes.setProperty("showDropIndicator", False)
        self.lwProjectCodes.setDragEnabled(False)
        self.lwProjectCodes.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lwProjectCodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwProjectCodes.setProperty("isWrapping", True)
        self.lwProjectCodes.setViewMode(QtGui.QListView.IconMode)
        self.lwProjectCodes.setUniformItemSizes(False)
        self.lwProjectCodes.setObjectName(_fromUtf8("lwProjectCodes"))
        self.vlSectionList.addWidget(self.lwProjectCodes)
        self.hlSectionControls.addLayout(self.vlSectionList)
        self.vlSectionTabAndButtons = QtGui.QVBoxLayout()
        self.vlSectionTabAndButtons.setObjectName(_fromUtf8("vlSectionTabAndButtons"))
        self.twSectionContent = QtGui.QTabWidget(self.frSectionControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twSectionContent.sizePolicy().hasHeightForWidth())
        self.twSectionContent.setSizePolicy(sizePolicy)
        self.twSectionContent.setMinimumSize(QtCore.QSize(200, 300))
        self.twSectionContent.setToolTip(_fromUtf8(""))
        self.twSectionContent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twSectionContent.setTabPosition(QtGui.QTabWidget.North)
        self.twSectionContent.setTabShape(QtGui.QTabWidget.Rounded)
        self.twSectionContent.setObjectName(_fromUtf8("twSectionContent"))
        self.tpDetails = QtGui.QWidget()
        self.tpDetails.setObjectName(_fromUtf8("tpDetails"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tpDetails)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.saSectionEdit = QtGui.QScrollArea(self.tpDetails)
        self.saSectionEdit.setWidgetResizable(True)
        self.saSectionEdit.setObjectName(_fromUtf8("saSectionEdit"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 267, 415))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grSectionEdit = QtGui.QGridLayout()
        self.grSectionEdit.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.grSectionEdit.setVerticalSpacing(6)
        self.grSectionEdit.setObjectName(_fromUtf8("grSectionEdit"))
        self.lwTOYMonths = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.lwTOYMonths.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lwTOYMonths.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwTOYMonths.setFlow(QtGui.QListView.LeftToRight)
        self.lwTOYMonths.setProperty("isWrapping", True)
        self.lwTOYMonths.setObjectName(_fromUtf8("lwTOYMonths"))
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwTOYMonths.addItem(item)
        self.grSectionEdit.addWidget(self.lwTOYMonths, 9, 1, 1, 1)
        self.lblUPStart = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblUPStart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUPStart.setObjectName(_fromUtf8("lblUPStart"))
        self.grSectionEdit.addWidget(self.lblUPStart, 6, 0, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSecurity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.grSectionEdit.addWidget(self.lblSecurity, 2, 0, 1, 1)
        self.cbSectionSecurity = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSectionSecurity.sizePolicy().hasHeightForWidth())
        self.cbSectionSecurity.setSizePolicy(sizePolicy)
        self.cbSectionSecurity.setMinimumSize(QtCore.QSize(100, 0))
        self.cbSectionSecurity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbSectionSecurity.setObjectName(_fromUtf8("cbSectionSecurity"))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbSectionSecurity, 2, 1, 1, 1)
        self.lblContentCodes = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblContentCodes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblContentCodes.setObjectName(_fromUtf8("lblContentCodes"))
        self.grSectionEdit.addWidget(self.lblContentCodes, 3, 0, 1, 1)
        self.pteContentCodes = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.pteContentCodes.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteContentCodes.sizePolicy().hasHeightForWidth())
        self.pteContentCodes.setSizePolicy(sizePolicy)
        self.pteContentCodes.setMinimumSize(QtCore.QSize(100, 35))
        self.pteContentCodes.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteContentCodes.setObjectName(_fromUtf8("pteContentCodes"))
        self.grSectionEdit.addWidget(self.pteContentCodes, 3, 1, 1, 1)
        self.lblFeatureSource = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFeatureSource.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblFeatureSource.setObjectName(_fromUtf8("lblFeatureSource"))
        self.grSectionEdit.addWidget(self.lblFeatureSource, 4, 0, 1, 1)
        self.cbFeatureSource = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFeatureSource.sizePolicy().hasHeightForWidth())
        self.cbFeatureSource.setSizePolicy(sizePolicy)
        self.cbFeatureSource.setMinimumSize(QtCore.QSize(100, 0))
        self.cbFeatureSource.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbFeatureSource.setObjectName(_fromUtf8("cbFeatureSource"))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.cbFeatureSource.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbFeatureSource, 4, 1, 1, 1)
        self.lblUsePeriod = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblUsePeriod.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblUsePeriod.setObjectName(_fromUtf8("lblUsePeriod"))
        self.grSectionEdit.addWidget(self.lblUsePeriod, 5, 0, 1, 1)
        self.cbUsePeriod = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbUsePeriod.sizePolicy().hasHeightForWidth())
        self.cbUsePeriod.setSizePolicy(sizePolicy)
        self.cbUsePeriod.setMinimumSize(QtCore.QSize(100, 0))
        self.cbUsePeriod.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbUsePeriod.setObjectName(_fromUtf8("cbUsePeriod"))
        self.cbUsePeriod.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbUsePeriod, 5, 1, 1, 1)
        self.lblTimeOfYear = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblTimeOfYear.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTimeOfYear.setObjectName(_fromUtf8("lblTimeOfYear"))
        self.grSectionEdit.addWidget(self.lblTimeOfYear, 8, 0, 1, 1)
        self.cbTimeOfYear = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTimeOfYear.sizePolicy().hasHeightForWidth())
        self.cbTimeOfYear.setSizePolicy(sizePolicy)
        self.cbTimeOfYear.setMinimumSize(QtCore.QSize(100, 0))
        self.cbTimeOfYear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbTimeOfYear.setObjectName(_fromUtf8("cbTimeOfYear"))
        self.cbTimeOfYear.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbTimeOfYear, 8, 1, 1, 1)
        self.lblSectionTags = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSectionTags.setObjectName(_fromUtf8("lblSectionTags"))
        self.grSectionEdit.addWidget(self.lblSectionTags, 10, 0, 1, 1)
        self.pteSectionTags = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.pteSectionTags.setMinimumSize(QtCore.QSize(100, 30))
        self.pteSectionTags.setMaximumSize(QtCore.QSize(16777215, 70))
        self.pteSectionTags.setObjectName(_fromUtf8("pteSectionTags"))
        self.grSectionEdit.addWidget(self.pteSectionTags, 10, 1, 1, 1)
        self.lblSectionNote = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSectionNote.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblSectionNote.setObjectName(_fromUtf8("lblSectionNote"))
        self.grSectionEdit.addWidget(self.lblSectionNote, 11, 0, 1, 1)
        self.pteSectionNote = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteSectionNote.sizePolicy().hasHeightForWidth())
        self.pteSectionNote.setSizePolicy(sizePolicy)
        self.pteSectionNote.setMinimumSize(QtCore.QSize(100, 30))
        self.pteSectionNote.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pteSectionNote.setObjectName(_fromUtf8("pteSectionNote"))
        self.grSectionEdit.addWidget(self.pteSectionNote, 11, 1, 1, 1)
        self.deUPStart = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.deUPStart.setObjectName(_fromUtf8("deUPStart"))
        self.grSectionEdit.addWidget(self.deUPStart, 6, 1, 1, 1)
        self.lblUPEnd = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblUPEnd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUPEnd.setObjectName(_fromUtf8("lblUPEnd"))
        self.grSectionEdit.addWidget(self.lblUPEnd, 7, 0, 1, 1)
        self.deUPEnd = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.deUPEnd.setObjectName(_fromUtf8("deUPEnd"))
        self.grSectionEdit.addWidget(self.deUPEnd, 7, 1, 1, 1)
        self.lblTOYMonths = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblTOYMonths.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTOYMonths.setObjectName(_fromUtf8("lblTOYMonths"))
        self.grSectionEdit.addWidget(self.lblTOYMonths, 9, 0, 1, 1)
        self.lblCode = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setMinimumSize(QtCore.QSize(100, 0))
        self.lblCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.grSectionEdit.addWidget(self.lblCode, 0, 0, 1, 1)
        self.leCode = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCode.sizePolicy().hasHeightForWidth())
        self.leCode.setSizePolicy(sizePolicy)
        self.leCode.setMinimumSize(QtCore.QSize(50, 0))
        self.leCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leCode.setDragEnabled(False)
        self.leCode.setReadOnly(True)
        self.leCode.setObjectName(_fromUtf8("leCode"))
        self.grSectionEdit.addWidget(self.leCode, 0, 1, 1, 1)
        self.lblLegacyCode = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblLegacyCode.setObjectName(_fromUtf8("lblLegacyCode"))
        self.grSectionEdit.addWidget(self.lblLegacyCode, 1, 0, 1, 1)
        self.lblLegacyCodeValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblLegacyCodeValue.setText(_fromUtf8(""))
        self.lblLegacyCodeValue.setObjectName(_fromUtf8("lblLegacyCodeValue"))
        self.grSectionEdit.addWidget(self.lblLegacyCodeValue, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.grSectionEdit, 0, 0, 1, 1)
        self.saSectionEdit.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.saSectionEdit)
        self.twSectionContent.addTab(self.tpDetails, _fromUtf8(""))
        self.tpSectionText = QtGui.QWidget()
        self.tpSectionText.setObjectName(_fromUtf8("tpSectionText"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tpSectionText)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblMediaStart = QtGui.QLabel(self.tpSectionText)
        self.lblMediaStart.setObjectName(_fromUtf8("lblMediaStart"))
        self.gridLayout_2.addWidget(self.lblMediaStart, 0, 0, 1, 1)
        self.lblMediaEnd = QtGui.QLabel(self.tpSectionText)
        self.lblMediaEnd.setObjectName(_fromUtf8("lblMediaEnd"))
        self.gridLayout_2.addWidget(self.lblMediaEnd, 1, 0, 1, 1)
        self.lblRecordingDate = QtGui.QLabel(self.tpSectionText)
        self.lblRecordingDate.setObjectName(_fromUtf8("lblRecordingDate"))
        self.gridLayout_2.addWidget(self.lblRecordingDate, 2, 0, 1, 1)
        self.dteRecordingDate = QtGui.QDateTimeEdit(self.tpSectionText)
        self.dteRecordingDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 59)))
        self.dteRecordingDate.setDate(QtCore.QDate(2000, 1, 1))
        self.dteRecordingDate.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 59)))
        self.dteRecordingDate.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteRecordingDate.setCalendarPopup(False)
        self.dteRecordingDate.setObjectName(_fromUtf8("dteRecordingDate"))
        self.gridLayout_2.addWidget(self.dteRecordingDate, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spMediaStart = QtGui.QSpinBox(self.tpSectionText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMediaStart.sizePolicy().hasHeightForWidth())
        self.spMediaStart.setSizePolicy(sizePolicy)
        self.spMediaStart.setMinimumSize(QtCore.QSize(100, 0))
        self.spMediaStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spMediaStart.setMaximum(1000000000)
        self.spMediaStart.setObjectName(_fromUtf8("spMediaStart"))
        self.horizontalLayout_4.addWidget(self.spMediaStart)
        self.tbSetStart = QtGui.QToolButton(self.tpSectionText)
        self.tbSetStart.setObjectName(_fromUtf8("tbSetStart"))
        self.horizontalLayout_4.addWidget(self.tbSetStart)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spMediaEnd = QtGui.QSpinBox(self.tpSectionText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMediaEnd.sizePolicy().hasHeightForWidth())
        self.spMediaEnd.setSizePolicy(sizePolicy)
        self.spMediaEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.spMediaEnd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spMediaEnd.setMaximum(1000000000)
        self.spMediaEnd.setObjectName(_fromUtf8("spMediaEnd"))
        self.horizontalLayout_5.addWidget(self.spMediaEnd)
        self.tbSetEnd = QtGui.QToolButton(self.tpSectionText)
        self.tbSetEnd.setObjectName(_fromUtf8("tbSetEnd"))
        self.horizontalLayout_5.addWidget(self.tbSetEnd)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.pteSectionText = QtGui.QPlainTextEdit(self.tpSectionText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteSectionText.sizePolicy().hasHeightForWidth())
        self.pteSectionText.setSizePolicy(sizePolicy)
        self.pteSectionText.setMinimumSize(QtCore.QSize(10, 50))
        self.pteSectionText.setToolTip(_fromUtf8(""))
        self.pteSectionText.setWhatsThis(_fromUtf8(""))
        self.pteSectionText.setDocumentTitle(_fromUtf8(""))
        self.pteSectionText.setObjectName(_fromUtf8("pteSectionText"))
        self.gridLayout_7.addWidget(self.pteSectionText, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblSearch = QtGui.QLabel(self.tpSectionText)
        self.lblSearch.setObjectName(_fromUtf8("lblSearch"))
        self.horizontalLayout_6.addWidget(self.lblSearch)
        self.leSearch = QtGui.QLineEdit(self.tpSectionText)
        self.leSearch.setObjectName(_fromUtf8("leSearch"))
        self.horizontalLayout_6.addWidget(self.leSearch)
        self.tbSearchNext = QtGui.QToolButton(self.tpSectionText)
        self.tbSearchNext.setEnabled(False)
        self.tbSearchNext.setArrowType(QtCore.Qt.DownArrow)
        self.tbSearchNext.setObjectName(_fromUtf8("tbSearchNext"))
        self.horizontalLayout_6.addWidget(self.tbSearchNext)
        self.tbSearchPrevious = QtGui.QToolButton(self.tpSectionText)
        self.tbSearchPrevious.setEnabled(False)
        self.tbSearchPrevious.setArrowType(QtCore.Qt.UpArrow)
        self.tbSearchPrevious.setObjectName(_fromUtf8("tbSearchPrevious"))
        self.horizontalLayout_6.addWidget(self.tbSearchPrevious)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.tpSectionText)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_7.addWidget(self.line_5, 2, 0, 1, 1)
        self.twSectionContent.addTab(self.tpSectionText, _fromUtf8(""))
        self.tpPhotos = QtGui.QWidget()
        self.tpPhotos.setObjectName(_fromUtf8("tpPhotos"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tpPhotos)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbAddPhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbAddPhoto.setObjectName(_fromUtf8("pbAddPhoto"))
        self.horizontalLayout.addWidget(self.pbAddPhoto)
        self.pbEditPhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbEditPhoto.setEnabled(False)
        self.pbEditPhoto.setObjectName(_fromUtf8("pbEditPhoto"))
        self.horizontalLayout.addWidget(self.pbEditPhoto)
        self.pbRemovePhoto = QtGui.QPushButton(self.tpPhotos)
        self.pbRemovePhoto.setEnabled(False)
        self.pbRemovePhoto.setObjectName(_fromUtf8("pbRemovePhoto"))
        self.horizontalLayout.addWidget(self.pbRemovePhoto)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.twPhotos = QtGui.QTableWidget(self.tpPhotos)
        self.twPhotos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twPhotos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twPhotos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twPhotos.setObjectName(_fromUtf8("twPhotos"))
        self.twPhotos.setColumnCount(0)
        self.twPhotos.setRowCount(0)
        self.gridLayout_6.addWidget(self.twPhotos, 0, 0, 1, 1)
        self.twSectionContent.addTab(self.tpPhotos, _fromUtf8(""))
        self.vlSectionTabAndButtons.addWidget(self.twSectionContent)
        self.hlSectionButtons = QtGui.QHBoxLayout()
        self.hlSectionButtons.setObjectName(_fromUtf8("hlSectionButtons"))
        self.pbSaveSection = QtGui.QPushButton(self.frSectionControls)
        self.pbSaveSection.setEnabled(False)
        self.pbSaveSection.setObjectName(_fromUtf8("pbSaveSection"))
        self.hlSectionButtons.addWidget(self.pbSaveSection)
        self.pbCancelSection = QtGui.QPushButton(self.frSectionControls)
        self.pbCancelSection.setEnabled(False)
        self.pbCancelSection.setObjectName(_fromUtf8("pbCancelSection"))
        self.hlSectionButtons.addWidget(self.pbCancelSection)
        self.pbDeleteSection = QtGui.QPushButton(self.frSectionControls)
        self.pbDeleteSection.setEnabled(False)
        self.pbDeleteSection.setObjectName(_fromUtf8("pbDeleteSection"))
        self.hlSectionButtons.addWidget(self.pbDeleteSection)
        self.vlSectionTabAndButtons.addLayout(self.hlSectionButtons)
        self.hlSectionControls.addLayout(self.vlSectionTabAndButtons)
        self.gridLayout.addLayout(self.hlSectionControls, 1, 0, 1, 1)
        self.qfToolBar = QtGui.QFrame(self.frSectionControls)
        self.qfToolBar.setObjectName(_fromUtf8("qfToolBar"))
        self.vlToolBar = QtGui.QVBoxLayout(self.qfToolBar)
        self.vlToolBar.setMargin(0)
        self.vlToolBar.setSpacing(0)
        self.vlToolBar.setObjectName(_fromUtf8("vlToolBar"))
        self.lnAboveToolBar = QtGui.QFrame(self.qfToolBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnAboveToolBar.sizePolicy().hasHeightForWidth())
        self.lnAboveToolBar.setSizePolicy(sizePolicy)
        self.lnAboveToolBar.setMinimumSize(QtCore.QSize(0, 8))
        self.lnAboveToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.lnAboveToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnAboveToolBar.setObjectName(_fromUtf8("lnAboveToolBar"))
        self.vlToolBar.addWidget(self.lnAboveToolBar)
        self.hlButtons = QtGui.QHBoxLayout()
        self.hlButtons.setSpacing(0)
        self.hlButtons.setObjectName(_fromUtf8("hlButtons"))
        self.tbPan = QtGui.QToolButton(self.qfToolBar)
        self.tbPan.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPan.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPan.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPan.setIcon(icon1)
        self.tbPan.setCheckable(True)
        self.tbPan.setAutoRaise(False)
        self.tbPan.setObjectName(_fromUtf8("tbPan"))
        self.hlButtons.addWidget(self.tbPan)
        self.line_3 = QtGui.QFrame(self.qfToolBar)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.hlButtons.addWidget(self.line_3)
        self.tbPoint = QtGui.QToolButton(self.qfToolBar)
        self.tbPoint.setEnabled(False)
        self.tbPoint.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPoint.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPoint.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tbPoint.setIcon(icon2)
        self.tbPoint.setCheckable(True)
        self.tbPoint.setChecked(False)
        self.tbPoint.setAutoRaise(False)
        self.tbPoint.setArrowType(QtCore.Qt.NoArrow)
        self.tbPoint.setObjectName(_fromUtf8("tbPoint"))
        self.hlButtons.addWidget(self.tbPoint)
        self.tbLine = QtGui.QToolButton(self.qfToolBar)
        self.tbLine.setEnabled(False)
        self.tbLine.setMinimumSize(QtCore.QSize(28, 28))
        self.tbLine.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLine.setIcon(icon3)
        self.tbLine.setCheckable(True)
        self.tbLine.setObjectName(_fromUtf8("tbLine"))
        self.hlButtons.addWidget(self.tbLine)
        self.tbPolygon = QtGui.QToolButton(self.qfToolBar)
        self.tbPolygon.setEnabled(False)
        self.tbPolygon.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPolygon.setMaximumSize(QtCore.QSize(28, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPolygon.setIcon(icon4)
        self.tbPolygon.setCheckable(True)
        self.tbPolygon.setObjectName(_fromUtf8("tbPolygon"))
        self.hlButtons.addWidget(self.tbPolygon)
        self.tbEdit = QtGui.QToolButton(self.qfToolBar)
        self.tbEdit.setEnabled(False)
        self.tbEdit.setMinimumSize(QtCore.QSize(28, 28))
        self.tbEdit.setMaximumSize(QtCore.QSize(28, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("edit_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEdit.setIcon(icon5)
        self.tbEdit.setCheckable(True)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.hlButtons.addWidget(self.tbEdit)
        self.tbMove = QtGui.QToolButton(self.qfToolBar)
        self.tbMove.setEnabled(False)
        self.tbMove.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMove.setMaximumSize(QtCore.QSize(28, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("edit_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMove.setIcon(icon6)
        self.tbMove.setCheckable(True)
        self.tbMove.setObjectName(_fromUtf8("tbMove"))
        self.hlButtons.addWidget(self.tbMove)
        self.tbNonSpatial = QtGui.QToolButton(self.qfToolBar)
        self.tbNonSpatial.setEnabled(False)
        self.tbNonSpatial.setMinimumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.tbNonSpatial.setFont(font)
        self.tbNonSpatial.setAutoFillBackground(False)
        self.tbNonSpatial.setCheckable(False)
        self.tbNonSpatial.setObjectName(_fromUtf8("tbNonSpatial"))
        self.hlButtons.addWidget(self.tbNonSpatial)
        self.line_4 = QtGui.QFrame(self.qfToolBar)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.hlButtons.addWidget(self.line_4)
        self.tbZoomIn = QtGui.QToolButton(self.qfToolBar)
        self.tbZoomIn.setMinimumSize(QtCore.QSize(28, 28))
        self.tbZoomIn.setMaximumSize(QtCore.QSize(28, 28))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("zoom_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomIn.setIcon(icon7)
        self.tbZoomIn.setObjectName(_fromUtf8("tbZoomIn"))
        self.hlButtons.addWidget(self.tbZoomIn)
        self.tbZoomOut = QtGui.QToolButton(self.qfToolBar)
        self.tbZoomOut.setMinimumSize(QtCore.QSize(28, 28))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomOut.setIcon(icon8)
        self.tbZoomOut.setObjectName(_fromUtf8("tbZoomOut"))
        self.hlButtons.addWidget(self.tbZoomOut)
        self.tbZoomData = QtGui.QToolButton(self.qfToolBar)
        self.tbZoomData.setMinimumSize(QtCore.QSize(28, 28))
        self.tbZoomData.setMaximumSize(QtCore.QSize(28, 28))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("zoom_data.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomData.setIcon(icon9)
        self.tbZoomData.setArrowType(QtCore.Qt.NoArrow)
        self.tbZoomData.setObjectName(_fromUtf8("tbZoomData"))
        self.hlButtons.addWidget(self.tbZoomData)
        self.tbZoomArea = QtGui.QToolButton(self.qfToolBar)
        self.tbZoomArea.setMinimumSize(QtCore.QSize(28, 28))
        self.tbZoomArea.setMaximumSize(QtCore.QSize(28, 28))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("zoom_area.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomArea.setIcon(icon10)
        self.tbZoomArea.setObjectName(_fromUtf8("tbZoomArea"))
        self.hlButtons.addWidget(self.tbZoomArea)
        self.tbSketchMode = QtGui.QToolButton(self.qfToolBar)
        self.tbSketchMode.setMinimumSize(QtCore.QSize(28, 28))
        self.tbSketchMode.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.tbSketchMode.setFont(font)
        self.tbSketchMode.setCheckable(True)
        self.tbSketchMode.setObjectName(_fromUtf8("tbSketchMode"))
        self.hlButtons.addWidget(self.tbSketchMode)
        self.vlToolBar.addLayout(self.hlButtons)
        self.line = QtGui.QFrame(self.qfToolBar)
        self.line.setMinimumSize(QtCore.QSize(0, 8))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.vlToolBar.addWidget(self.line)
        self.hlInterviewTools = QtGui.QHBoxLayout()
        self.hlInterviewTools.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hlInterviewTools.setSpacing(2)
        self.hlInterviewTools.setObjectName(_fromUtf8("hlInterviewTools"))
        self.lblTimeOfDay = QtGui.QLabel(self.qfToolBar)
        self.lblTimeOfDay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimeOfDay.setObjectName(_fromUtf8("lblTimeOfDay"))
        self.hlInterviewTools.addWidget(self.lblTimeOfDay)
        self.vlLeftOfTimer = QtGui.QFrame(self.qfToolBar)
        self.vlLeftOfTimer.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfTimer.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfTimer.setObjectName(_fromUtf8("vlLeftOfTimer"))
        self.hlInterviewTools.addWidget(self.vlLeftOfTimer)
        self.lblTimer = QtGui.QLabel(self.qfToolBar)
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName(_fromUtf8("lblTimer"))
        self.hlInterviewTools.addWidget(self.lblTimer)
        self.line_2 = QtGui.QFrame(self.qfToolBar)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.hlInterviewTools.addWidget(self.line_2)
        self.tbMediaPlay = QtGui.QToolButton(self.qfToolBar)
        self.tbMediaPlay.setEnabled(False)
        self.tbMediaPlay.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setMaximumSize(QtCore.QSize(28, 28))
        self.tbMediaPlay.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("media_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMediaPlay.setIcon(icon11)
        self.tbMediaPlay.setCheckable(False)
        self.tbMediaPlay.setObjectName(_fromUtf8("tbMediaPlay"))
        self.hlInterviewTools.addWidget(self.tbMediaPlay)
        self.hsSectionMedia = QtGui.QSlider(self.qfToolBar)
        self.hsSectionMedia.setEnabled(False)
        self.hsSectionMedia.setMaximumSize(QtCore.QSize(800, 16777215))
        self.hsSectionMedia.setSingleStep(1)
        self.hsSectionMedia.setOrientation(QtCore.Qt.Horizontal)
        self.hsSectionMedia.setObjectName(_fromUtf8("hsSectionMedia"))
        self.hlInterviewTools.addWidget(self.hsSectionMedia)
        self.vlToolBar.addLayout(self.hlInterviewTools)
        self.lnBelowToolBar = QtGui.QFrame(self.qfToolBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnBelowToolBar.sizePolicy().hasHeightForWidth())
        self.lnBelowToolBar.setSizePolicy(sizePolicy)
        self.lnBelowToolBar.setMinimumSize(QtCore.QSize(0, 8))
        self.lnBelowToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.lnBelowToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnBelowToolBar.setObjectName(_fromUtf8("lnBelowToolBar"))
        self.vlToolBar.addWidget(self.lnBelowToolBar)
        self.gridLayout.addWidget(self.qfToolBar, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frSectionControls, 2, 0, 1, 1)
        self.frMapOptions = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMapOptions.sizePolicy().hasHeightForWidth())
        self.frMapOptions.setSizePolicy(sizePolicy)
        self.frMapOptions.setMinimumSize(QtCore.QSize(0, 50))
        self.frMapOptions.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frMapOptions.setFrameShape(QtGui.QFrame.NoFrame)
        self.frMapOptions.setFrameShadow(QtGui.QFrame.Plain)
        self.frMapOptions.setLineWidth(0)
        self.frMapOptions.setObjectName(_fromUtf8("frMapOptions"))
        self.formLayout = QtGui.QFormLayout(self.frMapOptions)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbFeatures = QtGui.QCheckBox(self.frMapOptions)
        self.cbFeatures.setObjectName(_fromUtf8("cbFeatures"))
        self.verticalLayout.addWidget(self.cbFeatures)
        self.cbLabels = QtGui.QCheckBox(self.frMapOptions)
        self.cbLabels.setObjectName(_fromUtf8("cbLabels"))
        self.verticalLayout.addWidget(self.cbLabels)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cbReference = QtGui.QCheckBox(self.frMapOptions)
        self.cbReference.setObjectName(_fromUtf8("cbReference"))
        self.verticalLayout_2.addWidget(self.cbReference)
        self.cbBoundary = QtGui.QCheckBox(self.frMapOptions)
        self.cbBoundary.setObjectName(_fromUtf8("cbBoundary"))
        self.verticalLayout_2.addWidget(self.cbBoundary)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.verticalLayout_2)
        self.gridLayout_5.addWidget(self.frMapOptions, 0, 0, 1, 1)
        mapbioCollector.setWidget(self.dcwLMB)

        self.retranslateUi(mapbioCollector)
        self.twSectionContent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioCollector)
        mapbioCollector.setTabOrder(self.pbStart, self.pbImportFeatures)
        mapbioCollector.setTabOrder(self.pbImportFeatures, self.pbImportAudio)
        mapbioCollector.setTabOrder(self.pbImportAudio, self.pbRenumberSections)
        mapbioCollector.setTabOrder(self.pbRenumberSections, self.pbPause)
        mapbioCollector.setTabOrder(self.pbPause, self.pbFinish)
        mapbioCollector.setTabOrder(self.pbFinish, self.lwSectionList)
        mapbioCollector.setTabOrder(self.lwSectionList, self.tbMoveUp)
        mapbioCollector.setTabOrder(self.tbMoveUp, self.tbMoveDown)
        mapbioCollector.setTabOrder(self.tbMoveDown, self.lwProjectCodes)
        mapbioCollector.setTabOrder(self.lwProjectCodes, self.twSectionContent)
        mapbioCollector.setTabOrder(self.twSectionContent, self.cbSectionSecurity)
        mapbioCollector.setTabOrder(self.cbSectionSecurity, self.pteSectionText)
        mapbioCollector.setTabOrder(self.pteSectionText, self.twPhotos)
        mapbioCollector.setTabOrder(self.twPhotos, self.pbAddPhoto)
        mapbioCollector.setTabOrder(self.pbAddPhoto, self.pbEditPhoto)
        mapbioCollector.setTabOrder(self.pbEditPhoto, self.pbRemovePhoto)
        mapbioCollector.setTabOrder(self.pbRemovePhoto, self.pbSaveSection)
        mapbioCollector.setTabOrder(self.pbSaveSection, self.pbCancelSection)
        mapbioCollector.setTabOrder(self.pbCancelSection, self.pbDeleteSection)

    def retranslateUi(self, mapbioCollector):
        self.pbStart.setToolTip(_translate("mapbioCollector", "Start recording an interview", None))
        self.pbStart.setText(_translate("mapbioCollector", "Start", None))
        self.pbImportFeatures.setToolTip(_translate("mapbioCollector", "Import map features and add to end of interview", None))
        self.pbImportFeatures.setText(_translate("mapbioCollector", "Features", None))
        self.pbImportTranscript.setToolTip(_translate("mapbioCollector", "Import transcript and link to features or create new sections", None))
        self.pbImportTranscript.setText(_translate("mapbioCollector", "Transcript", None))
        self.pbImportAudio.setToolTip(_translate("mapbioCollector", "Import audio file and replace existing file", None))
        self.pbImportAudio.setText(_translate("mapbioCollector", "Audio", None))
        self.pbRenumberSections.setToolTip(_translate("mapbioCollector", "Renumber sections based on sequence order", None))
        self.pbPause.setToolTip(_translate("mapbioCollector", "Pause or continue an interview", None))
        self.pbPause.setText(_translate("mapbioCollector", "Pause", None))
        self.pbFinish.setToolTip(_translate("mapbioCollector", "Finish an interview", None))
        self.pbFinish.setText(_translate("mapbioCollector", "Finish", None))
        self.lblSectionList.setText(_translate("mapbioCollector", "Sections", None))
        self.lwSectionList.setToolTip(_translate("mapbioCollector", "Time ordered list of sections in interview", None))
        self.tbMoveUp.setToolTip(_translate("mapbioCollector", "Move section up", None))
        self.tbMoveUp.setText(_translate("mapbioCollector", "...", None))
        self.tbMoveDown.setToolTip(_translate("mapbioCollector", "Move section down", None))
        self.tbMoveDown.setText(_translate("mapbioCollector", "...", None))
        self.tbSort.setToolTip(_translate("mapbioCollector", "Reorder sections", None))
        self.tbSort.setText(_translate("mapbioCollector", "Ro", None))
        self.lblCodeList.setText(_translate("mapbioCollector", "Code List", None))
        self.lwProjectCodes.setToolTip(_translate("mapbioCollector", "List of content codes. Click to select and hold Ctrl + click to set content code", None))
        self.lwProjectCodes.setSortingEnabled(False)
        __sortingEnabled = self.lwTOYMonths.isSortingEnabled()
        self.lwTOYMonths.setSortingEnabled(False)
        item = self.lwTOYMonths.item(0)
        item.setText(_translate("mapbioCollector", "1", None))
        item = self.lwTOYMonths.item(1)
        item.setText(_translate("mapbioCollector", "2", None))
        item = self.lwTOYMonths.item(2)
        item.setText(_translate("mapbioCollector", "3", None))
        item = self.lwTOYMonths.item(3)
        item.setText(_translate("mapbioCollector", "4", None))
        item = self.lwTOYMonths.item(4)
        item.setText(_translate("mapbioCollector", "5", None))
        item = self.lwTOYMonths.item(5)
        item.setText(_translate("mapbioCollector", "6", None))
        item = self.lwTOYMonths.item(6)
        item.setText(_translate("mapbioCollector", "7", None))
        item = self.lwTOYMonths.item(7)
        item.setText(_translate("mapbioCollector", "8", None))
        item = self.lwTOYMonths.item(8)
        item.setText(_translate("mapbioCollector", "9", None))
        item = self.lwTOYMonths.item(9)
        item.setText(_translate("mapbioCollector", "10", None))
        item = self.lwTOYMonths.item(10)
        item.setText(_translate("mapbioCollector", "11", None))
        item = self.lwTOYMonths.item(11)
        item.setText(_translate("mapbioCollector", "12", None))
        self.lwTOYMonths.setSortingEnabled(__sortingEnabled)
        self.lblUPStart.setText(_translate("mapbioCollector", "Start Date", None))
        self.lblSecurity.setText(_translate("mapbioCollector", "Security", None))
        self.cbSectionSecurity.setToolTip(_translate("mapbioCollector", "Set security setting for this section", None))
        self.cbSectionSecurity.setItemText(0, _translate("mapbioCollector", "Public", None))
        self.cbSectionSecurity.setItemText(1, _translate("mapbioCollector", "Community", None))
        self.cbSectionSecurity.setItemText(2, _translate("mapbioCollector", "Private", None))
        self.lblContentCodes.setText(_translate("mapbioCollector", "Content Codes", None))
        self.pteContentCodes.setToolTip(_translate("mapbioCollector", "List of content codes", None))
        self.lblFeatureSource.setText(_translate("mapbioCollector", "Spatial Feature", None))
        self.cbFeatureSource.setToolTip(_translate("mapbioCollector", "Spatial feature type", None))
        self.cbFeatureSource.setItemText(0, _translate("mapbioCollector", "None", None))
        self.cbFeatureSource.setItemText(1, _translate("mapbioCollector", "Is Unique", None))
        self.cbFeatureSource.setItemText(2, _translate("mapbioCollector", "From Section #", None))
        self.lblUsePeriod.setText(_translate("mapbioCollector", "Use Period", None))
        self.cbUsePeriod.setToolTip(_translate("mapbioCollector", "Set time of use", None))
        self.cbUsePeriod.setItemText(0, _translate("mapbioCollector", "Unknown", None))
        self.lblTimeOfYear.setText(_translate("mapbioCollector", "Time of Year", None))
        self.cbTimeOfYear.setToolTip(_translate("mapbioCollector", "Set time of year this area is used", None))
        self.cbTimeOfYear.setItemText(0, _translate("mapbioCollector", "Unknown", None))
        self.lblSectionTags.setText(_translate("mapbioCollector", "Tags", None))
        self.lblSectionNote.setText(_translate("mapbioCollector", "Note", None))
        self.pteSectionNote.setToolTip(_translate("mapbioCollector", "Enter note about this section", None))
        self.deUPStart.setDisplayFormat(_translate("mapbioCollector", "yyyy-MM-dd", None))
        self.lblUPEnd.setText(_translate("mapbioCollector", "End Date", None))
        self.deUPEnd.setDisplayFormat(_translate("mapbioCollector", "yyyy-MM-dd", None))
        self.lblTOYMonths.setText(_translate("mapbioCollector", "Months", None))
        self.lblCode.setText(_translate("mapbioCollector", "Primary Code", None))
        self.leCode.setToolTip(_translate("mapbioCollector", "Main content code", None))
        self.lblLegacyCode.setText(_translate("mapbioCollector", "Legacy Code", None))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpDetails), _translate("mapbioCollector", "Section Details", None))
        self.lblMediaStart.setText(_translate("mapbioCollector", "Media Start", None))
        self.lblMediaEnd.setText(_translate("mapbioCollector", "Media End", None))
        self.lblRecordingDate.setText(_translate("mapbioCollector", "Recorded", None))
        self.dteRecordingDate.setDisplayFormat(_translate("mapbioCollector", "yyyy-MM-dd HH:mm", None))
        self.spMediaStart.setToolTip(_translate("mapbioCollector", "Media index start value", None))
        self.tbSetStart.setToolTip(_translate("mapbioCollector", "Click to set start from current slide position", None))
        self.tbSetStart.setText(_translate("mapbioCollector", "S", None))
        self.spMediaEnd.setToolTip(_translate("mapbioCollector", "Media index end value", None))
        self.tbSetEnd.setToolTip(_translate("mapbioCollector", "Click to set end from current slide position", None))
        self.tbSetEnd.setText(_translate("mapbioCollector", "E", None))
        self.lblSearch.setText(_translate("mapbioCollector", "Search", None))
        self.tbSearchNext.setText(_translate("mapbioCollector", "...", None))
        self.tbSearchPrevious.setText(_translate("mapbioCollector", "...", None))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpSectionText), _translate("mapbioCollector", "Section Text", None))
        self.pbAddPhoto.setText(_translate("mapbioCollector", "Add", None))
        self.pbEditPhoto.setText(_translate("mapbioCollector", "Edit", None))
        self.pbRemovePhoto.setText(_translate("mapbioCollector", "Remove", None))
        self.twSectionContent.setTabText(self.twSectionContent.indexOf(self.tpPhotos), _translate("mapbioCollector", "Images", None))
        self.pbSaveSection.setToolTip(_translate("mapbioCollector", "Save edits section", None))
        self.pbSaveSection.setText(_translate("mapbioCollector", "Save", None))
        self.pbCancelSection.setToolTip(_translate("mapbioCollector", "Cancel edits to section", None))
        self.pbCancelSection.setText(_translate("mapbioCollector", "Cancel", None))
        self.pbDeleteSection.setToolTip(_translate("mapbioCollector", "Delete section", None))
        self.pbDeleteSection.setText(_translate("mapbioCollector", "Delete", None))
        self.tbPan.setToolTip(_translate("mapbioCollector", "Navigate the Map", None))
        self.tbPoint.setToolTip(_translate("mapbioCollector", "Place a point", None))
        self.tbLine.setToolTip(_translate("mapbioCollector", "Place a line", None))
        self.tbLine.setText(_translate("mapbioCollector", "...", None))
        self.tbPolygon.setToolTip(_translate("mapbioCollector", "Place a polygon", None))
        self.tbPolygon.setText(_translate("mapbioCollector", "...", None))
        self.tbEdit.setToolTip(_translate("mapbioCollector", "Edit the selected feature", None))
        self.tbEdit.setText(_translate("mapbioCollector", "...", None))
        self.tbMove.setToolTip(_translate("mapbioCollector", "Move the selected feature", None))
        self.tbMove.setText(_translate("mapbioCollector", "...", None))
        self.tbNonSpatial.setToolTip(_translate("mapbioCollector", "Insert a non-spatial section", None))
        self.tbNonSpatial.setText(_translate("mapbioCollector", "NS", None))
        self.tbZoomIn.setToolTip(_translate("mapbioCollector", "Zoom In", None))
        self.tbZoomIn.setText(_translate("mapbioCollector", "...", None))
        self.tbZoomOut.setToolTip(_translate("mapbioCollector", "Zoom Out", None))
        self.tbZoomOut.setText(_translate("mapbioCollector", "...", None))
        self.tbZoomData.setToolTip(_translate("mapbioCollector", "Zoom to Data Extent", None))
        self.tbZoomData.setText(_translate("mapbioCollector", "...", None))
        self.tbZoomArea.setToolTip(_translate("mapbioCollector", "Zoom to Study Area", None))
        self.tbZoomArea.setText(_translate("mapbioCollector", "...", None))
        self.tbSketchMode.setToolTip(_translate("mapbioCollector", "Sketch Mode - Draw lines in parts", None))
        self.tbSketchMode.setText(_translate("mapbioCollector", "SK", None))
        self.lblTimeOfDay.setToolTip(_translate("mapbioCollector", "Time of day", None))
        self.lblTimeOfDay.setText(_translate("mapbioCollector", "00:00:00", None))
        self.lblTimer.setToolTip(_translate("mapbioCollector", "Time elapsed in interview", None))
        self.lblTimer.setText(_translate("mapbioCollector", "00:00:00", None))
        self.tbMediaPlay.setToolTip(_translate("mapbioCollector", "Play / Pause Audio", None))
        self.hsSectionMedia.setToolTip(_translate("mapbioCollector", "Adjust playback position", None))
        self.cbFeatures.setText(_translate("mapbioCollector", "Show Features", None))
        self.cbLabels.setText(_translate("mapbioCollector", "Show Feature Labels", None))
        self.cbReference.setText(_translate("mapbioCollector", "Show Reference", None))
        self.cbBoundary.setText(_translate("mapbioCollector", "Show Boundary", None))

