# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapbio_interviewer.ui'
#
# Created: Fri Nov  7 15:05:43 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapbioInterviewer(object):
    def setupUi(self, mapbioInterviewer):
        mapbioInterviewer.setObjectName(_fromUtf8("mapbioInterviewer"))
        mapbioInterviewer.resize(405, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapbioInterviewer.sizePolicy().hasHeightForWidth())
        mapbioInterviewer.setSizePolicy(sizePolicy)
        mapbioInterviewer.setMinimumSize(QtCore.QSize(405, 700))
        mapbioInterviewer.setMaximumSize(QtCore.QSize(524287, 524287))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("interview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapbioInterviewer.setWindowIcon(icon)
        mapbioInterviewer.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        mapbioInterviewer.setWindowTitle(_fromUtf8("LOUIS Map Biographer - Interview Tool"))
        self.dcwLMB = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcwLMB.sizePolicy().hasHeightForWidth())
        self.dcwLMB.setSizePolicy(sizePolicy)
        self.dcwLMB.setMinimumSize(QtCore.QSize(405, 0))
        self.dcwLMB.setObjectName(_fromUtf8("dcwLMB"))
        self.gridLayout = QtGui.QGridLayout(self.dcwLMB)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frInterviewControls = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInterviewControls.sizePolicy().hasHeightForWidth())
        self.frInterviewControls.setSizePolicy(sizePolicy)
        self.frInterviewControls.setMinimumSize(QtCore.QSize(0, 100))
        self.frInterviewControls.setFrameShape(QtGui.QFrame.NoFrame)
        self.frInterviewControls.setFrameShadow(QtGui.QFrame.Plain)
        self.frInterviewControls.setLineWidth(0)
        self.frInterviewControls.setObjectName(_fromUtf8("frInterviewControls"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frInterviewControls)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vlConductInterview = QtGui.QVBoxLayout()
        self.vlConductInterview.setObjectName(_fromUtf8("vlConductInterview"))
        self.hlInterviewActions = QtGui.QHBoxLayout()
        self.hlInterviewActions.setObjectName(_fromUtf8("hlInterviewActions"))
        self.pbStart = QtGui.QPushButton(self.frInterviewControls)
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        self.hlInterviewActions.addWidget(self.pbStart)
        self.pbPause = QtGui.QPushButton(self.frInterviewControls)
        self.pbPause.setObjectName(_fromUtf8("pbPause"))
        self.hlInterviewActions.addWidget(self.pbPause)
        self.pbFinish = QtGui.QPushButton(self.frInterviewControls)
        self.pbFinish.setEnabled(False)
        self.pbFinish.setObjectName(_fromUtf8("pbFinish"))
        self.hlInterviewActions.addWidget(self.pbFinish)
        self.vlConductInterview.addLayout(self.hlInterviewActions)
        self.hlInterviewTools = QtGui.QHBoxLayout()
        self.hlInterviewTools.setSpacing(1)
        self.hlInterviewTools.setObjectName(_fromUtf8("hlInterviewTools"))
        self.tbPan = QtGui.QToolButton(self.frInterviewControls)
        self.tbPan.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPan.setMaximumSize(QtCore.QSize(28, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPan.setIcon(icon1)
        self.tbPan.setCheckable(True)
        self.tbPan.setObjectName(_fromUtf8("tbPan"))
        self.hlInterviewTools.addWidget(self.tbPan)
        self.tbPoint = QtGui.QToolButton(self.frInterviewControls)
        self.tbPoint.setEnabled(False)
        self.tbPoint.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPoint.setMaximumSize(QtCore.QSize(28, 28))
        self.tbPoint.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("point.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tbPoint.setIcon(icon2)
        self.tbPoint.setCheckable(True)
        self.tbPoint.setChecked(False)
        self.tbPoint.setObjectName(_fromUtf8("tbPoint"))
        self.hlInterviewTools.addWidget(self.tbPoint)
        self.tbLine = QtGui.QToolButton(self.frInterviewControls)
        self.tbLine.setMinimumSize(QtCore.QSize(28, 28))
        self.tbLine.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLine.setIcon(icon3)
        self.tbLine.setCheckable(True)
        self.tbLine.setObjectName(_fromUtf8("tbLine"))
        self.hlInterviewTools.addWidget(self.tbLine)
        self.tbPolygon = QtGui.QToolButton(self.frInterviewControls)
        self.tbPolygon.setMinimumSize(QtCore.QSize(28, 28))
        self.tbPolygon.setMaximumSize(QtCore.QSize(28, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPolygon.setIcon(icon4)
        self.tbPolygon.setCheckable(True)
        self.tbPolygon.setObjectName(_fromUtf8("tbPolygon"))
        self.hlInterviewTools.addWidget(self.tbPolygon)
        self.tbEdit = QtGui.QToolButton(self.frInterviewControls)
        self.tbEdit.setMinimumSize(QtCore.QSize(28, 28))
        self.tbEdit.setMaximumSize(QtCore.QSize(28, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("edit_node.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEdit.setIcon(icon5)
        self.tbEdit.setCheckable(True)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.hlInterviewTools.addWidget(self.tbEdit)
        self.tbMove = QtGui.QToolButton(self.frInterviewControls)
        self.tbMove.setMinimumSize(QtCore.QSize(28, 28))
        self.tbMove.setMaximumSize(QtCore.QSize(28, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("edit_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMove.setIcon(icon6)
        self.tbMove.setCheckable(True)
        self.tbMove.setObjectName(_fromUtf8("tbMove"))
        self.hlInterviewTools.addWidget(self.tbMove)
        self.vlLeftOfNS = QtGui.QFrame(self.frInterviewControls)
        self.vlLeftOfNS.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfNS.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfNS.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfNS.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfNS.setObjectName(_fromUtf8("vlLeftOfNS"))
        self.hlInterviewTools.addWidget(self.vlLeftOfNS)
        self.tbNonSpatial = QtGui.QToolButton(self.frInterviewControls)
        self.tbNonSpatial.setMinimumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setMaximumSize(QtCore.QSize(28, 28))
        self.tbNonSpatial.setCheckable(False)
        self.tbNonSpatial.setObjectName(_fromUtf8("tbNonSpatial"))
        self.hlInterviewTools.addWidget(self.tbNonSpatial)
        self.vlLeftOfClock = QtGui.QFrame(self.frInterviewControls)
        self.vlLeftOfClock.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfClock.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfClock.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfClock.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfClock.setObjectName(_fromUtf8("vlLeftOfClock"))
        self.hlInterviewTools.addWidget(self.vlLeftOfClock)
        self.lblTimeOfDay = QtGui.QLabel(self.frInterviewControls)
        self.lblTimeOfDay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimeOfDay.setObjectName(_fromUtf8("lblTimeOfDay"))
        self.hlInterviewTools.addWidget(self.lblTimeOfDay)
        self.vlLeftOfTimer = QtGui.QFrame(self.frInterviewControls)
        self.vlLeftOfTimer.setMinimumSize(QtCore.QSize(2, 0))
        self.vlLeftOfTimer.setMaximumSize(QtCore.QSize(2, 30))
        self.vlLeftOfTimer.setFrameShape(QtGui.QFrame.VLine)
        self.vlLeftOfTimer.setFrameShadow(QtGui.QFrame.Sunken)
        self.vlLeftOfTimer.setObjectName(_fromUtf8("vlLeftOfTimer"))
        self.hlInterviewTools.addWidget(self.vlLeftOfTimer)
        self.lblTimer = QtGui.QLabel(self.frInterviewControls)
        self.lblTimer.setScaledContents(False)
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName(_fromUtf8("lblTimer"))
        self.hlInterviewTools.addWidget(self.lblTimer)
        self.vlConductInterview.addLayout(self.hlInterviewTools)
        self.hlBelowToolBar = QtGui.QFrame(self.frInterviewControls)
        self.hlBelowToolBar.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowToolBar.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowToolBar.setObjectName(_fromUtf8("hlBelowToolBar"))
        self.vlConductInterview.addWidget(self.hlBelowToolBar)
        self.hlSectionInfo = QtGui.QHBoxLayout()
        self.hlSectionInfo.setObjectName(_fromUtf8("hlSectionInfo"))
        self.vlSectionList = QtGui.QVBoxLayout()
        self.vlSectionList.setObjectName(_fromUtf8("vlSectionList"))
        self.lblSectionList = QtGui.QLabel(self.frInterviewControls)
        self.lblSectionList.setObjectName(_fromUtf8("lblSectionList"))
        self.vlSectionList.addWidget(self.lblSectionList)
        self.lwSectionList = QtGui.QListWidget(self.frInterviewControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSectionList.sizePolicy().hasHeightForWidth())
        self.lwSectionList.setSizePolicy(sizePolicy)
        self.lwSectionList.setMinimumSize(QtCore.QSize(100, 0))
        self.lwSectionList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lwSectionList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSectionList.setObjectName(_fromUtf8("lwSectionList"))
        self.vlSectionList.addWidget(self.lwSectionList)
        self.hlSectionInfo.addLayout(self.vlSectionList)
        self.grSectionEdit = QtGui.QGridLayout()
        self.grSectionEdit.setObjectName(_fromUtf8("grSectionEdit"))
        self.cbFeatureStatus = QtGui.QComboBox(self.frInterviewControls)
        self.cbFeatureStatus.setObjectName(_fromUtf8("cbFeatureStatus"))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.cbFeatureStatus.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbFeatureStatus, 3, 2, 1, 1)
        self.lblTimePeriod = QtGui.QLabel(self.frInterviewControls)
        self.lblTimePeriod.setObjectName(_fromUtf8("lblTimePeriod"))
        self.grSectionEdit.addWidget(self.lblTimePeriod, 4, 1, 1, 1)
        self.lblTags = QtGui.QLabel(self.frInterviewControls)
        self.lblTags.setObjectName(_fromUtf8("lblTags"))
        self.grSectionEdit.addWidget(self.lblTags, 2, 1, 1, 1)
        self.lblSpatialFeature = QtGui.QLabel(self.frInterviewControls)
        self.lblSpatialFeature.setObjectName(_fromUtf8("lblSpatialFeature"))
        self.grSectionEdit.addWidget(self.lblSpatialFeature, 3, 1, 1, 1)
        self.cbSectionSecurity = QtGui.QComboBox(self.frInterviewControls)
        self.cbSectionSecurity.setObjectName(_fromUtf8("cbSectionSecurity"))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.cbSectionSecurity.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbSectionSecurity, 1, 2, 1, 1)
        self.cbAnnualVariation = QtGui.QComboBox(self.frInterviewControls)
        self.cbAnnualVariation.setObjectName(_fromUtf8("cbAnnualVariation"))
        self.cbAnnualVariation.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbAnnualVariation, 5, 2, 1, 1)
        self.lblAnnualVariation = QtGui.QLabel(self.frInterviewControls)
        self.lblAnnualVariation.setObjectName(_fromUtf8("lblAnnualVariation"))
        self.grSectionEdit.addWidget(self.lblAnnualVariation, 5, 1, 1, 1)
        self.leCode = QtGui.QLineEdit(self.frInterviewControls)
        self.leCode.setEnabled(False)
        self.leCode.setDragEnabled(False)
        self.leCode.setReadOnly(True)
        self.leCode.setObjectName(_fromUtf8("leCode"))
        self.grSectionEdit.addWidget(self.leCode, 0, 2, 1, 1)
        self.pteTags = QtGui.QPlainTextEdit(self.frInterviewControls)
        self.pteTags.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteTags.sizePolicy().hasHeightForWidth())
        self.pteTags.setSizePolicy(sizePolicy)
        self.pteTags.setMinimumSize(QtCore.QSize(0, 25))
        self.pteTags.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteTags.setObjectName(_fromUtf8("pteTags"))
        self.grSectionEdit.addWidget(self.pteTags, 2, 2, 1, 1)
        self.lblSectionNote = QtGui.QLabel(self.frInterviewControls)
        self.lblSectionNote.setObjectName(_fromUtf8("lblSectionNote"))
        self.grSectionEdit.addWidget(self.lblSectionNote, 6, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.frInterviewControls)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.grSectionEdit.addWidget(self.lblCode, 0, 1, 1, 1)
        self.cbTimePeriod = QtGui.QComboBox(self.frInterviewControls)
        self.cbTimePeriod.setObjectName(_fromUtf8("cbTimePeriod"))
        self.cbTimePeriod.addItem(_fromUtf8(""))
        self.grSectionEdit.addWidget(self.cbTimePeriod, 4, 2, 1, 1)
        self.lblSecurity = QtGui.QLabel(self.frInterviewControls)
        self.lblSecurity.setObjectName(_fromUtf8("lblSecurity"))
        self.grSectionEdit.addWidget(self.lblSecurity, 1, 1, 1, 1)
        self.pteSectionNote = QtGui.QPlainTextEdit(self.frInterviewControls)
        self.pteSectionNote.setObjectName(_fromUtf8("pteSectionNote"))
        self.grSectionEdit.addWidget(self.pteSectionNote, 6, 2, 1, 1)
        self.hlSectionInfo.addLayout(self.grSectionEdit)
        self.vlConductInterview.addLayout(self.hlSectionInfo)
        self.hlSectionActions = QtGui.QHBoxLayout()
        self.hlSectionActions.setObjectName(_fromUtf8("hlSectionActions"))
        self.pbSaveSection = QtGui.QPushButton(self.frInterviewControls)
        self.pbSaveSection.setObjectName(_fromUtf8("pbSaveSection"))
        self.hlSectionActions.addWidget(self.pbSaveSection)
        self.pbCancelSection = QtGui.QPushButton(self.frInterviewControls)
        self.pbCancelSection.setEnabled(False)
        self.pbCancelSection.setObjectName(_fromUtf8("pbCancelSection"))
        self.hlSectionActions.addWidget(self.pbCancelSection)
        self.pbDeleteSection = QtGui.QPushButton(self.frInterviewControls)
        self.pbDeleteSection.setObjectName(_fromUtf8("pbDeleteSection"))
        self.hlSectionActions.addWidget(self.pbDeleteSection)
        self.vlConductInterview.addLayout(self.hlSectionActions)
        self.hlBelowSectionEdit = QtGui.QFrame(self.frInterviewControls)
        self.hlBelowSectionEdit.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowSectionEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowSectionEdit.setObjectName(_fromUtf8("hlBelowSectionEdit"))
        self.vlConductInterview.addWidget(self.hlBelowSectionEdit)
        self.lblCodeList = QtGui.QLabel(self.frInterviewControls)
        self.lblCodeList.setObjectName(_fromUtf8("lblCodeList"))
        self.vlConductInterview.addWidget(self.lblCodeList)
        self.lwProjectCodes = QtGui.QListWidget(self.frInterviewControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwProjectCodes.sizePolicy().hasHeightForWidth())
        self.lwProjectCodes.setSizePolicy(sizePolicy)
        self.lwProjectCodes.setMinimumSize(QtCore.QSize(0, 50))
        self.lwProjectCodes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwProjectCodes.setProperty("showDropIndicator", False)
        self.lwProjectCodes.setDragEnabled(False)
        self.lwProjectCodes.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lwProjectCodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwProjectCodes.setViewMode(QtGui.QListView.IconMode)
        self.lwProjectCodes.setObjectName(_fromUtf8("lwProjectCodes"))
        self.vlConductInterview.addWidget(self.lwProjectCodes)
        self.lblAudioStatus = QtGui.QLabel(self.frInterviewControls)
        self.lblAudioStatus.setObjectName(_fromUtf8("lblAudioStatus"))
        self.vlConductInterview.addWidget(self.lblAudioStatus)
        self.gridLayout_2.addLayout(self.vlConductInterview, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frInterviewControls, 4, 0, 1, 1)
        self.frInterviewSelection = QtGui.QFrame(self.dcwLMB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInterviewSelection.sizePolicy().hasHeightForWidth())
        self.frInterviewSelection.setSizePolicy(sizePolicy)
        self.frInterviewSelection.setMinimumSize(QtCore.QSize(0, 150))
        self.frInterviewSelection.setFrameShape(QtGui.QFrame.NoFrame)
        self.frInterviewSelection.setFrameShadow(QtGui.QFrame.Plain)
        self.frInterviewSelection.setLineWidth(0)
        self.frInterviewSelection.setObjectName(_fromUtf8("frInterviewSelection"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frInterviewSelection)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hlParticipants = QtGui.QHBoxLayout()
        self.hlParticipants.setObjectName(_fromUtf8("hlParticipants"))
        self.lblParticipants = QtGui.QLabel(self.frInterviewSelection)
        self.lblParticipants.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblParticipants.setObjectName(_fromUtf8("lblParticipants"))
        self.hlParticipants.addWidget(self.lblParticipants)
        self.pteParticipants = QtGui.QPlainTextEdit(self.frInterviewSelection)
        self.pteParticipants.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteParticipants.sizePolicy().hasHeightForWidth())
        self.pteParticipants.setSizePolicy(sizePolicy)
        self.pteParticipants.setMinimumSize(QtCore.QSize(0, 25))
        self.pteParticipants.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pteParticipants.setObjectName(_fromUtf8("pteParticipants"))
        self.hlParticipants.addWidget(self.pteParticipants)
        self.gridLayout_3.addLayout(self.hlParticipants, 1, 0, 1, 1)
        self.hlInterviewButtons = QtGui.QHBoxLayout()
        self.hlInterviewButtons.setObjectName(_fromUtf8("hlInterviewButtons"))
        self.pbConductInterview = QtGui.QPushButton(self.frInterviewSelection)
        self.pbConductInterview.setEnabled(False)
        self.pbConductInterview.setObjectName(_fromUtf8("pbConductInterview"))
        self.hlInterviewButtons.addWidget(self.pbConductInterview)
        self.pbClose = QtGui.QPushButton(self.frInterviewSelection)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlInterviewButtons.addWidget(self.pbClose)
        self.gridLayout_3.addLayout(self.hlInterviewButtons, 3, 0, 1, 1)
        self.hlAudio = QtGui.QHBoxLayout()
        self.hlAudio.setObjectName(_fromUtf8("hlAudio"))
        self.lblRecordAudio = QtGui.QLabel(self.frInterviewSelection)
        self.lblRecordAudio.setObjectName(_fromUtf8("lblRecordAudio"))
        self.hlAudio.addWidget(self.lblRecordAudio)
        self.cbRecordAudio = QtGui.QComboBox(self.frInterviewSelection)
        self.cbRecordAudio.setEnabled(False)
        self.cbRecordAudio.setObjectName(_fromUtf8("cbRecordAudio"))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.cbRecordAudio.addItem(_fromUtf8(""))
        self.hlAudio.addWidget(self.cbRecordAudio)
        self.tbAudioSettings = QtGui.QToolButton(self.frInterviewSelection)
        self.tbAudioSettings.setMinimumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setMaximumSize(QtCore.QSize(20, 28))
        self.tbAudioSettings.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tbAudioSettings.setObjectName(_fromUtf8("tbAudioSettings"))
        self.hlAudio.addWidget(self.tbAudioSettings)
        self.pbSoundTest = QtGui.QPushButton(self.frInterviewSelection)
        self.pbSoundTest.setEnabled(False)
        self.pbSoundTest.setObjectName(_fromUtf8("pbSoundTest"))
        self.hlAudio.addWidget(self.pbSoundTest)
        self.gridLayout_3.addLayout(self.hlAudio, 2, 0, 1, 1)
        self.hlCodeInterview = QtGui.QHBoxLayout()
        self.hlCodeInterview.setObjectName(_fromUtf8("hlCodeInterview"))
        self.lblProjectCode = QtGui.QLabel(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProjectCode.sizePolicy().hasHeightForWidth())
        self.lblProjectCode.setSizePolicy(sizePolicy)
        self.lblProjectCode.setMinimumSize(QtCore.QSize(0, 0))
        self.lblProjectCode.setObjectName(_fromUtf8("lblProjectCode"))
        self.hlCodeInterview.addWidget(self.lblProjectCode)
        self.leProjectCode = QtGui.QLineEdit(self.frInterviewSelection)
        self.leProjectCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectCode.sizePolicy().hasHeightForWidth())
        self.leProjectCode.setSizePolicy(sizePolicy)
        self.leProjectCode.setMinimumSize(QtCore.QSize(0, 0))
        self.leProjectCode.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leProjectCode.setObjectName(_fromUtf8("leProjectCode"))
        self.hlCodeInterview.addWidget(self.leProjectCode)
        self.lblInterview = QtGui.QLabel(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInterview.sizePolicy().hasHeightForWidth())
        self.lblInterview.setSizePolicy(sizePolicy)
        self.lblInterview.setMinimumSize(QtCore.QSize(0, 0))
        self.lblInterview.setObjectName(_fromUtf8("lblInterview"))
        self.hlCodeInterview.addWidget(self.lblInterview)
        self.cbInterviewSelection = QtGui.QComboBox(self.frInterviewSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInterviewSelection.sizePolicy().hasHeightForWidth())
        self.cbInterviewSelection.setSizePolicy(sizePolicy)
        self.cbInterviewSelection.setMinimumSize(QtCore.QSize(150, 0))
        self.cbInterviewSelection.setObjectName(_fromUtf8("cbInterviewSelection"))
        self.hlCodeInterview.addWidget(self.cbInterviewSelection)
        self.gridLayout_3.addLayout(self.hlCodeInterview, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frInterviewSelection, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.dcwLMB)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        mapbioInterviewer.setWidget(self.dcwLMB)

        self.retranslateUi(mapbioInterviewer)
        self.cbRecordAudio.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapbioInterviewer)

    def retranslateUi(self, mapbioInterviewer):
        self.pbStart.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Start or continue recording the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setText(QtGui.QApplication.translate("mapbioInterviewer", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Pause the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setText(QtGui.QApplication.translate("mapbioInterviewer", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Finish the interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbFinish.setText(QtGui.QApplication.translate("mapbioInterviewer", "Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPan.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLine.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPolygon.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMove.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNonSpatial.setText(QtGui.QApplication.translate("mapbioInterviewer", "NS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimeOfDay.setText(QtGui.QApplication.translate("mapbioInterviewer", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimer.setText(QtGui.QApplication.translate("mapbioInterviewer", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionList.setText(QtGui.QApplication.translate("mapbioInterviewer", "Sections", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Is Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.cbFeatureStatus.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "From Section #", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTimePeriod.setText(QtGui.QApplication.translate("mapbioInterviewer", "Use Period", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTags.setText(QtGui.QApplication.translate("mapbioInterviewer", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpatialFeature.setText(QtGui.QApplication.translate("mapbioInterviewer", "Spatial Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Community", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(2, QtGui.QApplication.translate("mapbioInterviewer", "Restricted", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSectionSecurity.setItemText(3, QtGui.QApplication.translate("mapbioInterviewer", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAnnualVariation.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAnnualVariation.setText(QtGui.QApplication.translate("mapbioInterviewer", "Annual Var.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSectionNote.setText(QtGui.QApplication.translate("mapbioInterviewer", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCode.setText(QtGui.QApplication.translate("mapbioInterviewer", "Content Code", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimePeriod.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSecurity.setText(QtGui.QApplication.translate("mapbioInterviewer", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Save Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Cancel Section Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Delete Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteSection.setText(QtGui.QApplication.translate("mapbioInterviewer", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodeList.setText(QtGui.QApplication.translate("mapbioInterviewer", "Project Code List", None, QtGui.QApplication.UnicodeUTF8))
        self.lwProjectCodes.setSortingEnabled(False)
        self.lblAudioStatus.setText(QtGui.QApplication.translate("mapbioInterviewer", "Audio recording not selected", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParticipants.setText(QtGui.QApplication.translate("mapbioInterviewer", "Participant(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConductInterview.setText(QtGui.QApplication.translate("mapbioInterviewer", "Conduct Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("mapbioInterviewer", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRecordAudio.setText(QtGui.QApplication.translate("mapbioInterviewer", "Record Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(0, QtGui.QApplication.translate("mapbioInterviewer", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRecordAudio.setItemText(1, QtGui.QApplication.translate("mapbioInterviewer", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setToolTip(QtGui.QApplication.translate("mapbioInterviewer", "Select Playback Device", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAudioSettings.setText(QtGui.QApplication.translate("mapbioInterviewer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSoundTest.setText(QtGui.QApplication.translate("mapbioInterviewer", "No Sound Test Required", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectCode.setText(QtGui.QApplication.translate("mapbioInterviewer", "Project Code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterview.setText(QtGui.QApplication.translate("mapbioInterviewer", "Interview", None, QtGui.QApplication.UnicodeUTF8))

